### ISSUE TITLE
Cycle exact emulation

### ISSUE THREAD

**Issue by bspinner** [midwan/amiberry#150] opened 2017-11-11 03:42 UTC
Cycle exact emulation seems to be necessary to get rid of the variations in emulation speed. Sometimes games run 3x as fast as they should.

This is a feature that's lacking since the first UAE to ARM port. Therefore I guess this is non-trivial?

**Comment by blinkydoos** [comment] 2017-11-11 10:31
Yeah, this is a feature that will fix a lot of the issues reported here and everywhere, especially for WHDLoad games. It doesn't look very promising though unless Midwan knows how to do it. The original author, TomB said that he will only add features that work well on his Pandora/Pyra Handheld. Unfortunately those handhelds are not the most powerful and neither is a Pi 3. 68020+ Cycle Accuracy (which we will need for WHDLoad games) needs quite a bit of power. 68000 CE will probably work well for most games but in comparison on WinUAE that needs at least a 1.3Ghz Atom otherwise you get choppy audio. We can only hope.

**Comment by HoraceAndTheSpider** [comment] 2017-11-11 10:47
Cycle exact is being looked at, as are speed improvements.

**Comment by blinkydoos** [comment] 2017-11-11 10:58
Nice, could I ask who's on the case ? TomB doesn't have a Github Repo (that I know of) so I wondered how you knew ? This would work great on Android (but the OS is locked at 60Hz so not a real Amiga experience). Hopefully the Pi won't melt !

**Comment by HoraceAndTheSpider** [comment] 2017-11-11 11:19
how do I know?

We (all of the contributors and Devs of Amiberry) talk to each other. 

TomB doesn’t need a repo, and is providing contributions directly.

**Comment by blinkydoos** [comment] 2017-11-11 12:37
That was my point, can I read about these other changes planned somewhere ? The only place I see TomB is the Pandora forums. You only added the custom controls so it's either Midwan or TomB that's doing the technical emulation stuff (no offence !), so where was it reported that Cycle Exact is being looked at ?

**Comment by midwan** [comment] 2017-11-11 12:46
Cycle-exact mode is coming in a future update.
I had started implementing it, but since TomB joined the effort as well and he offered to add it instead, I will focus on getting some bugs fixed instead for now.

It's not exactly a trivial thing, and we'll have to see how well the platform performs with it, but we'll see in due time.

TomB is no longer pursuing new versions for Pandora (since the hardware there is rather limited) but is interested in helping out with the Pi version.

**Comment by blinkydoos** [comment] 2017-11-11 13:00
Thanks for the confirmation @midwan . As all the ARM builds are being merged (Android, Pandora, Pi etc.) wouldn't it make more sense to call the emulator UAE4Arm again ? For instance, the Android version will be called Amiberry ?

**Comment by bspinner** [comment] 2017-11-11 13:51
Glad to hear you're working on it. Until then: I just noticed emulation works smoothest when I choose "fastest" as cpu clock speed.

**Comment by HoraceAndTheSpider** [comment] 2017-11-11 13:51
I guess this is some kind of joke?

Completely rewriting the controls system,  adding parallel ports and other functions obviously this means I won’t be looking at any other areas, since it seems you do not think I am good enough for that. 

We have places other than here where we collectively discuss developments. @midwan and I talk almost daily. 

I think based on this I will now stick to doing updates that way only.

**Comment by blinkydoos** [comment] 2017-11-11 14:16
@HoraceAndTheSpider What just happened here ? Your branch and all your commits are for the controller and Midwan and TomB have been doing the Actual Amiga emulation since day one. I never implied that you "weren't good enough" ! I didn't know you were contributing to the Cycle Accuracy code, that's why i asked who was on the case. @midwan What just happened here ?

**Comment by HoraceAndTheSpider** [comment] 2017-11-11 14:40
Yep. My current branch is for controls, which needed (and got) a massive overhaul. Future branches may work on other things.

What happened was you chose to make an assumption over who is contributing what and used that as a basis to imply I wouldn’t be able/willing to be involved in anything else on the emulation code. 

when there is so much that happens behind the scenes, which frankly , no one is under any duty to share.... why do you need to know who is working on what? Why was it not enough to be told that it was being worked on?

I’ve spent a lot of time answering queries on here, and often have been made to “justify” my work, even when it is not finished. I have no problem helping people, but don’t be surprised if I do take offence when assumptions like that are made.

**Comment by blinkydoos** [comment] 2017-11-11 15:37
`What happened was you chose to make an assumption over who is contributing what and used that as a basis to imply I wouldn’t be able/willing to be involved in anything else on the emulation code.`

And you made a hypocritical assumption that I said you "weren't good enough". Because you have done things that never made it into a commit, how was I supposed to know ? You just turned into Mr Hyde ! I asked who was working on Cycle Accuracy because I was curious, and @midwan told me, no need to imply that I called you shit. When I see your commits on Chipset emulation/accuracy etc. then opinions will change again. A lot of people have asked questions that you chose to answer, "comments like the above" (plural ?) are how you chose to perceive them. I'm a 39 year old woman so let's not get into a petty argument about something so trivial.

**Comment by HoraceAndTheSpider** [comment] 2017-11-11 15:57
OK, this is enough for me.

All i ask is to consider how certain comments may read (even if you perhaps do not mean them to). 
I have done everything possible to try and answer many questions, and have no desire to have any such arguments also.

**Comment by bspinner** [comment] 2017-11-19 11:42
Hm, can we delete the off topic discussion?
Could be discouraging other people to join development/contribute.

**Comment by midwan** [comment] 2017-11-19 11:56
@blinkydoos The codebase is being harmonized but it will still be called Amiberry.
We've made changes from the base version that will go to all the platforms we support, and the naming needs to reflect that.
The Android target will also be called Amiberry, since it will be different from UAE4Arm in functionality, bug corrections, etc.

**Comment by ZappaUtopia** [comment] 2018-02-13 18:13
I read somewhere a few months ago (maybe Facebook ?) that TomB was testing 68000 Cycle Accuracy code . Is this still on-going or was the idea scrapped ? I know that the Pi won't be fast enough for the majority of stuff but the future Android version will run it with ease. Not really bothered about 68020+ Cycle Accuracy as it still isn't accurate on Windows due to lack of documentation, just Toni Willen's good guess work.

**Comment by Naviara** [comment] 2018-02-14 07:40
If cylce exact is not working for the PI, at least a Speed Throttle (if possible) would be nice, so we can adjust the speed where games are running too fast manually. These is mostly experienced with all WHDLoad games wich have to use the 68020 CPU. "Underclocking" it to 7 Mhz doesn't change the speed. (for instance Populous 2 or Star Wars).

**Comment by HoraceAndTheSpider** [comment] 2018-02-16 08:44
Run the Whdload versions and Switch on “wait for blitter” and this will fix the speed I those games.

These games often had DBF loops used for timing and these are corrected with proper blitwaits in most Whdload fixes.

I’ve have run some tests on this (see the uae Config Maker GitHub) benchmarking against a real A600 using ADF versions , Whdload versions and against Amiberry , so I can confirm this defiantly achieves the correct speed.

I play Populous 2 regularly on Amiberry :)

**Comment by HoraceAndTheSpider** [comment] 2018-02-16 08:52
https://github.com/HoraceAndTheSpider/UAEConfigMaker/issues/35#issuecomment-366175901

Post 5.



@naviata

I have filmed 4 videos of NZS, which suffers from the speed issue badly,  on level one. Moved Tiki across the screen to his death. I then freeze video at the first frame of the 5 second mark for comparrison.

**1 - Real A600, 68000 only Gotek loaded ADF.**

http://www.ultimateamiga.co.uk/HostedProjects/RetroPieAmiga/debug/NZS_A600.PNG

We can see here that Tiki should have reached certain doom and be showing a 'red' electrocution . As a test on real hardware, the original processor and using the original game (no WHD blitter patches etc) this should be the benchmark for the speed we are trying to achieve.

I will add that there is a 'smoothness' factor lacking and will cover that in a mo.

**2 - Amiberry/Pi, 68000 , WHDLoad - Immediate Blitters**

http://www.ultimateamiga.co.uk/HostedProjects/RetroPieAmiga/debug/NZS_PI_68000_IMMEDIATE.PNG

The reason this should be correct is that the game is not hampered by the newly added blitterwaits, instead performing its game cycle in processing time to the original. Amazingly, as you can see the returned the exact same frame as the A600 mode.

**3 - Amiberry/Pi, 68020 , WHDLoad - Wait for Blitter**

http://www.ultimateamiga.co.uk/HostedProjects/RetroPieAmiga/debug/NZS_PI_68020_NORMAL.PNG

As suspected, not perfect, this does indeed run a little fast, but not much. As you can see Tiki is not touching the ground yet in his electrocution animation. Over the course of the 5 seconds, it is only 1 frameaway from where he should be (the next animation frame is the same as the above two)

**4 - Amiberry/Pi, 68000 , WHDLoad - Normal Blitter**

http://www.ultimateamiga.co.uk/HostedProjects/RetroPieAmiga/debug/NZS_PI_68000_NORMAL.PNG

Miles off i'm afraid. The speed which i stated was slower and choppy (more so than the A600), and the game is simply considerably slower than it should be. The above demonstrates this really is down to the added blitter waits since that setting alone can solve the problem (and perhaps the slave should be updated to allow their removal)

Obviously this test has a slight wiggle room for human error, but gives a nice visual indicator for comparions.... in essence, the 68020 mode could even be performing exactly right in terms of time, with the blitter wait enabled should be very close. It also seems to have an added smoothness that was not present on the A600 - either this this the cause of a display refresh (i.e. Indivisions fault) or the game is coded well enough to take advantage of a few extra cpu cycles.

**Comment by Naviara** [comment] 2018-02-16 09:03
@HoraceAndTheSpider 
Thank you, I will try that :-)

**Comment by midwan** [comment] 2018-02-17 18:59
To avoid keeping this issue around as Open, as there's nothing else to do until this is implemented in a future version, I'm closing it and we'll add an entry in the Wiki FAQ page about it instead.

**Closed by midwan** 2018-02-17 18:59 UTC
Labels: compatibility, enhancement
