### ISSUE TITLE
Fix cursor on XU4

### ISSUE THREAD

**Issue by bspinner** [midwan/amiberry#148] opened 2017-11-07 18:10 UTC
As already mentioned here #144:

The cursor is not displayed because this
```c
if (cursorSurface)
{
    cursor = SDL_CreateColorCursor(cursorSurface, 0, 0);
}
```
Leads to an `nullptr`, so the call failed. `SDL_error` says *Cursors are not currently supported*. 🤔 
I am using `libsdl2-dev_2.0.6+1mali_armhf` as compiled by `retropie_packages.sh sdl2`

I'll investigate and - if possible - propose a fix.

**Comment by bspinner** [comment] 2017-11-08 18:11
This looks like a configuration problem. I'm currently messing around with X11/graphics driver stuff and was able to start it and had a cursor.

@midwan Are you running a X11 server?

**Comment by midwan** [comment] 2017-11-08 18:21
Interesting...

Most my tests were not using X11 at all, but I believe I also tested it under X11 on the Pi. I'll have to re-test it to make sure, I can get back to you after that.

The majority of testing was done on Raspbian Jessie, but now that I have Stretch things seem to behave even better (had major problems when OpenGL was enabled under Jessie for example). I've tested the SDL1 version extensively on Stretch without problems, but I haven't done that much with the SDL2 one yet.

**Comment by bspinner** [comment] 2017-11-08 19:14
https://github.com/RetroPie/SDL-mirror/find/mali-2.0.6

There are several mouse implementations. Looks like my libsdl binary is either missing a compile flag (e.g. one for the fbdirect mouse?) or there's no supported mouse without x11 etc.

**Comment by midwan** [comment] 2017-11-08 21:03
Just tested it again on Stretch, under X11 - no problems with the mouse cursor on the Pi at least.

**Comment by bspinner** [comment] 2017-11-09 14:51
Looking at the sdl mouse implementations you either need the Rpi graphics stuff, X11, drm, Wayland or directfb.
Since this is some things users can configure as they like, we should make sure that the cursor is active when actually supported only.

**Comment by HoraceAndTheSpider** [comment] 2017-11-09 15:04
The new controller changes have extra control of the gui from the SDL inputs (hat/dpad buttons at the moment)

Is it a case that without these we cannot display the cursor at all? I had planned to see if it was possible to add cursor control from an analogue stick... this would help if the issue is only with control and not display, but perhaps I could still use this method to push the focus around (like using cursor keys or the dpad) 

(Just a thought!)

**Comment by bspinner** [comment] 2017-11-09 16:23
@HoraceAndTheSpider The SDL_mouse implementations seem to handle displaying the cursor at the correct position etc (I just took a *brief* look at them) => no cursor without SDL_mouse.
Not sure how hard it is to create an implementation for [mali](https://github.com/RetroPie/SDL-mirror/tree/mali-2.0.6/src/video/mali-fbdev).

**Comment by midwan** [comment] 2017-11-09 17:29
@bspinner ok, so then we'll have to find a way to detect if it's supported/working on the system it's running on or not, and adapt the code accordingly. :)

**Comment by HoraceAndTheSpider** [comment] 2017-11-09 18:45
Well at least we have the fall back now for Controller Input.

I will look to add control of the “focus” from axis 0/1 and we can always add cursor control for 2/3 later

**Comment by bspinner** [comment] 2017-11-14 19:14
#153 handles missing cursor support. Or tries to... :)

**Comment by midwan** [comment] 2017-11-19 09:50
@bspinner Is it working OK for you with the code we merged in?
Can we close this issue in that case?

**Comment by bspinner** [comment] 2017-11-19 10:45
There's still no cursor, but the mouse is completely disabled for the GUI if unsupported now.
The actual fix must be done in SDL2 itself (implementation of mouse for Mali). So we can close this, since the error is to be fixed in a different code base

**Comment by midwan** [comment] 2017-11-19 10:46
OK, thanks for confirming

**Closed by midwan** 2017-11-19 10:46 UTC
