### ISSUE TITLE
USB Joystick Competition Pro switches Port 0 and 1 on beta 2021-02-08

### ISSUE THREAD

**Issue by phipslk** [midwan/amiberry#770] opened 2021-02-15 14:50 UTC
As soon as I plug the Speedlink competition pro USB in, the mouseport (0) and joystickport (1) are switched or both set to "none".

If I disable mouse/joystick Autoswitch on input table before starting emulation, the ports are kept in right order and not switched.

When I activate autoswitch then during emulation, the ports are switched (or set to "none"), and that can't be redone.

It doesn't matter if the "autofire" button on the joystick itself is activated or not.

**Comment by midwan** [comment] 2021-02-22 21:01
@phipslk 
Do you have other devices connected, besides the Mouse and the Competition Pro joystick? E.g. a second joystick?

**Comment by amyren1966** [comment] 2021-02-26 12:30
I am unable to reproduce this.
I have both the Competition Pro and the Competition Pro Aniversary Edition.
I am using Manjaro OS, with 64 bit Amiberry dev 2021-02-08 version on my RPi4.

For me the joysticks needs to be plugged before launcing amiberry, or else they will not be listed. Nothing happens if I plug them in after the amiberry GUI is launced.
When I plug either of these joysticks, and then launch amiberry, Port 0 will always be System Mouse (unchanged). Port 1 will change from <none> to "Competition Pro" or to "PC Game Controller" for the aniversary edition.
If I plug in both, it will still show System Mouse in port 0 and port 0 will list the joystick that was plugged in first.

I just updated to dev version 2021-02-15 and it also works like this.

**Comment by midwan** [comment] 2021-02-26 13:05
@amyren1966 
Thanks for the feedback. I don't have such a joystick to test with here, but no other controller I've tested shows this kind of behavior.

@phipslk also mentioned that it's only with this joystick that the problem occurs for him, others work fine - still a mystery on why exactly. :)

**Comment by midwan** [comment] 2021-04-09 14:50
Finally got a Competition Pro joystick to test with here, today. It's the latest model available (SL-650212) and the only one I could find on the market.
I still cannot recreate the specific problem mentioned above, however.

**Comment by amyren1966** [comment] 2021-04-09 16:47
Congratulation with the new joystick :) That is the same model no that is written on the one I have, branded 20 years Anniversary Edition.

**Comment by midwan** [comment] 2021-04-10 19:38
Closing this, since it seems to be unique to the case reported above. Nobody else can recreate it, it seems.

**Closed by midwan** 2021-04-10 19:38 UTC
Labels: can't recreate
