### ISSUE TITLE
(RPi 4) Corrupted sprites in Batman on 4.1.1

### ISSUE THREAD

**Issue by SeraphisCain** [midwan/amiberry#793] opened 2021-04-04 22:16 UTC
While testing the controller issue from my previous thread, I ran across this issue. On 4.1.1, the player, enemy, and projectile sprites in Batman are heavily corrupted. When going back to the 3.3 binary from RetroPie's repo, the issue is not present.

Example video:
https://www.dropbox.com/s/1cd40dqtpxkbwd7/VID_20210404_175854546.mp4?dl=0

Thus far I've only seen it in Batman. 

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by midwan** [comment] 2021-04-05 21:49
This seems to be fixable by setting `CPU=68000` in the XML for the title, also.

**Comment by midwan** [comment] 2021-04-07 15:58
This is actually fixed in `dev` with the latest merges from WinUAE (custom chipset improvements), but that version is not ready to be released yet. It works with 020/14MHz without glitches.

**Comment by midwan** [comment] 2021-09-05 14:43
Duplicate of #799

**Closed by midwan** 2021-09-05 14:43 UTC
Labels: duplicate, compatibility, fixed in dev
