### ISSUE TITLE
RiverRaidReloaded - Problems with 64-bit JIT

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#720] opened 2020-11-09 17:20 UTC
Raspberry Pi 4 with Manjaro Linux. Amiberry v3.3 (2020-09-17) 64 bit with AmigaOS 3.1.4.1.

While I don't have the problem with the 32-bit version of Amiberry v.3.3, with the 64-bit version I can start and play the game RiverRaidReloaded ... only the opponents are not visible, but the fuel tanks can. If I shoot, I hit them, then you can see the explosion effect. Although you can't see them, you can still collide with them. Otherwise the graphic is OK, you can see your own ship, but nothing of the objects on the water or what is flying. Strange...

Cheers
Retro1968

**Comment by midwan** [comment] 2020-11-09 18:20
I can see the problem, but only when starting it from WB.
If you use the ADF, it works fine in both A500 and A1200 configurations.

**Comment by Retro1968** [comment] 2020-11-09 18:37
OK thanks. But 6 billion people prefer to start it from the workbench. What is the fault?

**Comment by midwan** [comment] 2020-11-09 18:42
The problem is JIT (specifically, in the 64-bit implementation if it works for you on 32-bit).
Run it without JIT enabled, and it seems to work.

**Comment by Retro1968** [comment] 2020-11-09 19:05
OK. But I have JIT activated on 32-bit and 64-bit. Why does this cause problems under 64-bit? In the meantime, I'll use your workaround.

**Comment by midwan** [comment] 2020-11-09 19:21
The 64-bit JIT implementation is different than the 32-bit one, so it's a bug in 64-bit JIT essentially. ;)

**Comment by Retro1968** [comment] 2020-11-09 19:47
I see. Could it be a good idea to let the JIT programmer know? I think Santa himself likes to play RiverRaidReloaded too.

**Comment by Retro1968** [comment] 2020-11-23 09:22
Hello ... is anyone home?

**Comment by midwan** [comment] 2020-11-23 09:49
@Retro1968 
this has been reported to TomB since I mentioned it was a bug in JIT, as you can see above. For now, we have to wait for more news from his side...

**Comment by Retro1968** [comment] 2020-11-23 10:20
Oh man ... no, I had overlooked that. Thanks buddy.

**Comment by Retro1968** [comment] 2021-03-15 12:30
Update with Amiberry BETA (2021-03-15)

In between all objects can be seen; however often only faulty.

**Comment by midwan** [comment] 2021-03-16 17:39
fixed with 72a4ca553a2f3fb322308a7a79dd9007e96c2e6f

**Closed by midwan** 2021-03-16 17:39 UTC
Labels: bug, upstream bug
