### ISSUE TITLE
SDL1 2.12 menu key assign problem

### ISSUE THREAD

**Issue by pawelomega** [midwan/amiberry#226] opened 2018-02-05 08:50 UTC
Hello.

I'm not sure what's wrong with my Retropie or Amiberry SDL1(2.12).
I setup menu key to F10 and save config. Amiberry start with new config and my choice (F10) but still is F12 as quit to menu  Gui showing F10.

Thanks ;)

**Comment by midwan** [comment] 2018-02-08 08:28
This is a dupe of #229

**Closed by midwan** 2018-02-08 08:28 UTC
Labels: duplicate
