### ISSUE TITLE
Cannon Fodder: lower part of the screen isn't visible, and helicopter rotor is missing if JIT is on.

### ISSUE THREAD

**Issue by vanfanel** [midwan/amiberry#170] opened 2017-12-29 10:56 UTC
Hi,

I have noticed that Cannon Fodder is missing part of the screen: I am running on a native 50HZ mode (1280x720@50Hz) and emulating an OCS/ECS PAL Amiga.
Also, it seems to be missing part of the helicopter graphics before the game itself starts... but only with JIT ON! Strange...

**Comment by HoraceAndTheSpider** [comment] 2017-12-29 11:01
Sensible software are notorious for using overscan.

All sensi games should have a screen height of at least 262 pixels, which they were generally designed to, so check that is being used and then consider using vertical offset if need (shouldn’t be on a 720 display though)


As for JIT, this should only be used on 3D vector or FPS games, and should be removed for something like CF :)

**Comment by vanfanel** [comment] 2017-12-29 11:15
@HoraceAndTheSpider : Ok, I got the whole screen to show by increasing the HEIGHT in the Display menu options. Thanks about that!

But there's still something strange going on with CF: 
If I disable JIT, the helicopter tail is shown duting the intro to the first mission. 
However, after I pass the first mission... the helicopter tail is drawn in a crazy position! Almost out of the screen, on the lower part of the screen but moving with the helicopter. The rest of the helicopter is fine.

**Comment by vanfanel** [comment] 2017-12-29 11:24
@HoraceAndTheSpider : Ah, found a solution. Using the "MORE COMPATIBLE" CPU option makes it look fine. Seems to be related to CPU emulation, then.

**Comment by midwan** [comment] 2017-12-29 11:25
@vanfanel you might want to check @HoraceAndTheSpider's "UAE Config Maker" tool, it should make things easier... ;-)

Closing this issue then.

**Closed by midwan** 2017-12-29 11:25 UTC

**Comment by HoraceAndTheSpider** [comment] 2017-12-29 11:28
Funnily enough I was just about to look up the Config Maker settings for CF, and @vanfanel beat me to it :)

I am going to assume ADFs are being used here which I have not yet added support for (but should do in the future) on the Config Maker

**Comment by vanfanel** [comment] 2017-12-29 11:37
@HoraceAndTheSpider : No, I don't use ADFs but hand-made self-booting HDFs for transparent and fast-loading emulation

**Comment by HoraceAndTheSpider** [comment] 2017-12-29 11:44
OK. HDFs are supported by the Config Maker already , but lack some of the extra function you can get from files access (such as trainer/Whdload tooltype control) at the moment. 

I do plan to improved the HDF support further in the future if you ever wanted to provide some example files, but presently they should work already to some extent :)

**Comment by vanfanel** [comment] 2017-12-29 11:46
@HoraceAndTheSpider : I am slowly doing these HDFs, but I can pass them if you want so you can add them to your tool

**Comment by HoraceAndTheSpider** [comment] 2017-12-29 11:48
Can I ask why you prefer HDFs to the base files? I appreciate a handful of games need to be HDF for unpacking on the Amiga side (due to certain file names), but I find the files approach very convenient and still much faster than ADFs.

Please feel free to email me any via this username at hotmail dot com :)

**Comment by vanfanel** [comment] 2017-12-29 11:50
@HoraceAndTheSpider : Do you mean using directories (a directory for DH0: containig the game and a minimal system) instead of having them contained on an HDF?
Never tried that really!

**Comment by HoraceAndTheSpider** [comment] 2017-12-29 11:59
Yes , sort of :)

The default method for my Config Maker is a special “Whdload booter” for dh0: and the unpacked files for dh1: ... the config Maker matches the two together to create a .uae file which will boot the game. 

Check out the project and guide etc here, which may interest you:

http://ultimateamiga.co.uk/HostedProjects/RetroPieAmiga/

**Comment by vanfanel** [comment] 2017-12-29 12:12
@HoraceAndTheSpider : I will try it, looks like a great idea!
Are plain files instead of HDFs faster on loading files given the same emulated Amiga model??

**Comment by blinkydoos** [comment] 2017-12-29 12:31
HDF's and Directory mode load at the same speed, there's no difference except for HDF's being cleaner on the SD card. I have noticed that @HoraceAndTheSpider the booter does take quite a long time to boot compared to a different booter ?

Also, another thing that i've been meaning to mention @HoraceAndTheSpider . Why aren't you using 68000 for ECS games ? This corrects the speed to the same as the ADF versions. For example, in the current config of UAEConfigMaker, Barbarian (Palace) and Magic Pockets etc. still play too fast but if you set it to run at 68000 it plays at the exact same speed as the ADF version, no need for Cycle Exact ! Obviously a few will still need it but remember that WHDLoad can be run on a A600 which is 68000. So for ECS games you could use -

68000
Full ECS
3.1 A600 ROM.

**Comment by HoraceAndTheSpider** [comment] 2017-12-29 13:38
There can be little/no difference in speed of booter. Once set up it creates a script that immediately loads the slave file. There is no possible way it can be faster, other than the Amiga OS commands!

You cannot uae 68000 very well with whdload, therefore it is not used by default. Functions are limited because you cannot use certain commands (eg VBR move) I can include the option to specify for certain games. 

Keep in mind Whdload was designed for 68020+ so there needs to be an element of “responsibility” for the emulator to produce the correct speed, as these games run fine on real (enhanced) hardware.

**Comment by blinkydoos** [comment] 2017-12-29 13:49
As I said here https://github.com/HoraceAndTheSpider/UAEConfigMaker/issues/25#issuecomment-354448020 it was also designed for 68000.

**Comment by HoraceAndTheSpider** [comment] 2017-12-29 14:13
And reasoning behind that statement (which I stand by) posted in the same thread.

**Comment by blinkydoos** [comment] 2017-12-29 14:44
OK thanks for the info. I meant nothing by it, I just said that the requirements on the WHDLoad site is 68000 onwards. A lot of people still buy A600's from eBay specifically for WHDLoad. 

As I said, for games that run too fast like Barbarian & Magic Pockets it will match the original speed by using 68000. (Currently it's set at 68020 7Mhz which still plays too fast). I would love to have the option like you said or just set any games that run too fast as 68000. Do what you think is best. Thanks.
