### ISSUE TITLE
DietPi and RPI 3B+ throws Illegal Instruction

### ISSUE THREAD

**Issue by AdvancedFollower** [midwan/amiberry#304] opened 2018-04-15 13:52 UTC
2.19 is broken, getting "Illegal Instruction" when trying to run it on a Pi 3B+.

Also the pre-made image still doesn't boot properly on a B+.

**Comment by midwan** [comment] 2018-04-15 14:08
@AdvancedFollower 
Please provide detailed steps to recreate?

I've been testing v2.19 on a Pi 3B+ for quite some time now, haven't seen such a problem...

**Comment by AdvancedFollower** [comment] 2018-04-17 19:01
The image is this one:
http://dietpi.com/downloads/images/DietPi_RPi-ARMv6-Stretch_AmiBerry.7z
Linked at https://blitterstudio.com/amiberry/
When this is flashed, my Pi 3B+ just blinks the green LED repeatedly and doesn't boot. I write the image the same way as usual with Win32DiskImager.

I had previously installed Amiberry on the regular DietPi distro (http://dietpi.com/downloads/images/DietPi_RPi-ARMv6-Stretch.7z), using dietpi-software. I updated to Amiberry 2.19 by simply replacing all the files in the /mnt/dietpi_userdata/amiberry with the ones from the zip. I noticed Amiberry no longer started automatically after this (it was set to autostart in Dietpi-Config). If I try to start it manually from the console, i get this "Illegal instruction" message on the console, and nothing more happens.

**Comment by midwan** [comment] 2018-04-17 19:03
@AdvancedFollower 
DietPi has not yet included the latest version, this is an open issue here: https://github.com/Fourdee/DietPi/issues/1707

The image was prepared before this release, so it does not contain the latest version.

**Comment by Fourdee** [comment] 2018-04-18 02:06
http://dietpi.com/downloads/images/DietPi_RPi-ARMv6-Stretch_AmiBerry.7z Does not current contain the updated RPi 3B+ code. We'll get that image updated along with 2.19: https://github.com/Fourdee/DietPi/issues/1707

**Comment by midwan** [comment] 2018-04-19 12:35
@Fourdee Thanks for the assistance :)

**Comment by midwan** [comment] 2018-05-05 21:54
@AdvancedFollower 
This seems to be resolved in the latest updates of DietPi (not the pre-built image, at least not yet).
Could you please test and confirm if the issue is fixed for you?

**Comment by midwan** [comment] 2018-05-16 20:37
I'm assuming this is resolved now, so I'm closing this.
Let me know if there's still an issue with the latest version.

**Closed by midwan** 2018-05-16 20:37 UTC
