### ISSUE TITLE
How do you reset Custom controls to default?

### ISSUE THREAD

**Issue by vretro** [midwan/amiberry#254] opened 2018-02-13 21:37 UTC
Hi @midwan, thanks for all your work on Amiberry.

I have deleted all configs for Amiberry (that I know of), and installed fresh from source in RetroPie. 
Previously I have ran various versions of Amiberry and played around with custom controls.

I am now in a position where it appears as though I have set the following:
West = Joy1 Up
South = Joy1 Fire/Mouse1 Left

However, the above listed fields along with all others in Amiberry "Custom Controls" show "None".

I definitely would have created this custom control setup, but see no reference to it within Amiberry to be able to delete and start over.

My Input Device: USB,2-axis 8-button gamepad [R] Default

What directories do I need to delete to initiate a fresh install to remove the potential conflict from old configs?

**Comment by HoraceAndTheSpider** [comment] 2018-02-13 22:30
West as Up and South as Fire are the default for Joystick mode, and the correct behaviour for “none” in custom settings.


The custom maps are only set in the individual .uae so what you have done is correct :)

**Comment by vretro** [comment] 2018-02-15 00:04
Oh! I never knew about those defaults @HoraceAndTheSpider - silly me.

Thanks for pointing that out.

I don't seem to be able to assign up and fire to any other buttons though, and for them to work at all I must leave West and South set to None.

On a related note, I cant assign anything to L and R on my Input Device: USB,2-axis 8-button gamepad (SNES style iBuffalo pad)

**Comment by HoraceAndTheSpider** [comment] 2018-02-16 10:10
Do L + R show as greyed out in your custom tab?

Have you definatly assigned these to “shoulder” in retroarch, or as “trigger” 
(Trigger buttons are not currently supported)

If possible, perhaps you can post your controller  cfg file here and I can check to see there is any reason they won’t work.


I will have to look into the up/fire mapping separately, but make sure you are picking the right “port” for them to be mapped from (ie Joy 2 Up is the standard player 1 jump, not Joy 1 Up)

**Comment by vretro** [comment] 2018-02-17 16:39
Hi @HoraceAndTheSpider,

L + R show as None and are not Greyed out.

As far as I know, L + R are assigned to "shoulder" as I do not own controllers with triggers and there are no issues else where in Retroarch.

The correct port was chosen when assigning controls also.

Below is my controller cfg:

input_device = "USB,2-axis 8-button gamepad  "
input_driver = "udev"
input_l_btn = "4"
input_load_state_btn = "4"
input_start_btn = "7"
input_exit_emulator_btn = "7"
input_up_axis = "-1"
input_a_btn = "0"
input_b_btn = "1"
input_reset_btn = "1"
input_enable_hotkey_btn = "6"
input_down_axis = "+1"
input_r_btn = "5"
input_save_state_btn = "5"
input_right_axis = "+0"
input_state_slot_increase_axis = "+0"
input_x_btn = "2"
input_menu_toggle_btn = "2"
input_select_btn = "6"
input_y_btn = "3"
input_left_axis = "-0"
input_state_slot_decrease_axis = "-0"

**Comment by HoraceAndTheSpider** [comment] 2018-02-18 23:05
I cannot reproduce any problem with custom remapping Joy 2 Up and Joy 2 Fire to other buttons.

I have successfully managed this on all input ports. (Even where the default mapping is set to port 0)

What is this being tested on? I use a controller checking programme specifically for this.

**Comment by HoraceAndTheSpider** [comment] 2018-02-18 23:06
For the L/R problem  I will need to create a debugging binary for you to test some stuff for me

**Comment by vretro** [comment] 2018-02-20 23:16
Hi @HoraceAndTheSpider, I updated to v2.14 and the issue with L/R has been resolved. 

Additionally your hunch about port numbers was completely appropriate and resolved the other half of my issue and I am now able to assign the fire + up (jump) buttons as I please.

You were right, I mistook Joy1 as being Player 1, instead Joy2 was what I was after, emulating a mouse in port 1 and a joystick in port 2, which is true to original hardware, but perhaps less user intuitive and likely to trip more people up.

Thank you for looking into this issue and helping solve it.

**Comment by midwan** [comment] 2018-02-22 07:26
I believe we can close this then, otherwise let me know and we'll re-open it...

**Closed by midwan** 2018-02-22 07:26 UTC
Labels: question
