### ISSUE TITLE
Custom .whd load problem under Odroid XU4q TheRa 3.0.6

### ISSUE THREAD

**Issue by laszlovida** [midwan/amiberry#462] opened 2019-04-07 18:44 UTC
When creating a custom .whd file next to whdload_db.xml, Amiberry still uses hardware options from the xml database.
I'm using TheRa 3.06 with Amiberry 2.25 installed from source.

**I placed the custom .whd file at the following location:**
pigaming@odroid:/opt/retroarena/emulators/amiberry/whdboot/game-data$ ls -la
total 4096
drwxrwxr-x 2 pigaming pigaming    4096 Apr  7 20:36 .
drwxr-xr-x 4 pigaming pigaming    4096 Apr  7 17:41 ..
-rw-rw-r-- 1 pigaming pigaming      92 Apr  7 15:56 LethalWeapon_v1.3_0814.whd
-rw-rw-r-- 1 pigaming pigaming 4179303 Apr  7 19:31 whdload_db.xml

**The content of the .whd file:**
pigaming@odroid:/opt/retroarena/emulators/amiberry/whdboot/game-data$ cat LethalWeapon_v1.3_0814.whd
PRIMARY_CONTROL=JOYSTICK
PORT0=JOY
PORT1=JOY
JIT=FALSE
SCREEN_HEIGHT=216
SCREEN_Y_OFFSET=14

Amiberry log is the same no matter whether I try to use the custom .whd file or not. In both cases it indicates that it loaded hardware settings from the xml database.
**pigaming@odroid:/opt/retroarena/emulators/amiberry$ cat amiberry_log.txt**
AMIBERRY Logfile

Allocated 16 MB for 24-bit area (0x20000000) and 256 MB for Z3 and RTG at real address (0x60000000 - 0x70000020)
KS ver = 34 (0x22)
Stored port 0/0 d=0: added 200 0  
Stored port 0/0 d=0: added 200 0 Mouse MOUSE0
Port0: ID 'mouse' matched
Stored port 1/0 d=0: added 100 0  
Stored port 1/0 d=0: added 100 0 RetroArch Keyboard as Joystick [Input #1] JOY0
Port1: ID 'joy1' matched
Port2: NONE
Port3: NONE
target_cfgfile_load(): load file /opt/retroarena/emulators/amiberry/conf/uaeconfig.uae
load config '/opt/retroarena/emulators/amiberry/conf/uaeconfig.uae':3
cfgfile_load_2 failed
KS ver = 34 (0x22)
Stored port 0/0 d=0: added 200 0  
Stored port 0/0 d=0: added 200 0 Mouse MOUSE0
Port0: ID 'mouse' matched
Stored port 1/0 d=0: added 100 0  
Stored port 1/0 d=0: added 100 0 RetroArch Keyboard as Joystick [Input #1] JOY0
Port1: ID 'joy1' matched
Port2: NONE
Port3: NONE
failed to load config '/opt/retroarena/emulators/amiberry/conf/uaeconfig.uae'
KS ver = 34 (0x22)
Stored port 0/0 d=1: added 200 0 Mouse MOUSE0
Port0: COMBO 'Mouse' + 'MOUSE0' matched
Stored port 1/0 d=1: added 100 0 RetroArch Keyboard as Joystick [Input #1] JOY0
Port1: COMBO 'RetroArch Keyboard as Joystick [Input #1]' + 'JOY0' matched
Port2: NONE
Port3: NONE
WHDBooter LaunchedSymLink Kickstart ROMs for Booter
Making SymLink for Kickstart ROM: /opt/retroarena/emulators/amiberry/whdboot/save-data/Kickstarts/kick33180.A500
Making SymLink for Kickstart ROM: /opt/retroarena/emulators/amiberry/whdboot/save-data/Kickstarts/kick34005.A500
Making SymLink for Kickstart ROM: /opt/retroarena/emulators/amiberry/whdboot/save-data/Kickstarts/kick37175.A500
Making SymLink for Kickstart ROM: /opt/retroarena/emulators/amiberry/whdboot/save-data/Kickstarts/kick39106.A1200
Making SymLink for Kickstart ROM: /opt/retroarena/emulators/amiberry/whdboot/save-data/Kickstarts/kick40063.A600
Making SymLink for Kickstart ROM: /opt/retroarena/emulators/amiberry/whdboot/save-data/Kickstarts/kick40068.A1200
Making SymLink for Kickstart ROM: /opt/retroarena/emulators/amiberry/whdboot/save-data/Kickstarts/kick40068.A4000
WHDBooter - Host: A600 ROM Available 
WHDBooter - Looking for /opt/retroarena/emulators/amiberry/whdboot/save-data/Autoboots/LethalWeapon_v1.3_0814.auto-startup 
WHDBooter -  Loading hostprefs.conf.
WHDBooter - Loading whdload_db.xml
WHDBooter - Searching whdload_db.xml for LethalWeapon_v1.3_0814
WHDBooter - Game H/W Settings: 

		PRIMARY_CONTROL=JOYSTICK
		PORT0=JOY
		PORT1=JOY
		JIT=FALSE
		SCREEN_HEIGHT=216
		SCREEN_Y_OFFSET=24
		
		
WHDBooter - Default Slave: LethalWeapon.Slave
WHDBooter - SubPath:  LethalWeapon
WHDBooter - Libraries:  LethalWeapon
WHDBooter - Created Startup-Sequence  

 
IF NOT EXISTS WHDLoad
DH3:C/Assign C: DH3:C/ ADD
ENDIF
CD "Games:LethalWeapon"
WHDLoad SLAVE="games:LethalWeapon/LethalWeapon.Slave" PRELOAD NOWRITECACHE NOREQ SPLASHDELAY=0 SAVEPATH=Saves:Savegames/ SAVEDIR="LethalWeapon"

WHDBooter - Saved Auto-Startup to /opt/retroarena/emulators/amiberry/whdboot/save-data/Autoboots/LethalWeapon_v1.3_0814.auto-startup
WHDBooter - Found Auto-Startup to SymLink
WHDBooter - Game: Port 0     : JOY  
WHDBooter - Game: Port 1     : JOY  
WHDBooter - Game: Control    : JOYSTICK  
WHDBooter - Game: Fast Copper: nul  
WHDBooter - Game: CPU        : nul  
WHDBooter - Game: Blitter    : nul  
WHDBooter - Game: CPU Clock  : nul  
WHDBooter - Game: Chipset    : nul  
WHDBooter - Game: JIT        : FALSE  
WHDBooter - Game: CPU Compat : nul  
WHDBooter - Game: Scr Height : 216  
WHDBooter - Game: Scr YOffset: 24  
WHDBooter - Game: NTSC       : nul  
WHDBooter - Game: Fast Ram   : nul  
WHDBooter - Game: Z3 Ram     : nul  
WHDBooter - Host: Controller 1   : joy1  
WHDBooter - Host: Controller 2   : joy2  
WHDBooter - Host: Controller 3   : joy0  
WHDBooter - Host: Controller 4   : nul  
WHDBooter - Host: Mouse 1        : joy1  
WHDBooter - Host: Mouse 2        : joy2  
WHDBooter - Host: Sound On       : nul  
WHDBooter - Host: Sound Mode     : nul  
WHDBooter - Host: Stereo Split   : 1  
WHDBooter - Host: Fixed Height    : nul  
WHDBooter Option (Joystick Control): joyport0
WHDBooter Option (Joystick Control): joyport1
Unknown value ('nul') for option 'collision_level'.
0: 640x400, 8-bit (50,60)
1: 640x400, 16-bit (50,60)
2: 640x400, 32-bit (50,60)
3: 640x480, 8-bit (50,60)
4: 640x480, 16-bit (50,60)
5: 640x480, 32-bit (50,60)
6: 720x400, 8-bit (50,60)
7: 720x400, 16-bit (50,60)
8: 720x400, 32-bit (50,60)
9: 800x480, 8-bit (50,60)
10: 800x480, 16-bit (50,60)
11: 800x480, 32-bit (50,60)
12: 800x600, 8-bit (50,60)
13: 800x600, 16-bit (50,60)
14: 800x600, 32-bit (50,60)
15: 960x540, 8-bit (50,60)
16: 960x540, 16-bit (50,60)
17: 960x540, 32-bit (50,60)
18: 1024x768, 8-bit (50,60)
19: 1024x768, 16-bit (50,60)
20: 1024x768, 32-bit (50,60)
21: 1280x720, 8-bit (50,60)
22: 1280x720, 16-bit (50,60)
23: 1280x720, 32-bit (50,60)
24: 1280x800, 8-bit (50,60)
25: 1280x800, 16-bit (50,60)
26: 1280x800, 32-bit (50,60)
27: 1280x1024, 8-bit (50,60)
28: 1280x1024, 16-bit (50,60)
29: 1280x1024, 32-bit (50,60)
30: 1360x768, 8-bit (50,60)
31: 1360x768, 16-bit (50,60)
32: 1360x768, 32-bit (50,60)
33: 1366x768, 8-bit (50,60)
34: 1366x768, 16-bit (50,60)
35: 1366x768, 32-bit (50,60)
36: 1680x1050, 8-bit (50,60)
37: 1680x1050, 16-bit (50,60)
38: 1680x1050, 32-bit (50,60)
39: 1920x1080, 8-bit (50,60)
40: 1920x1080, 16-bit (50,60)
41: 1920x1080, 32-bit (50,60)
Autoconfig board list:
Card 01: '<no name>' no autoconfig 00da0000 - 00daffff.
Card 02: '<no name>' no autoconfig 00600000 - 00a7ffff.
Card 03: 'UAE Boot ROM' no autoconfig 00f00000 - 00f0ffff.
Card 04: 'Z2 Fast RAM'
  e7.51.00.00.07.db.00.00.00.01.00.00.00.00.00.00
  MID 2011 (07db) PID 81 (51) SER 00000001
  Z2 0x00200000 0x00200000 4096K RAM 0
Card 05: 'UAE FS ROM'
  d1.52.40.00.07.db.00.00.00.03.20.00.00.00.00.00
  MID 2011 (07db) PID 82 (52) SER 00000003
  Z2 0x00e90000 0x00e90000   64K ROM 0
END
KS ver = 39 (0x27)
Stored port 0/1 d=0: added 100 3  
Stored port 0/1 d=0: added 100 3 RetroArch Keyboard as Joystick [Input #1] JOY0
Port0: ID 'joy2' matched
Stored port 1/1 d=0: added 101 3  
Stored port 1/1 d=0: added 101 3 Pro Controller JOY1
Port1: ID 'joy1' matched
Stored port 2/0 d=0: added 100 0  
Stored port 2/0 d=0: added 100 0 RetroArch Keyboard as Joystick [Input #1] JOY0
Port2: ID 'joy0' matched
Port3: NONE
Stored port 0/1 d=0: added 200 0 Mouse MOUSE0
Stored port 1/1 d=0: added 101 3 Pro Controller JOY1
Stored port 2/0 d=0: added 100 0 RetroArch Keyboard as Joystick [Input #1] JOY0
RTAREA located at 00F00000
mapped_malloc(): 0x00f00000 - 0x00f10000 (0x20f00000 - 0x20f10000) -> UAE Boot ROM (rtarea)
mapped_malloc(): 0x00200000 - 0x00600000 (0x20200000 - 0x20600000) -> Fast memory (*)
mapped_malloc(): 0x00f80000 - 0x01000000 (0x20f80000 - 0x21000000) -> Kickstart ROM (kick)
mapped_malloc(): 0x00000000 - 0x00200000 (0x20000000 - 0x20200000) -> Chip memory (chip)
ROM loader.. (<none>)
Known ROM 'KS ROM v3.0 (A1200)' loaded
ROM loader end
memory init end
No disk in drive 0.
JIT: &countdown =  0x46f3a78
JIT: &build_comp = 0x3d1af1
CPU=68020, FPU=0, JIT=0. 24-bit
Stored port 0/1 d=0: added 200 0 Mouse MOUSE0
Stored port 1/1 d=0: added 101 3 Pro Controller JOY1
Stored port 2/0 d=0: added 100 0 RetroArch Keyboard as Joystick [Input #1] JOY0
JIT: &countdown =  0x46f3a78
JIT: &build_comp = 0x3d1af1
CPU=68020, FPU=0, JIT=0. 24-bit
memory init end
Reset at 00000000. Chipset mask = 00000003
Autoconfig board list:
Card 01: '<no name>' no autoconfig 00da0000 - 00daffff.
Card 02: '<no name>' no autoconfig 00600000 - 00a7ffff.
Card 03: 'UAE Boot ROM' no autoconfig 00f00000 - 00f0ffff.
Card 04: 'Z2 Fast RAM'
  e7.51.00.00.07.db.00.00.00.01.00.00.00.00.00.00
  MID 2011 (07db) PID 81 (51) SER 00000001
  Z2 0x00200000 0x00200000 4096K RAM 0
Card 05: 'UAE FS ROM'
  d1.52.40.00.07.db.00.00.00.03.20.00.00.00.00.00
  MID 2011 (07db) PID 82 (52) SER 00000003
  Z2 0x00e90000 0x00e90000   64K ROM 0
END
Card 0: skipping autoconfig (not autoconfig)
Card 2: skipping autoconfig (not autoconfig)
hardreset, memory cleared
Card 4: Z2 0x00200000 4096K RAM Fast memory
mapped_malloc(): 0x00e90000 - 0x00ea0000 (0x20e90000 - 0x20ea0000) -> Filesystem autoconfig (*)
Card 5: Z2 0x00e90000   64K ROM Filesystem autoconfig
filesystem: diagentry 00200098 configdev 00000c40
Mounting uaehf.device:0 0 (0):
FS: mounted virtual unit DH0 (/tmp/)
Mounting uaehf.device:0 1 (0):
FS: mounted virtual unit DH3 (/opt/retroarena/emulators/amiberry/whdboot/boot-data.zip)
Mounting uaehf.device:0 2 (0):
FS: mounted virtual unit DH1 (/home/pigaming/RetroArena/roms/amiga/LethalWeapon_v1.3_0814.lha)
Mounting uaehf.device:0 3 (0):
FS: mounted virtual unit DH2 (/opt/retroarena/emulators/amiberry/whdboot/save-data/)
FS: DH0 (flags=00000000,E=0,ED=1,EF=0,native='/tmp/') starting..
FS: Games (flags=00000004,E=0,ED=0,EF=1,native='/home/pigaming/RetroArena/roms/amiga/LethalWeapon_v1.3_0814.lha') starting..
FS: Saves (flags=00000000,E=0,ED=1,EF=0,native='/opt/retroarena/emulators/amiberry/whdboot/save-data/') starting..
FS: DH3 (flags=00000004,E=0,ED=0,EF=1,native='/opt/retroarena/emulators/amiberry/whdboot/boot-data.zip') starting..
Unknown mousehack hook 208
Unknown mousehack hook 209
Unknown mousehack hook 202
Unknown mousehack hook 203
Unknown mousehack hook 202
Unknown mousehack hook 202
Unknown mousehack hook 202
hdf_close_target
hdf_close_target
hdf_close_target
hdf_close_target
hdf_close_target
hdf_close_target
hdf_close_target

Thank you for your help in advance!

Best regards,
Laszlo

**Comment by midwan** [comment] 2019-04-08 10:46
@laszlovida 
`.whd` files are considered obsolete with the later versions of Amiberry.
The ideal approach would be to not use anything special at all (Amiberry will attempt to pick the title from the XML database, if it finds a match), or if you need to change some settings for all games you can do so in the `hostprefs.conf` file instead.

Alternatively, you can still use `.uae` config files per title if you wish.

**Comment by laszlovida** [comment] 2019-04-08 13:15
Thank you for your quick reply!
Is it possible to update the WHDLoad Auto booting Wiki that .whd files are not used anymore?

Actually, I tried using .uae configs to customize the screen and my controller settings. This way, unfortunately, in case of some titles my controller is not detected when next time I load them. It's very strange, because I saved the .uae config in the Amiberry emulator window. Is it possible that not all settings provided in the xml database are written into the .uae file?

I thought trying .whd files worth a chance.
Anyway, I found it working as an alternative to modify the whdload_db.xml manually, but this is not the best solution.

**Comment by midwan** [comment] 2019-04-08 13:19
@laszlovida 
Yeap, we'll update the Wiki accordingly.
For controller settings, you could use the `hostprefs.conf` file instead, as that's the kind of thing it was designed for.

Modifying the `whdload_db.xml` is doable also, but not recommended - as it's normally updated with new stuff every few days for improved compatibility, and you can download the latest version from within Amiberry itself (go to Paths, click on Download XML).

**Comment by HoraceAndTheSpider** [comment] 2019-04-08 17:21
yes, please let us know what chages you are manually changing, as if it is one of compatibility, i will fix the master XML file

**Comment by laszlovida** [comment] 2019-04-08 18:06
Here is what I changed, I marked the difference with bold.
First, I updated the screen Y offset, so the upper part of the screen can be visible.
Secondly, I like using the same button for jumping in all games, so I made an alternate mapping for up button.
I'd really appreciate it, if you could add these to the master XML.

        <game filename="LethalWeapon_v1.3_0814"  sha1="9ea0b5a24acb06ae71e063b33ecb5077fbc771dc">
                <name>Lethal Weapon</name>
                <subpath>LethalWeapon</subpath>
                <variant_uuid>2ffe4cf2-113e-51fa-881d-718ba766665a</variant_uuid>
                <slave_count>1</slave_count>
                <slave_default>LethalWeapon.Slave</slave_default>
                <slave_libraries>False</slave_libraries>
                <slave number="1">
                        <filename>LethalWeapon.Slave</filename>
                        <datapath></datapath>
                </slave>
                <hardware>
                PRIMARY_CONTROL=JOYSTICK
                PORT0=JOY
                PORT1=JOY
                JIT=FALSE
                SCREEN_HEIGHT=216
                SCREEN_Y_OFFSET=**14**

                </hardware>
                **<custom_controls>
                    joyport1_amiberry_custom_none_east=Joy2 Up
                </custom_controls>**
        </game>

**Comment by laszlovida** [comment] 2019-04-12 21:42
I did some testing.
I launched a game then changed some display properties and customized a control button in Amiberry emulator screen. Finally, I saved the configuration in .uae format.
When next time I boot the game, my controller is not recognized, I see the following in the log:

Stored port 0/1 d=0: added 200 0 Mouse MOUSE0
Port0: COMBO 'Mouse' + 'MOUSE0' matched
Stored port 2/0 d=0: added 100 0 RetroArch Keyboard as Joystick [Input #1] JOY0
Port2: COMBO 'RetroArch Keyboard as Joystick [Input #1]' + 'JOY0' matched
**Unplugged stored, port 1 'Pro Controller' (JOY1)**
Stored port 1/1 d=0: added -2 0 Pro Controller JOY1
Port3: NONE

I did the same on my Raspberry Pi 2 with Retropie and I did not experience the above problem.
Do you have any idea what can cause this with theRA release on Odroid?

Thank you in advance!

**Comment by mrfomt** [comment] 2019-05-01 09:12
@laszlovida
I must ask, because you are using odroid xu4. Are you using scanlines? In some screen height I got weird scanlines, like white shadows horizontal on the screen, its most visable in brighter areas, it appears when I have screen height to 256 or 262. 200, 240 and 270 looks good.
LED tv 1080p display

**Comment by HoraceAndTheSpider** [comment] 2019-06-09 12:25
I have added `joyport1_amiberry_custom_none_east=Joy2 Up` and `SCREEN_Y_OFFSET=14` so these shoudl be picked up on the next XML update

**Comment by midwan** [comment] 2019-08-31 21:12
I believe we can close this then.

**Closed by midwan** 2019-08-31 21:12 UTC
Labels: question
