### ISSUE TITLE
Fast-Forward option

### ISSUE THREAD

**Issue by solskogen** [midwan/amiberry#36] opened 2017-01-07 12:19 UTC
Just like WinUAE and FS-UAE have.

**Comment by midwan** [comment] 2017-03-02 11:33
@solskogen 
This will come as part of the WinUAE 2.8.1 merge, sometime later.

**Comment by midwan** [comment] 2019-08-31 21:32
Isn't this a duplicate of https://github.com/midwan/amiberry/issues/501 ?

**Closed** 2019-08-31 21:32 UTC
Labels: enhancement
