### ISSUE TITLE
problem with saving my configuration to *** .uae

### ISSUE THREAD

**Issue by pawelomega** [midwan/amiberry#84] opened 2017-04-16 21:22 UTC
Hey M8. I found some bugs in saving configuration to new configuration ex MyA500.uae. Im trying to setup leds numlock for power and scroll lock for DF0 next im setting filter LINEAR(smooth) and MENU BUTTON for xbox 360 pad as JoyButton1 then saving my config. Exiting and re-run amiberry-sdl2 then loading my saving config and in miscellaneous my setting for numlock and scrolllock are back to default = none, filter setting to default (auto) and Menu Button = ---------. .

**Comment by windale** [comment] 2017-04-16 22:12
This is a dupe of https://github.com/midwan/amiberry/issues/63

**Comment by midwan** [comment] 2017-04-17 19:26
@pawelomega 
Known issue, as mentioned above by @windale 
Tracked in #63

**Closed by midwan** 2017-04-17 19:26 UTC
