### ISSUE TITLE
Cd rom drive mount?

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#125] opened 2017-09-15 04:03 UTC
Hi.

Is the cd mount for Amiberry only available for cd32 only? I have a hdf + cd image. After creating a 1200 quickstart. Workbench starts the hdf is obviously detected but i dont see anything mounted in cd drive even although i mount the amiga cd image.
The cd drive tab in gui shows nothing even after i re mount the cd image and reset Amiberry?

Game is T-zer0 AMIGACD + HDF found here.
http://eab.abime.net/showthread.php?t=86983

Winuae plays it. Amiberry only plays the HDF therefore lacking the cd audio from the cd image.

**Comment by blinkydoos** [comment] 2017-09-15 09:15
Currently, it's only for CD32. It's also been asked here (Issue https://github.com/midwan/amiberry/issues/37)

**Comment by ransom1122** [comment] 2017-09-15 09:34
Is it on the todo list at all?

**Comment by blinkydoos** [comment] 2017-09-15 10:12
No idea, sorry. If you ask TomB on the Pandora forums i'm sure he'll add it.

**Comment by HoraceAndTheSpider** [comment] 2017-09-15 10:51
It's probably not that hard to add, I think there is a check prior to mounting that the system is in CD32 "mode"

I can have a look at removing that check and see if that works

**Comment by ransom1122** [comment] 2017-09-15 11:02
That would be good.  A small little unlock like that can open a big door with Amiberry. Thanks

**Comment by midwan** [comment] 2017-11-24 11:25
Closing this since it's a dupe of #37

**Closed by midwan** 2017-11-24 11:25 UTC
