### ISSUE TITLE
No scanlines when a game has its own UAE file

### ISSUE THREAD

**Issue by mrfomt** [midwan/amiberry#482] opened 2019-05-26 19:45 UTC
If I make my own changes in Amiberry and save an UAE file for a specific game, everything saves, but not scanlines. The scanlines is not saved, the UAE file has this in it:
gfx_linemode=scanlines
But makes no differents. Scanlines is on by default in amiberry.conf. I get scanlines in games that has no UAE files.
Tried every screen mode to see if its something to do with that, but it doesnt.

**Comment by HoraceAndTheSpider** [comment] 2019-06-09 11:12
I might need to defer to @midwan on this, but i have check `cfgfile.cpp` for the scanline option and it is in there for both reading and writing.

the syntax also appears correcy with the available options being:

```
static const TCHAR* linemode[] = {
	_T("none"),
	_T("double"), _T("scanlines"), _T("scanlines2p"), _T("scanlines3p"),
	_T("double2"), _T("scanlines2"), _T("scanlines2p2"), _T("scanlines2p3"),
	_T("double3"), _T("scanlines3"), _T("scanlines3p2"), _T("scanlines3p3"),
	nullptr
};
```


Can you confirm you are using Amiberry v2.25 ?

**Comment by HoraceAndTheSpider** [comment] 2019-06-09 12:11
Looks like this is a duplicate of the issue here: https://github.com/midwan/amiberry/issues/466

i will close this thread and ask that comments be kept under the single issue until resolved.

**Closed by HoraceAndTheSpider** 2019-06-09 12:11 UTC
