### ISSUE TITLE
[dev] USB Megadrive Adapter

### ISSUE THREAD

**Issue by FabrizioRadica** [midwan/amiberry#702] opened 2020-10-19 13:14 UTC
Hi, 
I've a problem with Mayflash Megadrive Usb Adapter (i whould like to connect a real amiga joystick). because i've some problem with keyrah and I bought a new usb adapter.
So, Amiberry Control Panel it show me the name of controller but doesn't works.

https://ibb.co/hC9py2b
https://ibb.co/zJyGfmV

Amiberry 3.4b (latest release)

any solution?
Regards,

**Comment by midwan** [comment] 2020-10-19 14:09
It looks like the name of the controller is not fetched correctly in the Input panel.
It's still there, but with an empty name (twice, probably one per connector).

Can you still select it, even though it has an empty name? Does it work if you do that?

**Comment by midwan** [comment] 2020-10-19 17:08
This area is still under development in the `dev` branch, so it's possible there are bugs that I haven't found yet. ;)
Please try the following:
- enable logging (Paths panel)
- Quit Amiberry
- Restart emulator, so we can capture the log events
- Quit it again

Then check the created logfile and search for entries beginning with:
`Controller Detection for Device:`

It should have such a line for each controller detected in the system. Even if the name is blank, the line should appear with an empty text next to it.

Or even better, upload the logifle here so we can take a look.

**Comment by FabrizioRadica** [comment] 2020-10-19 20:11
> 
> 
> This area is still under development in the `dev` branch, so it's possible there are bugs that I haven't found yet. ;)
> Please try the following:
> 
>     * enable logging (Paths panel)
> 
>     * Quit Amiberry
> 
>     * Restart emulator, so we can capture the log events
> 
>     * Quit it again
> 
> 
> Then check the created logfile and search for entries beginning with:
> `Controller Detection for Device:`
> 
> It should have such a line for each controller detected in the system. Even if the name is blank, the line should appear with an empty text next to it.
> 
> Or even better, upload the logifle here so we can take a look.

Hi :)
here the LOG.
Hope to help you :)
[amiberry.log](https://github.com/midwan/amiberry/files/5404423/amiberry.log)

**Comment by midwan** [comment] 2020-10-19 20:21
Thanks for the logfile. It doesn't seem to contain that string at all, which means that either this wasn't detected as a controller at all, or the event wasn't triggered.

Could you try once more please, but click on the Rescan button in Paths first, before closing down the emulator. That should rescan all joysticks as well, and we'll see if it shows up there.

**Comment by FabrizioRadica** [comment] 2020-10-19 20:38
> 
> 
> Thanks for the logfile. It doesn't seem to contain that string at all, which means that either this wasn't detected as a controller at all, or the event wasn't triggered.
> 
> Could you try once more please, but click on the Rescan button in Paths first, before closing down the emulator. That should rescan all joysticks as well, and we'll see if it shows up there.

mmh.. it save the same log maybe...
[amiberry.log](https://github.com/midwan/amiberry/files/5404540/amiberry.log)

**Comment by vretro** [comment] 2020-10-19 21:48
I use the same adaptor with Amiberry and am able to control both players, with an Atari compatible Amiga joystick attached. Just sharing to rule out any kind of hardware incompatibility.

Using Amiberry 3.3, installed via RetroPie:

**Port 0 =** I selected the second instance of “Mayflash Ltd Mayflash MD USB Adaptor” from the list. Because the ports on this particular adaptor are mapped the wrong way around.

Then make sure Joystick 1 is in the left hand side port (furthest from the adaptor usb cable).

**Port 1 =** Then selected the first instance from the list.
Player 2 should then be the right hand port, closest to the adaptor usb cable.

**Input Device:** this is mapped to the Retroarch controller in my instance, with an [R] to indicate this - rather than the [N] as seen in your screenshot @FabrizioRadica

**Comment by FabrizioRadica** [comment] 2020-10-19 22:49
> 
> 
> I use the same adaptor with Amiberry and am able to control both players, with an Atari compatible Amiga joystick attached. Just sharing to rule out any kind of hardware incompatibility.
> 
> Using Amiberry 3.3, installed via RetroPie:
> 
> Both adaptor ports appear as identically named devices within the Port 0/1/2/3 drop down lists. The names are not hidden in my instance.
> 
> **Port 0 =** I selected the second instance of “Mayflash Ltd Mayflash MD USB Adaptor” from the list. Because the ports on this particular adaptor are mapped the wrong way around.
> 
> Then make sure Joystick 1 is in the left hand side port (furthest from the adaptor usb cable).
> 
> **Port 1 =** Then selected the first instance from the list.
> Player 2 should then be the right hand port, closest to the adaptor usb cable.
> 
> **Input Device:** this is mapped to the Retroarch controller in my instance, with an [R] to indicate this - rather than the [N] as seen in your screenshot @FabrizioRadica

Hi vretro :)
i've this version of Mayflash USB Adapter.
http://www.mayflash.com/Products/NINTENDOWiiU/MF104.html
but I think it's the same in the end...

**Comment by vretro** [comment] 2020-10-19 22:55
Hi @FabrizioRadica 
I didn’t know Mayflash made another Sega Mega Drive adaptor!

This is the older one I have, it doesn’t feature the additional buttons for Turbo or the Home button for Switch:
http://www.mayflash.com/Products/PCUSB/PC054.html

**Comment by midwan** [comment] 2020-10-20 07:41
This is most likely an issue only in the `dev` beta version - @FabrizioRadica have you tested the latest stable release instead? I'm guessing it works properly there.

Still, I would like to fix it in `dev` as well, as that will eventually become the next stable release when ready.

**Comment by ninjaweb62** [comment] 2020-10-20 07:46
I've got exactly the same problem as the @FabrizioRadica one in dev beta version. I'm trying with an USB Joystick (TheC64-Joystick).
Results: in 'Input' panel there is a blank (invisible) name,  in 'Custom control' panel then input device name is visible (The C64 Joystick), but the joystick is not working at all.
Here's my log:
[amiberry.log](https://github.com/midwan/amiberry/files/5407071/amiberry.log)

**Comment by ninjaweb62** [comment] 2020-10-20 07:46
I'll try asap with master branch.

**Comment by FabrizioRadica** [comment] 2020-10-20 07:52
> 
> 
> This is most likely an issue only in the `dev` beta version - @FabrizioRadica have you tested the latest stable release instead? I'm guessing it works properly there.
> 
> Still, I would like to fix it in `dev` as well, as that will eventually become the next stable release when ready.

yes, I can test it on 3.3 :)

cul8er...

**Comment by ninjaweb62** [comment] 2020-10-20 08:03
I can confirm that for me the problem is present only with the dev branch.

**Comment by FabrizioRadica** [comment] 2020-10-20 08:07
> 
> 
> I can confirm that for me the problem is present only with the dev branch.

Thank's / Grazie Riccardo :)

**Comment by FabrizioRadica** [comment] 2020-10-20 08:34
> 
> 
> I can confirm that for me the problem is present only with the dev branch.

Ok works but not fine.
with the Amiga Joystick, it recognize only LEFT and LEFT/UP movement.
with Megadrive joypad works only but without fire.

@ninjaweb62 have you the same problems?

**Comment by ninjaweb62** [comment] 2020-10-20 08:51
> > I can confirm that for me the problem is present only with the dev branch.
> 
> Ok works but not fine.
> with the Amiga Joystick, it recognize only LEFT and LEFT/UP movement.
> with Megadrive joypad works but without fire.
> 
> @ninjaweb62 have you the same problems?

No, sorry, it looks like my joystick is working fine.

**Comment by FabrizioRadica** [comment] 2020-10-20 09:28
> 
> 
> > > I can confirm that for me the problem is present only with the dev branch.
> > 
> > 
> > Ok works but not fine.
> > with the Amiga Joystick, it recognize only LEFT and LEFT/UP movement.
> > with Megadrive joypad works but without fire.
> > @ninjaweb62 have you the same problems?
> 
> No, sorry, it looks like my joystick is working fine.

ok.. this (last) problem seems to be with my version of MayFlash Adapter model MF104 ... 
I've sent an email to the customer care.

**Comment by midwan** [comment] 2020-10-20 15:30
@FabrizioRadica 
When you tested the `dev` version, did you also have the `gamecontrollerdb.txt` file in the <binary location>/conf/ directory?
From what I can see, it probably didn't recognize your controller as part of the supported controller devices, so it skipped the part about opening it and getting the name, mappings etc.

There is an external file that I have included in the conf/ directory, that includes a big list of extra controllers supported by the community. It's a normal text file that can be edited by users, to add their own devices as well (if they don't exist). There are even some tools to help you create a new mapping in the file, such as this: https://generalarcade.com/gamepadtool/

So the question is, did you have the file included in your test (so that Amiberry can look for it and load it), or not?
If not, can you try the following 2 things please:
- Add the file and run the same test as before.
- If the above still fails (blank controller in the list, nothing new indicated in the logfile), then try using the tool I linked above to create a new mapping for your controller, in the `gamecontrollerdb.txt` file. Then test again, with that updated file.

**Comment by FabrizioRadica** [comment] 2020-10-21 12:17
> 
> 
> @FabrizioRadica
> When you tested the `dev` version, did you also have the `gamecontrollerdb.txt` file in the /conf/ directory?
> From what I can see, it probably didn't recognize your controller as part of the supported controller devices, so it skipped the part about opening it and getting the name, mappings etc.
> 
> There is an external file that I have included in the conf/ directory, that includes a big list of extra controllers supported by the community. It's a normal text file that can be edited by users, to add their own devices as well (if they don't exist). There are even some tools to help you create a new mapping in the file, such as this: https://generalarcade.com/gamepadtool/
> 
> So the question is, did you have the file included in your test (so that Amiberry can look for it and load it), or not?
> If not, can you try the following 2 things please:
> 
>     * Add the file and run the same test as before.
> 
>     * If the above still fails (blank controller in the list, nothing new indicated in the logfile), then try using the tool I linked above to create a new mapping for your controller, in the `gamecontrollerdb.txt` file. Then test again, with that updated file.

I wrote to customer support. the protocol for atari joysticks is simply not supported (as in  @ninjaweb62 's model).

At this point, there remains only the problem of the device not displayed in the list in dev branch (3.4b).
the same also happens with a Hori Fighting Stick

**Comment by midwan** [comment] 2020-10-21 17:30
@FabrizioRadica 
The "blank controller" problem has a solution however, try the steps I mentioned above. ;)

**Comment by midwan** [comment] 2020-11-07 18:23
@FabrizioRadica 
Did you get a chance to test with the tool I mentioned above, perhaps?

**Comment by ninjaweb62** [comment] 2020-11-12 10:14
@midwan
Anyway there's still the problem with the blank line in the Input panel (at list with my "TheC64-Joystick") in the dev version.

**Comment by midwan** [comment] 2020-11-12 10:57
@ninjaweb62 
Yes, that would happen if the controller is not in the list of "known" controllers with a mapping. The tool I mentioned allows you to create a mapping for such cases, which can be added to the list (gamecontrollerdb.txt) afterwards. Once you do that, it should show the name of the controller properly.

Of course, this area is still "work-in-progress" and not final yet.

**Comment by ninjaweb62** [comment] 2020-11-12 20:05
@midwan 
Sorry for my lack of knowledge, but then I can't understand why it works flawlessly with amiberry master without any mapping.

**Comment by midwan** [comment] 2020-11-12 20:31
@ninjaweb62 
I rewrote the game controller handling in `dev` (not entirely finished yet), to use SDL2's `GameController` features, instead of directly polling for joysticks. 

The benefits have to do with improved mapping by default:
With the older approach, you could never be sure which physical controller button maps to which number (e.g. 1st button, 2nd, 3rd and many more if you have an XBox or PS type of controller), as that can be different per controller. Some had HATs, some had analog sticks as well. The new approach uses SDL2's mapping features, to simplify this greatly.

But this only works if the controller is recognized. If it's not, then it's relatively easy to add a controller and mapping in the list, and that's a one-time task only. That's what the tool I mentioned above is about, but of course it can also be done manually (the db file is just plain text, one could edit it and add a new line).

But like I said, this is not finalized yet, and I might make more changes and improvements to it. That's why it's still in beta. ;)

**Comment by ninjaweb62** [comment] 2020-11-12 21:02
@midwan
thank you very much for this exhaustive explanation!

**Comment by midwan** [comment] 2020-12-28 17:03
Support for this is now finished in `dev`, and tested with various controllers (including some that had no mapping, so we added one in the `gamecontrollerdb.txt` file and tested that it worked).

**Closed** 2021-04-01 07:27 UTC
Labels: fixed in dev, question
