### ISSUE TITLE
Black screen in version 4.1

### ISSUE THREAD

**Issue by marcomto** [midwan/amiberry#789] opened 2021-04-03 10:51 UTC
I compiled Amiberry with dispmanx support as always. However when I launch my configuration (previously working) I get a black screen. If I press the F12 key I can only see the mouse pointer.
I tried to compile without dispmanx, sdl2 only, and the configuration starts but I get weird colors on screen (the red component seems to be missing in Workbench).  

To Reproduce
compiled as always: make -j2 PLATFORM=rpi3 (on raspberry pi3+)
made rescan of the paths
loaded my previously saved configuration
pressed the start button
black screen appears and stays forever (I can close the emulator by clicking on the lower part of the screen, where the quit button is supposed to be)

- OS: Raspberry Pi Lite (Latest version)

**Comment by midwan** [comment] 2021-04-03 18:07
Please try recreating your config file.
There have been several changes that could affect this, at least one known one is the 32-bit RTG pixel format which changed (to match that of WinUAE). The incorrect colors is a result of that.
To resolve that, you need to use the new RTG Board panel in the GUI, select the Pixel format for 16/32 bit modes (use those with the asterisk next to them!) and save the configuration.
When you boot into Workbench, your previous screenmode will be invalid (since you just changed it's format), so you'll need to open up "Screenmode" prefs and select the new 32-bit one.

16-bit modes are not affected, this change only happened for 32-bit ones.

Regarding the black screen... Not sure, but recreating the config might solve that as well. It could be some (now) invalid value somewhere. Lots of options were cleaned up and while before they didn't do anything, now they have a function as expected. 

Unfortunately this was unavoidable in the process of bringing Amiberry closer to WinUAE standards, but hopefully this kind of thing will be minimized from now on.

**Comment by marcomto** [comment] 2021-04-08 07:32
So far I've tried the following with no success:
- pulled the entire project into a new folder (no old configuration files)
- created new configurations with and without RTG board enabled
 I still get a black screen.

Tried the binary versions:
- with Dispmanx I get the same behavior, black screen.
- without Dispmanx the gui crashes when I load a new configuration, even before clicking on the start button.

At the moment I have a separate folder with tag 3.3 sources. Compiled with Dispmanx. It works perfectly.

**Comment by fluxabit** [comment] 2021-04-09 14:18
I can confirm the exact same behavior as described by @marcomto on my pi3 B+ running Raspbian 10 without Desktop. Amiberry 3.3 works flawless.

Also, I tested with just Kickstart ROM and no boot media, which should rule out any connection to the selected ScreenMode within AmigaOS (which would only be relevant when booting DOS media anyway).

**Comment by midwan** [comment] 2021-04-09 14:39
Unfortunately I still can't recreate this, I must be missing something I guess.
Let's start with the basics - forget your existing configs, and try from Quickstart, with just a kickstart ROM and a classic configuration (e.g. A1200 Kickstart 3.0/3.1).
@fluxabit mentioned that even that scenario fails, which is weird.

Just a thought: have you tried clearing out the `conf/amiberry.conf` file? There's a default one provided in the repo, you could use that. Or just delete it/rename it, it will be regenerated on-demand. Then do a Rescan Paths to pick up the ROMs again.

Also, what gfx driver are you using in the system? If you're using the Dispmanx version, you cannot use the Full KMS driver. Only Legacy and FKMS will work with that.

**Comment by fluxabit** [comment] 2021-04-09 20:40
I compiled some early 4.x RC when no binary was available for the pi3 and since tried the binary release. Both from within confined directories with no previous config files, so basically clean setup apart from copying Kick ROM files. Compile went fine. Unsure if I did a rescan - is that necessary when I select the ROM via absolut path?

hmm, wondering now, I use AmigaForever ROMs with rom.key...

All show the same black screen issue as described. All running on Raspbian lite with no Desktop.

I'm lost at that gfx driver question. I used dmx version for compile and binary as it is recommended. Legacy and FKMS? I only know OCS, ECS, AGA and CyberGraphX. :)

**Comment by midwan** [comment] 2021-04-09 21:08
The gfx driver I'm referring to is what is being used by Linux.
You can change it using `raspi-config` and the value gets saved in the `/boot/config.txt` file.
If you're not sure, you could attach your complete `config.txt` file here as well.

**Comment by fluxabit** [comment] 2021-04-09 21:20
The uncommented lines in /boot/config.txt are:

```
hdmi_force_hotplug=1
hdmi_group=2
hdmi_mode=35
dtparam=audio=on
[pi4]
dtoverlay=vc4-fkms-v3d
max_framebuffers=2
```

pi4? Whatever, all default with Raspbian install..

**Comment by midwan** [comment] 2021-04-10 18:56
try adding the following at the end of the file:
```
[all]
dtoverlay=vc4-fkms-v3d
```
And see if that changes anything?

**Comment by midwan** [comment] 2021-04-11 13:02
I've only been able to see a black screen problem under a certain combination, so far:
- Manjaro OS, using latest SDL2 from their repositories, running from console (so that it will use KMSDRM).

Under the desktop, there's no problem. When using Dispmanx, there's also no problem. And it does the same with v3.3 also, not just the newer versions.

This leads me to suspect something wrong with the version of SDL2 I'm testing, and specifically in their KMSDRM implementation. Since there's been a lot of activity in SDL2's repo regarding KMSDRM updates and bug fixes recently, it could be some bug that (hopefully?) got fixed afterwards. Testing with the latest SDL2 version from source might help here.

**Comment by solskogen** [comment] 2021-04-11 14:34
You can try with this (KMSDRM) if you're on Manjaro or Arch: https://aur.archlinux.org/packages/sdl2-nox-git/

**Comment by fluxabit** [comment] 2021-04-16 18:06
Reinstalled from scratch, Raspberry Pi OS lite, updated, installed requirements per readme and binary v4.1.2 - same black screen issue on start and after using F12 to return to GUI.

Also:
```
[all]
dtoverlay=vc4-fkms-v3d

```
results in immediate crash (not even the GUI starts):
`Unable to create window: Could not initialize OpenGL / GLES library`

You labeled this issue as "upstream bug", does this mean you found the issue in one of the required packages?

Massive thank you for your work!

**Comment by midwan** [comment] 2021-04-16 18:18
@fluxabit 
There's a known bug in SDL2's KMSDRM back-end, which seems to be fixed in their latest versions from git. That's why I flagged this as an upstream bug.

Try installing the latest SDL2 from git and see if that fixes the problem for you?

**Comment by marcomto** [comment] 2021-04-17 11:12
I compiled from source and installed the latest SDL2 version (2.0.14) then recompiled Amiberry from source. Still no luck
While compiling I got two issues: SDL_ttf.h and SDL_image.h were not found in the path, so I manually created two symlinks like that:
sudo ln -s /usr/include/SDL2/SDL_ttf.h /usr/local/include/SDL2/
sudo ln -s /usr/include/SDL2/SDL_image.h /usr/local/include/SDL2/
The compilation went fine, but I still get the black screen when I press the start button (after loading the configuration, a new one, by the way).

![IMG_20210417_123714](https://user-images.githubusercontent.com/59309883/115111006-70acca80-9f7e-11eb-9ea6-ac5e0e2220b9.jpg)

**Comment by midwan** [comment] 2021-04-17 21:42
@marcomto 
I believe that SDL2 v2.0.14 has the problems with KMSDRM, please try the latest one from git where the issue seems to be fixed?

**Comment by midwan** [comment] 2021-05-29 16:51
I discovered a bug that was only occurring on RPI3 (not RPI4) and possibly other older platforms. Not sure why that was the case, considering it worked on RPI4, but in any case... :)
The fix is deployed in `master` and `dev` now.

**Closed by midwan** 2021-05-29 16:51 UTC
Labels: question, upstream bug

**Comment by marcomto** [comment] 2021-05-31 12:55
I confirm this fix works for me.

**Comment by midwan** [comment] 2021-05-31 13:14
@marcomto thanks for confirming!

**Comment by fluxabit** [comment] 2021-05-31 13:19
Thank you for your great work and for letting us know! My fix was buying an RPI400 but I’ll try on RPI3+ later.
