### ISSUE TITLE
Exception “Level 3 Autovector (COPPER/VBLANK/BLITTER)” on majority of games

### ISSUE THREAD

**Issue by stuffu** [midwan/amiberry#785] opened 2021-04-01 22:37 UTC
Hi

Thanks for your hard work with bringing 4.0 to a final version. Eagerly jumped on the new build but unfortunately bumped into problems.

First of all, the old config from 3.3(?) didn’t seem compatible with 4.0. I haven’t checked thoroughly but the default display setting was set to max width and min height. When launching the new build.

anyway, removed the package along with all configs, rebuilt from source, rescanned paths etc and the issue was gone.

Now I bumped into the real issue. Most games launched returns:

```
Exception “Level 3 Autovector (COPPER/VBLANK/BLITTER)” ($6C) at $5F1FCA (Resload $AD2) occurred.
WHDLoad failed returncode 103
```

Tested a lot of games and so far and from what I found, AGA games launches fine, everything else return with the above error.

Running Amiberry 4.0 final, built from source on Retropie 4.7.11 using a RPI 4.

happy to provide more info if needed!

**Comment by midwan** [comment] 2021-04-02 09:20
Confirmed, this only seems to happen when using the whdbooter with non-AGA games.
I'll check the history of commits to isolate when this started happening, it might be related to some recent merges from WinUAE.

**Comment by midwan** [comment] 2021-04-02 10:30
The issue starts appearing after commit 4069d4a918f599179a6e67f9cdc63b34d13e2edb which added 68000 cycle-exact emulation. Before this commit, it doesn't occur.

I did a test with Blood Money, which showed the problem. Interestingly, if I change only one thing, it works normally again:
- Set CPU speed to 14MHz instead of 7MHz

Maybe it's related to the more accurate cycle emulation, but it seems that emulating an 68020 at 7MHz causes the problem. Need more tests to make sure that just making this change is enough, but if that's the case it can be fixed in the XML and no code changes are required.

@HoraceAndTheSpider Ping, need some help testing more titles with this scenario, and if validated we'll need to update all relevant entries in the XML

**Comment by midwan** [comment] 2021-04-02 10:48
I think this fixes the problem, at least for the (few) titles I tested here.
Need more testing to be sure that is the case, and also to be certain this change doesn't cause any other problems elsewhere (probably not).

Once we have tested more and have a more concrete result, I can merge this back to master and bump the version to v4.1 quite quickly.

**Comment by stuffu** [comment] 2021-04-02 11:03
Thanks for looking into it so quickly. I’m really looking forward for the new release!

**Comment by midwan** [comment] 2021-04-02 15:01
@stuffu 
If you have some time to test, the version in the `dev` branch should work as expected. It does in my tests so far, but the more people testing it the better, of course.

You'll need to compile it from source manually, as RetroPie's scripts will only compile the version in the `master` branch - and there's a known problem with that one with v4.0, anyway (see related issue here: https://github.com/midwan/amiberry/issues/784).

The easiest way to do that, would be to drop out in a shell (or do this over SSH) and use the following commands:
```
git clone https://github.com/midwan/amiberry -b dev amiberry-dev
cd amiberry-dev
make -j4 PLATFORM=rpi4
```
That will compile it for the RPI4/Dispmanx, which is what you want for RetroPie. After it's finished, you can just copy over the binary to the right location:
```
sudo cp amiberry /opt/retropie/emulators/amiberry/
```
then just exit the shell so you can go back to EmulationStation, and test Amiberry again.

**Comment by myzar** [comment] 2021-04-02 18:35
@midwan dev works for me no more errors in the ocs/ecs whdboot games

**Comment by midwan** [comment] 2021-04-02 18:38
@myzar
Thanks for confirming!

**Closed** 2021-04-02 18:41 UTC
Labels: bug, fixed in dev

**Comment by AnalogHero** [comment] 2021-04-02 20:11
Tested this, didnt work for me. Compiled latest dev branch as described still gives me the Level 3 autovector WHDLoad error.

**Comment by stuffu** [comment] 2021-04-02 21:35
I’ve tested 4.1, master branch, built from source. Issue is fixed for me.

**Comment by AnalogHero** [comment] 2021-04-03 07:21
Will try again from the master branch. Compiled it from dev branch.

**Comment by AnalogHero** [comment] 2021-04-03 08:49
Tested again with version 4.1. Still getting the error. When i select 14mhz CPU speed it works fine, but not with 7mhz.

**Comment by midwan** [comment] 2021-04-03 18:15
@AnalogHero 
Are you getting 7Mhz when launching a non-AGA game with v4.1?

**Comment by AnalogHero** [comment] 2021-04-03 19:06
Yes. Maybe its because for some whdloadgames i have an associated .uae file (sometimes i adjusted screen dimensions).

**Comment by midwan** [comment] 2021-04-03 19:43
If you have your own configs they will always override what the emulator tries to set, so you will either have to update them, or remove them to test

**Comment by AnalogHero** [comment] 2021-04-04 07:46
Tested and works ok if you dont override to 7mhz with .uae config. If you select 7mhz and reboot, you get the error again though.
