### ISSUE TITLE
Amiberry v2 cd mount fixed?

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#227] opened 2018-02-05 09:26 UTC
Has mounting a cd image been fixed in Amiberry v2? 

I am trying TZer0 Gamr HDF combined with mounting a bin/cue cd image. Ive ticked tge cd drive opened the cue. But the game will not recognize the cd for producing the cd audio ingame. There is nothing wrong with the game as it works in winuae perfectly.

**Comment by midwan** [comment] 2018-02-05 21:32
I believe this is a dupe of #37, so closing this one and we can move the discussion there...

**Closed by midwan** 2018-02-05 21:32 UTC
Labels: duplicate
