### ISSUE TITLE
Black screen when trying to start games

### ISSUE THREAD

**Issue by simon-videoloft** [midwan/amiberry#665] opened 2020-07-18 16:22 UTC
Running RetroPie 4.6.4 and Amiberry v3.2 beta on a 3B+ Pi. Have tried a binary and source install of Amiberry with the same results for both.

RetroPie was manually installed on top of Raspbian. Everything appears to work fine with other emulators but can't seem to get Amiberry working.

Pretty sure the Kickstart ROMs are all correctly in place and the symlinks set up.

When trying to run a game I just get a black screen with the mouse pointer showing.

Checking the logs, one of two things seems to be reported. Either:

'Could not load system ROM, trying system ROM replacement'

Or an error ('segmentation fault').

This is my first time trying to run Amiberry so may be missing something obvious but think I've covered all the set up steps correctly.

**Comment by midwan** [comment] 2020-07-26 21:14
This seems like a duplicate of #671 (regarding the black screen).
Regarding the kickstart ROM message, that would indicate that you're trying to reference a file that doesn't exist, or you didn't do a Rescan ROMs first. Let's keep the issues separate however, so we can track them easier.

**Closed by midwan** 2020-07-26 21:14 UTC
Labels: duplicate
