### ISSUE TITLE
Possible to add more RTG Memory?

### ISSUE THREAD

**Issue by CypherXG** [midwan/amiberry#265] opened 2018-02-22 16:48 UTC
My Question is:
Is it possible to add more RTG Memory than 16MB?

I'll tried this in my own Versions before and it work perfectly with max 128 MB RTG Memory.
In the actually Version of Amiberry it will not start with a Videomem greater than 16MB.
But when i start with another Config, load than the 128MB Config, the Emulator will reset perfectly with 128MB and these are shown in the System like Sysinfo etc.
The Config is correct and the Memory is the same that i saved with Amiberry.
Can you modify Amiberry to add max Memory for RTG?
This would be nice.

**Comment by midwan** [comment] 2018-02-22 16:53
@CypherXG 
Is the only modification you made in the config file?
If so, could you please attach such a config file for reference?

I will try adding more from the GUI, if it doesn't cause any problems we can keep it.

**Comment by CypherXG** [comment] 2018-02-22 17:03
In the Config there is the Row with
gfxcard_size=128
gfxcard_type=ZorroIII

Next modification was that i added in PanelRam.cpp some rows like the RTGMEM etc:

`static const char* RTGFastMem_list[] = { "Deaktiviert", "1.0 MB RTG VRam", "2.0 MB RTG VRam", "4.0 MB RTG VRam", "8.0 MB RTG VRam", "16 MB RTG VRam", "32 MB RTG VRam", "64 MB RTG VRam", "128 MB RTG VRam" };
static unsigned int RTGFastMem_values[] = { 0x000000, 0x100000, 0x200000, 0x400000, 0x800000, 0x1000000, 0x2000000, 0x4000000, 0x8000000 };`

`sldGfxmem = new gcn::Slider(0, 8);`

`	for (i = 0; i < 9; ++i)
	{
		if (changed_prefs.rtgboards[0].rtgmem_size == RTGFastMem_values[i])
		{
			sldGfxmem->setValue(i);
			lblGfxsize->setCaption(RTGFastMem_list[i]);
			break;
		}
	}
	sldGfxmem->setEnabled(!changed_prefs.address_space_24);`

to get the 128MB Slider.

In Main.cpp i modified these rows:
	for (auto & rtgboard : p->rtgboards) { //0x8000000 für 128MB
		const auto rbc = &rtgboard;
		if (rbc->rtgmem_size > 0x2000000 && rbc->rtgmem_type == GFXBOARD_UAE_Z3) {
			error_log(_T("Graphics card memory size %d (0x%x) larger than maximum reserved %d (0x%x)."), rbc->rtgmem_size, rbc->rtgmem_size, 0x2000000, 0x2000000);
			rbc->rtgmem_size = 0x8000000;
			err = 1;
		}

I changed the rtgmem_size to 0x8000000
That was all. It works with the older Versions of Amiberry. It work with the new one too but it won't start with an 128mb config.

**Comment by CypherXG** [comment] 2018-02-22 17:11
![dsc_0200](https://user-images.githubusercontent.com/7895130/36553037-9e0b75b6-17fb-11e8-87da-6222a40da360.JPG)
![dsc_0201](https://user-images.githubusercontent.com/7895130/36553047-a14aa300-17fb-11e8-970e-aebd1417068b.JPG)
![dsc_0202](https://user-images.githubusercontent.com/7895130/36553054-a67e10be-17fb-11e8-99fa-e41d6ff6c9f0.JPG)
![dsc_0203](https://user-images.githubusercontent.com/7895130/36553057-a7901ff6-17fb-11e8-8282-ede8c98529bf.JPG)
Here you see the 128 MB are working, but the Emulator wont start with a config greater than 16MB

**Comment by midwan** [comment] 2018-02-22 18:14
@CypherXG 
Thanks for the details.

Why do you need 128MB of RTG Memory anyway? What scenario are you using that requires that amount?

**Comment by CypherXG** [comment] 2018-02-22 18:37
Videoplaying and Videoediting.
A Simple Videplayer need with Workbench in a goog Resolution more than 75% RTG Mem.
For Videoediting i need more Memory because Chipmem is not used and to slow.

**Comment by midwan** [comment] 2018-02-25 13:53
Fixed in the `dev` branch

**Comment by CypherXG** [comment] 2018-02-25 16:49
Doesn't work.
Same as mine.
If i try to load a 128MB config Amiberry doesn't start.

**Comment by CypherXG** [comment] 2018-02-25 17:10
Sry, doesn't work.
If i save a config with 128 MB RTG Mem i can not start Amiberry with that config.
It only works if i start Amiberry with another config, load the 128mb RTG config in the config panel and make a reset. Then the 128MB would be allocated for the RTG.

**Comment by midwan** [comment] 2018-02-25 18:52
Hmm, I didn't try saving a config so it's possible that I missed something there.
I tested it by loading a config I had, changing the RAM options to give 128MB RTG to it, then start it. It worked that way at least.

**Comment by midwan** [comment] 2018-03-03 12:59
@CypherXG 
This works for me...

- I opened a config I had for testing, assigned 128MB RTG RAM to it, and saved it with a new name.
- I started the emulator with that config -> WORKS

- I started the emulator from the command prompt, passing a parameter to that config, like so:
`amiberry -conf conf/a4000-128.uae` -> WORKS

(The config was set to Hide the GUI, so it booted directly).

Could you please try recreating a config from scratch, in case the problem is in that?

**Comment by CypherXG** [comment] 2018-03-03 14:45
` 
config_description=test
config_hardware=true
config_host=true
config_version=3.6.0
-use_gui=no
kickstart_rom_file_id=FC24AE0D,KS ROM v3.1 (A500,A600,A2000)
pandora.rom_path=/opt/retropie/emulators/uae4arm/kickstarts/
pandora.floppy_path=/opt/retropie/emulators/uae4arm/disks/
pandora.hardfile_path=/opt/retropie/emulators/uae4arm/
pandora.cd_path=/opt/retropie/emulators/uae4arm/cd32/
pandora.cpu_speed=0
pandora.hide_idle_led=0
pandora.tap_delay=10
pandora.custom_controls=1
pandora.custom_up=0
pandora.custom_down=0
pandora.custom_left=0
pandora.custom_right=0
pandora.custom_a=32
pandora.custom_b=32
pandora.custom_x=-3
pandora.custom_y=-3
pandora.custom_l=0
pandora.custom_r=0
pandora.move_x=0
pandora.move_y=0
synchronize_clock=true
key_for_menu=292
key_for_quit=0
button_for_menu=-1
button_for_quit=-1
gfx_correct_aspect=0
gfx_fullscreen_ratio=100
kbd_led_num=0
kbd_led_scr=-1
kbd_led_cap=-1
amiberry.rom_path=/opt/retropie/emulators/uae4arm/kickstarts/
amiberry.floppy_path=/opt/retropie/emulators/uae4arm/disks/
amiberry.hardfile_path=/opt/retropie/emulators/uae4arm/
amiberry.cd_path=/opt/retropie/emulators/uae4arm/cd32/
; 
; *** Controller/Input Configuration
; 
joyport0=mouse
joyport0_autofire=none
joyport0_friendlyname=Mouse
joyport0_name=MOUSE0
; 
joyport1=joy0
joyport1_autofire=none
joyport1_mode=djoy
joyport1_friendlyname=RetroArch Keyboard as Joystick [Input #1]
joyport1_name=JOY0
; 
; 
; 
input.joymouse_speed_analog=30
input.joymouse_speed_digital=10
input.joymouse_deadzone=33
input.joystick_deadzone=33
input.analog_joystick_multiplier=15
input.analog_joystick_offset=-1
input.mouse_speed=100
input.autofire_speed=0
kbd_lang=us
; 
; *** Host-Specific
; 
amiberry.vertical_offset=0
amiberry.hide_idle_led=0
amiberry.gfx_correct_aspect=0
amiberry.kbd_led_num=-1
amiberry.kbd_led_scr=-1
amiberry.scaling_method=-1
amiberry.use_analogue_remap=false
amiberry.use_retroarch_quit=true
amiberry.use_retroarch_menu=true
amiberry.use_retroarch_reset=false
; 
; *** Common / Paths
; 
use_gui=no
show_leds=true
kickstart_rom_file=/home/pi/RetroPie/BIOS/Amiga/Amiga Kickstart Roms/Amiga Kickstart 3.1 (40.063) (A600) (Commodore) (1993).rom
kickstart_rom_file_id=FC24AE0D,Amiga Kickstart ROM v3.1 (A500,A600,A2000)
kickstart_ext_rom_file=
ide_mb_rom_file=:ENABLED
flash_file=
cart_file=
; 
; *** Floppy Drives
; 
floppy0=
floppy1=
floppy2=
floppy2type=0
floppy3=
floppy3type=0
cdimage0=/home/pi/RetroPie/roms/amiga/HDF/AmigaSYS 4 AGA Amiga 1200-4000 for Advanced users ISO Image.iso,disabled
nr_floppies=4
floppy_speed=800
; 
; *** Hard Drives
; 
; 
; *** CD / CD32
; 
cd_speed=100
; 
; *** Display / Screen Setup
; 
gfx_framerate=0
gfx_width=768
gfx_height=262
gfx_refreshrate=50
gfx_refreshrate_rtg=50
gfx_lores=false
gfx_resolution=hires
gfx_linemode=none
gfx_fullscreen_amiga=false
gfx_fullscreen_picasso=false
ntsc=false
; 
; *** CPU options
; 
cpu_speed=max
cpu_type=68040
cpu_model=68040
fpu_model=68040
cpu_compatible=false
cpu_24bit_addressing=false
fpu_strict=false
compfpu=true
cachesize=8192
; 
; *** Memory
; 
chipmem_size=16
z3mapping=real
fastmem_size=0
a3000mem_size=0
mbresmem_size=0
z3mem_size=128
z3mem_start=0x40000000
bogomem_size=0
gfxcard_size=128
gfxcard_type=ZorroIII
rtg_modes=0x502
; 
; *** Chipset
; 
chipset=aga
chipset_refreshrate=50.000000
collision_level=full
chipset_compatible=Generic
fatgary=0
ramsey=15
immediate_blits=false
waiting_blits=automatic
fast_copper=false
; 
; *** Sound Options
; 
sound_output=normal
sound_channels=stereo
sound_stereo_separation=7
sound_stereo_mixing_delay=0
sound_frequency=44100
sound_interpol=none
sound_filter=off
sound_filter_type=standard
sound_volume_cd=20
; 
; *** Misc. Options
; 
bsdsocket_emu=true

`

That is a config from me that doesnt startup with 128MB

**Comment by midwan** [comment] 2018-03-03 16:06
@CypherXG 
It's certainly an older config, all those pandora* options are obsolete.
Please try to recreate it starting with a Quickstart option, then test with that. I suspect it will work as expected then.

**Comment by CypherXG** [comment] 2018-03-03 17:22
So. i tried with a Quickstart config.
Blanc A4000 Config and saved directly.
Tried 128MB RTG and saved it. Loads perfectly.
Tried 128MB RTG and 128 MB Z3 Fast...Crash
Tried 128MB RTG and 64 MB Z3 Fast...Crash
Tried 128MB RTG and 32 MB Z3 Fast...Crash
Tried 128MB RTG and 16 MB Z3 Fast...WORKS !!
So.
[a4000-configs.zip](https://github.com/midwan/amiberry/files/1777700/a4000-configs.zip)

Here i add for you my configs
a4000-1.uae = 128MB RTG and 16 MB Z3 Fast...WORKS
a4000-2.uae = 128MB RTG and 32 MB Z3 Fast...Crash
a4000-3.uae = 128MB RTG and 128 MB Z3 Fast...Crash

It looks like that amiberry couldn't allocate enough ram or somthing else.
When my Pi boots up i have over 650 MB free for Programs.

**Comment by midwan** [comment] 2018-03-03 17:37
@CypherXG 
Are you booting into a desktop, or just the console?
If there's not enough RAM on the Pi to allocate what you asked for, you might run into trouble.
It does work for me, with allocating 128MB Z3 RAM, 128MB RTG RAM, 2MB Chip, but I boot into the console directly and run the emulator from there (no desktop in the background).

Also, how much RAM have you allocated to the GPU in the Pi settings?

**Comment by CypherXG** [comment] 2018-03-03 17:44
Always console.
Give the GPU 256MB Mem

**Comment by midwan** [comment] 2018-03-03 17:57
@CypherXG 
I just tested your configs:
- a4000-3.uae: I noticed that the ROM assigned was a 1.3 one, so I changed it to a 3.1. You also have 8MB Motherboard RAM, which is not needed, but I left it there. Clicking on Start did work however, no crash.

I tried setting a config from scratch:
- Start with Quickstart, A4000 040 config.
- RAM Panel, set 128MB Z3 RAM, 128MB RTG RAM, remove Motherboard RAM.
- Click Start and it works

I also tried the above with 64MB Z3 RAM just in case, it still works here.

However, setting Z3 RAM to 32MB (while keeping the rest the same) caused a crash for some reason.

Note: I'm using the current `dev` branch for these tests.

**Comment by CypherXG** [comment] 2018-03-03 18:32
I use the dev also.
I tried your seetings.
When i press start it works.
When i save the config and i want to start from console with loading the config without GUI it crashed.
The Kickstart 1.3 is also a bug. I select a 3.1 Kickstart but in the config it would be regonized as a 1.3 Kickstart. 
Also happend when i quickstart a cd32.
In the Kickstart Panel it shows both cd32 roms. Kick + ext. thats ok.
When i save the config File it shows me 
kickstart_rom_File_id=FC24AE0D, KS ROM v3.1 (A500,1000,2000)
some rows down it shows me the Kickstart rom id 1E63D4A5,CD32 KS ROM v3.1
kickstart_rom_File_id is a double here in config.
I dont know from where Amiberry is taking the first ID info. 
[cd32x.zip](https://github.com/midwan/amiberry/files/1777759/cd32x.zip)

**Comment by midwan** [comment] 2018-03-03 19:27
Your `a4000-3.uae` config still contains obsolete entries, so it wasn't a "clean" config to begin with.
If you create a proper one by starting from the Quickstart panel, then save that as a new config, it should work correctly regarding ROMs.

Also, I noticed that your paths point to `/opt/retropie/emulators/uae4arm/` which would also mean that the `adfdir.conf` file is picked up from there. Old configs from `uae4arm` are different from Amiberry's, so it's recommended to keep them separate (or recreate them in Amiberry) to avoid such issues.

**Comment by CypherXG** [comment] 2018-03-03 19:46
This is correct. But the a4000 Config Files where created by the Quickstart Option with amiberry and directly saved.

**Comment by CypherXG** [comment] 2018-03-04 08:57
So i try it now. 
Raspi Mem 64MB
Clean Amiberry dir (All files i move in an empty Retropie/uae4arm dir)
Start Emu, rescan roms, make a Quickstart option with A4000, set config, removed Mainboard Mem, add 128 Z3 Mem, add 128RTG Mem, add 8MB Chipmem.
Save as default uaeconfig.
Start with command line...crash
Start normal and make a double click on config....crash
Start normal and load it from config Panel, click reset....crash
[Config+adfdir.zip](https://github.com/midwan/amiberry/files/1778312/Config.adfdir.zip)

**Comment by midwan** [comment] 2018-03-04 09:45
@CypherXG 
Testing it on RetroPie, I got the crash.

I used the same ROMs as before, just located in the RetroPie paths, recreated the config from scratch and tried to load it: **crash**
If I just started the emulator after modifying a config from Quickstart, it worked.

Weird, as the same exact steps do not crash on Raspbian Stretch, only on RetroPie (Jessie).
I wonder what is causing this...

**Comment by CypherXG** [comment] 2018-03-04 10:07
:-)

**Comment by midwan** [comment] 2018-03-04 10:17
@CypherXG 
It seems that it's not RetroPie, but rather the SDL1 version that crashes.
The SDL2 version does not crash with the same config file...

**Comment by CypherXG** [comment] 2018-03-19 15:58
Mhhhh
I found a little mini Solution for me.
If i gray out from row 75 to 81 it is possible to start Amiberry with saved 32MB RTG MEM Config.
So i think it's only an Memory allocate Problem. 

`void alloc_AmigaMem(void)
{
	int i;
	uae_u64 total;
	int max_allowed_mman;

	free_AmigaMem();
	set_expamem_z3_hack_mode(Z3MAPPING_AUTO);

	// First attempt: allocate 16 MB for all memory in 24-bit area 
	// and additional mem for Z3 and RTG at correct offset
	natmem_size = 16 * 1024 * 1024;
//#ifdef AMIBERRY
	// address returned by valloc() too high for later mmap() calls. Use mmap() also for first area.
//	regs.natmem_offset = (uae_u8*)mmap(reinterpret_cast<void *>(0x20000000), natmem_size + BARRIER,
//	                                   PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS | MAP_FIXED, -1, 0);
//#else
	regs.natmem_offset = (uae_u8*)valloc(natmem_size + BARRIER);
//#endif`

**Comment by midwan** [comment] 2018-03-20 08:35
@CypherXG 
It seems that it's indeed related to memory allocation, but I couldn't yet find out why it would crash on SDL1 but not on SDL2, for the 128MB setting. And again, only if you load the config, applying it from the GUI still allowed it to work, even on SDL1.

And on top of all that, the "32MB" setting seems to crash in both SDL1 and SDL2, even though 64MB and 128MB work fine on SDL2.

**Comment by midwan** [comment] 2018-04-02 09:49
@CypherXG 
Found some things that were probably causing this, with the help of TomB.
Expect a new update in the `dev` branch soon :)

**Closed** 2018-04-02 09:54 UTC
Labels: enhancement, question

**Comment by CypherXG** [comment] 2018-04-03 18:32
So. i found the Problem.
You must change the ADDITIONAL_MEMSIZE from 128 to 256MB in Row 25 ([Old Version](https://github.com/midwan/amiberry/commit/8cc02590cf3d787370e0d9356211c18630713883))
`#define ADDITIONAL_MEMSIZE ((256 + 16) * 1024 * 1024)`
Then you can save and load a config with 128MB RTG Memory with the SDL1 Version.
Works now fine :-)

**Comment by midwan** [comment] 2018-04-03 19:37
@CypherXG Hm, or maybe `#define ADDITIONAL_MEMSIZE (((MAX_RTG_MEM*2) + 16) * 1024 * 1024)` ?
