### ISSUE TITLE
Feature request: support HDF files larger than 1GB

### ISSUE THREAD

**Issue by c0d3h4x0r** [midwan/amiberry#373] opened 2018-10-26 04:15 UTC
### Expected behavior
The 8GB secondary HDF file I use to hold my entire collection of WHDLoad games/demos + other HD-based games should work on Amiberry.

### Actual behavior
I can configure Amiberry to use the HDF, but Amiberry just mysteriously doesn't use it.  Not even an error/warning message telling me that it won't be used or why.  It's a very confusing and frustrating user experience.

### Steps to reproduce the behavior
Using WinUAE, create an 8GB HDF file as a seconary hard drive (DH1), format it, and copy a bunch of shit onto it.  Then, copy the HDF file to a USB stick and transfer it to the Raspberry Pi 3B+ running Amiberry (in my case, included with Amibian).  Configure Amiberry to use the HDF as a secondary drive (DH1), then click "Start", let Workbench (on DH0) boot, and then notice that DH1 is simply not present as expected.

**Comment by midwan** [comment] 2018-10-26 10:54
Thanks for the report, this is actually a duplicate of #20 - so let's keep that one open and close this.

**Closed by midwan** 2018-10-26 10:54 UTC
Labels: duplicate

**Comment by c0d3h4x0r** [comment] 2018-10-26 18:17
Sounds good, thanks!
