### ISSUE TITLE
XBOX 360 configuration not working when....

### ISSUE THREAD

**Issue by pawelomega** [midwan/amiberry#52] opened 2017-02-23 16:34 UTC
When we exclude PAD XBOX 360 when Amiberry work and re-run again then configuration file in Amiberry is not working. All assign keys (entry GUI or QUIT) not working. We should get out of AMIBERRY and re-run again Amiberry then the PAD is on and all work like before.

**Comment by midwan** [comment] 2017-02-23 22:11
@pawelomega 
Could you please describe each step taken, so I can recreate the problem here?
How did you "exclude" the XBOX 360 pad exactly?

**Comment by pawelomega** [comment] 2017-02-24 07:21
Hello. My conclusion is when Amiberry start with working XBOX 360 PAD, everything work perfectly but when we not used PAD for w some time it automatically power off (or we power off manually) and when we power on it again then PAD doesn't work. Just i tested that situation a few minuts ago. Thanks

**Comment by windale** [comment] 2017-02-24 11:48
The same/similar thing happens with Wireless PS3 controllers (maybe all wireless controllers). If the pad powers off from inactivity, the only way to get it working again is to exit the emulator and start it again to re-detect the pad.

**Comment by HoraceAndTheSpider** [comment] 2017-02-24 14:10
Possibly we can fix this by forcing pad initialisation routines to re-run when a new device is detected.

**Comment by midwan** [comment] 2017-02-24 14:14
Indeed, this may be simple enough to fix. 
I'll take a look this weekend.

**Comment by midwan** [comment] 2019-09-14 15:58
Duplicate of #193

**Closed by midwan** 2019-09-14 15:58 UTC
Labels: enhancement
