### ISSUE TITLE
Screen Positioning Wrong

### ISSUE THREAD

**Issue by Dwarfboysim** [midwan/amiberry#565] opened 2019-12-25 23:30 UTC
Hi all,
Long time owner and love the Amiga. Amiberry with WHDLoad has been working great on my Pi till recently after updating. Now ALL games appear horizontal correct but vertically too far down cutting off the bottom 1/4 of the Amiga screen. Is there an over arching config to correct the vertical position and save it for all ?

Was advised to apply these settings to a .UAE file for the game:

gfx_center_horizontal=smart
gfx_center_vertical=smart

But hoping there is somewhere globally it can be applied as its happening with all games.

Also where can one go to obtain the "latest: WHD load versions of the games please.

Thanks,
Dwarfboysim

Thanks,
Dwarfboysim

**Comment by Dwarfboysim** [comment] 2019-12-25 23:32
gfx_center_horizontal=smart
gfx_center_vertical=smart
Would these be the correct commands to place in the hostprefs.conf to turn on smart centring by default for ALL WHDLoad games and Amiberry configurations. I want to avoid having to tweak a custom UAE file for EVERY game as its happening to all of them
Dwarfboysim

**Comment by midwan** [comment] 2020-02-03 18:30
This is a dupe of #577 so let's keep the discussion there :)

**Closed by midwan** 2020-02-03 18:30 UTC
Labels: duplicate
