### ISSUE TITLE
Onscreen keyboard

### ISSUE THREAD

**Issue by Tobias2K18** [midwan/amiberry#861] opened 2021-11-15 18:00 UTC
Hello, 

i think that the emulator needs an onscreen keyboard.  This feature was requested already but i think it is very important. In my setup is no room for a real keyboard and this makes the emulator unuseable to me. Please consider adding this feature. It is not important that i looks nice. It just should be available. 

Best regards.

**Comment by midwan** [comment] 2021-11-15 18:30
This is a duplicate of #224 
Please keep the discussion in the same issue, to avoid confusion.

**Closed by midwan** 2021-11-15 18:30 UTC
Labels: duplicate
