### ISSUE TITLE
Pinball Dreams Graphics Issue with flippers

### ISSUE THREAD

**Issue by jimi007** [midwan/amiberry#796] opened 2021-04-07 13:17 UTC
Issue occurs in Pinball Dreams v1.7  using Amiberry 4.1.2 default settings and Retropie 4.7.11 on a Pi4

**To Reproduce**
Run Pinball Dreams lha (NTSC and PAL version)
Go to any table
The flippers at the bottom have graphics issues and the ball gets stuck

**Expected behavior**
Clear graphics with no issues

**Additional context**
Using Amiberry default settings and have tried other CPU combinations - Maybe I haven't come across the right one.

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by midwan** [comment] 2021-09-05 14:43
Duplicate of #799

**Closed by midwan** 2021-09-05 14:43 UTC
Labels: duplicate, compatibility, fixed in dev
