### ISSUE TITLE
Black screen when trying to play amiga games with retropie

### ISSUE THREAD

**Issue by TheMaguffin** [midwan/amiberry#672] opened 2020-07-26 19:12 UTC
Im sorry if i have a lack of information ill try to fill this out as best as possible but im very new to this scene i have purchased a retro handheld (first one ive ever owned) (console being 1up piboy xl factory settings)

Bug
black screen when attempting to play amiga games on retropie 

**To Reproduce**

1. Go to 'my installed amiga game of choice'

2. start game

3. See error
error being that the screen stays black sometimes i can hear music of the games and often a cursor appears in the top left corner but the game never truly starts 
**Expected behavior**
i expect the game to just be playable but again nothing happens 

- OS: retropie 4.4

- Device: rassberry pi 3b + (i believe )

**Additional context**
so i have viewed a few issues and i have found no solutions that work for me specifically 
i have checked the kickstart files and they all seem to be in order to my limited knowledge and have checked the paths as well as the roms being in lha format

**Comment by midwan** [comment] 2020-07-26 21:14
This seems like a duplicate of #671 - closing this one, let's keep the details on that.

**Closed by midwan** 2020-07-26 21:14 UTC
Labels: duplicate
