### ISSUE TITLE
Fast Copper

### ISSUE THREAD

**Issue by Tomato1981** [midwan/amiberry#654] opened 2020-06-10 13:11 UTC
Many games now doesn´t working with "Fast Copper", so you have to switch it off, and most of games are too slow. Solution is Frame skip, but this make choppines of course.

PS: I love Amiberry and your work.)

**Comment by midwan** [comment] 2020-06-11 06:33
@Tomato1981 
Sorry, but I'll need more details than that.
Which platform are you testing with?
Which distro?
What games did you try?
How do you define "now"? Did they work better with a previous version you mean? If so, which one?

**Comment by midwan** [comment] 2020-06-13 19:52
Please come back with specific details as requested above, if you would like to look into this any further. Closing the issue for now, as there's nothing further we can do as it stands.

**Comment by Tomato1981** [comment] 2020-06-14 11:39
Hi.) Here are more details...
You´ll see in the pictures.
![FastCopper01](https://user-images.githubusercontent.com/48894236/84592212-38ab9700-ae44-11ea-8217-a6d874f6eadf.jpg)
![FastCopper02](https://user-images.githubusercontent.com/48894236/84592214-39dcc400-ae44-11ea-9033-e114255ef994.jpg)

(I am using Amiberry 3.1.3 on Raspberry Pi 3b with Emulation station 2.8.3RP)
(I tested 700 games last year, belive me:))

**Comment by midwan** [comment] 2020-06-14 16:03
Fast Copper is actually a hack, that is not officially maintained (WinUAE had it ages ago, but has since removed it). It's possible that with the improved core emulation updates in Custom Chipset and Drawing routines, some things got worse regarding Fast Copper.

I'll investigate just in case I missed anything during the updates, by comparing the Fast copper implementation of 2.25 and that of the latest 3.2.

But it's possible that that piece of code is the same, and it's just showing it's "hacky" self to us in these cases. Since the emulation got more accurate with v3.x (compared to v2.x), we are only seeing that now.

If that is the case, and we have to make a choice, I still prefer to have better compatibility overall than trying to make a hack work.

**Comment by Tomato1981** [comment] 2020-06-14 16:09
Thanks again for very quick answer:) It´s true, that emulation works better without this Copper Hack, but many apps will be slower. Solution is move on faster platform - Raspberry Pi 4. :)

**Comment by midwan** [comment] 2020-06-14 16:09
Let's see if I can find anything, just in case. :)

**Comment by midwan** [comment] 2020-06-14 17:50
Looks like TomB had made some changes to the Fast Copper code, back in March 2019. Those we also merged into Amiberry.

I tried reverting those, and testing the titles mentioned above, however the results are exactly the same. Therefore we have to conclude that the problem is not caused by any changes in the Fast Copper logic, but rather the rest of the updates coming from WinUAE.

I'm afraid we'll have to live with it for now, for the reasons I mentioned above.

PS: An RPI4 can handle both games perfectly fine at 50FPS, without Fast Copper. ;-)

**Closed by midwan** 2020-06-14 17:50 UTC
Labels: can't recreate, question

**Comment by Tomato1981** [comment] 2020-06-14 18:07
Thanks for message.) I try to live with Rpi 3 for a while. Many people still have it.
I recently finished my Amiga Image with 700 perfectly configured games.
(it also contains all 3D boxes, logos and videos. If you want this, tell me. It´s little thing what I can do for you for your amazing work)

PS: The problem with Copper affects about 25 percent of games.
