### ISSUE TITLE
Support for other popular arm-based SBCs (e.g. Odroid XU4)

### ISSUE THREAD

**Issue by bspinner** [midwan/amiberry#143] opened 2017-10-31 09:39 UTC
Hi,

I'd really love to see support for the Odroid XU4.
Would it still be possible to support other arm-based SBCs or is the codebase already tightly knit to  raspberry pis?
Can someone give a coarse overview what would have to be done to support the odroid xu4 and other?

**Comment by HoraceAndTheSpider** [comment] 2017-10-31 10:27
There are plans to port to other ARM machines, yes.  A lot of the work seems to involve utilising the appropriate SDL port for the target machine. Once we have the base-compile, it is simply a case of some testing on the machine to resolves any machine specific issues that occur. 

Unfortunately I am not aware of anyone in the dev team who has one of these machines.

**Comment by midwan** [comment] 2017-11-01 15:51
There is definitely a plan for supporting more platforms in the future. The port to SDL2 was done for this purpose as well.

The current state is that most of the code is portable enough to run on other platforms anyway, but the SDL1 branch has some specific pieces tied to the Pi for hardware acceleration of the display (DispManX).

In SDL2 this is normally not needed and you have a better abstraction layer, which allows for better portability between platforms. So if this is going to work, it will probably be using this version.

However, the problem is that the SDL2 framework itself doesn't offer full hardware support for all platforms. Even on the Pi, there were glitches if certain versions of the firmware were used, in combination with running it under X11 or not, using the OpenGL (vc4) driver or not, etc.
Other platforms don't seem to have any hardware acceleration at all under SDL2, which makes the whole project unusable. Perhaps this can be remedied by compiling SDL2 from source on those platforms, but since I don't have most of them at my disposal it's not easy to say.

I have a Pine64 which is my testbed for porting it, but I can't test other platforms "hands-on"...

**Comment by bspinner** [comment] 2017-11-02 20:09
Ah, there's a SDL2 branch already, great! Didn't see that one before 👍 

I just pulled it, followed the guide in the README, created a `xu4` target and well.. it compiles.. and starts! 😃  
Are there some standard test cases to make sure *everything* runs fine?

(used the linux distribution provided by hardkernel)

**Comment by midwan** [comment] 2017-11-02 20:13
The test cases are usually to check different configurations (e.g. A500 emulation, A1200 emulation, CD32 emulation) with different environments (e.g. Workbench with P96, games, demos).

There are known issues and glitches with certain games/demos, but the Workbench installations should work fine.

**Comment by bspinner** [comment] 2017-11-02 21:03
I'll extend the pull request #144 regarding all Odroid XU4 todos/problems/etc.

**Comment by midwan** [comment] 2018-01-11 10:03
I believe we can close this one?
If we have any specific issues, we can open them as separate ones so we can monitor and fix them individually (like the JIT related problems on XU4).

**Closed by midwan** 2018-01-11 10:03 UTC
Labels: enhancement
