### ISSUE TITLE
Lha CRC errors with JIT enabled

### ISSUE THREAD

**Issue by henrikstengaard** [midwan/amiberry#313] opened 2018-04-28 08:21 UTC
![amiberry_lha_crc_error_jit_screenshot](https://user-images.githubusercontent.com/9459668/39394085-e2bca388-4acd-11e8-8040-2350c4ca8354.jpg)

### Expected behavior
No CRC errors when extracting lha archives with JIT enabled.
It works fine without CRC errors, if JIT is disabled.

### Actual behavior
CRC errors occur when extracting lha archives with JIT enabled.

### Steps to reproduce the behavior

1. Extract attached file amiberry_jit_crc.zip and launch Amiberry with added directory containing the files. Config file is included. Make sure JIT is enabled.
2. Type "lha -m1 x pfs3_53.lha sys:t/".
3. Wait for lha to break with crc errors.

[amiberry_jit_crc.zip](https://github.com/midwan/amiberry/files/1957456/amiberry_jit_crc.zip)

**Comment by henrikstengaard** [comment] 2018-04-28 11:30
Strange, I forgot to mention that I used latest version pulled from master and freshly compiled yesterday. I configured cpu to 68020 with enabled jit.

Which version of amiberry are you using and does cpu set to 68040 make a difference with jit?

**Comment by midwan** [comment] 2018-04-28 11:31
I'll be testing this today, in both the latest and previous versions to see...

**Comment by midwan** [comment] 2018-04-28 13:40
@henrikstengaard Confirmed in the current version from the master branch, will test the older versions to check if this is something I (re)introduced when I reverted the JIT code one step back.

**Comment by midwan** [comment] 2018-04-28 13:43
Confirmed in v2.19 binary also.

**Comment by midwan** [comment] 2018-04-28 13:47
@henrikstengaard 
However, this seems to be a problem with the LHA binary you provided:
Using the latest LHA package from Aminet (`LHA22.lha`) does not show the same behavior.

**Comment by midwan** [comment] 2018-04-28 18:04
@henrikstengaard 
Sorry, I meant that this binary causes it but the other one doesn't. It's still a bug, obviously.

**Comment by henrikstengaard** [comment] 2018-04-28 19:03
Ahh yes, I assume it's a tricky one to fix, but hopefully this can help since it can reproduce issue.

**Comment by henrikstengaard** [comment] 2018-04-30 19:12
I can confirm that using lha22.lha from aminet does solve the crc errors.

For a quick fix, I'm going to update from lha 2.15 to lha 2.2 to the crc errors I have encountered with Amiberry and JIT enabled for cpu 68020 and fpu 68882.

**Comment by midwan** [comment] 2018-10-06 13:38
@henrikstengaard 
this should be fixed in `dev`, with 37e8c0e4ac95b1a05c1656d9eda9ab856637cf49

**Closed by midwan** 2018-10-06 13:38 UTC
Labels: bug, compatibility
