### ISSUE TITLE
Bad dudes vs dragonninja running at too fast speed

### ISSUE THREAD

**Issue by stuffu** [midwan/amiberry#791] opened 2021-04-04 14:06 UTC
Running baddudes runs at way too fast speed. Using amiberry 4.1.1 on retropie 4.7.11, rpi4, everything default in amiberry.

Running baddudesvsdragonninja WHDLoad v1.3 should be enough to reproduce the the problem.

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by midwan** [comment] 2021-04-04 21:31
Looks like the problem is the 68020/14MHz combination here.
If I test it with 68000/7MHz and Cycle-Exact, it works normally.

**Comment by stuffu** [comment] 2021-04-05 06:52
Thanks, wasn’t sure if I should change it on my side or if it was a bug, or even a possible change on the Amiberry-XML-builder side.

**Comment by midwan** [comment] 2021-04-05 21:33
Actually Cycle Exact is not needed, it works in the expected speed with just 68000@7MHz speed.
I think we might need to change the whdload autoloader logic a bit, since 68020 at 7MHz doesn't work with WHDLoad anymore (after the recent improvements in accuracy). Perhaps we should be using 68000 at 7MHz for non-AGA games, instead.

**Comment by midwan** [comment] 2021-04-05 21:44
Actually, the logic is already there. If the following option is specified in the XML:
```
CPU=68000
```
Then it will use an A600 configuration, with a 68000 CPU at 7MHz.
This fixes the problem for this game in my tests.

**Comment by midwan** [comment] 2021-05-05 09:16
@HoraceAndTheSpider 
did you get a chance to update the XML for this case?

**Comment by midwan** [comment] 2021-09-05 14:50
Closing this as it's not part of Amiberry's code - please refer to Horace's XML repo (https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder) if necessary

**Closed by midwan** 2021-09-05 14:50 UTC
Labels: compatibility
