### ISSUE TITLE
Can't get some WHDLoad games to work

### ISSUE THREAD

**Issue by ghost** [midwan/amiberry#455] opened 2019-03-26 22:06 UTC
I tried loading 'Jaguar XJ220' but got the following error (I added the DATA directory command to the autoboot file) -

```
: Unknown command
 failed returncode 10
```

I tried 'Ivans Off-Road Racing' NTSC and got -

```
xpkmaster.library version 4 not found
File "Disk.1" is compressed using XPK but not cached.
Detected in function 'resload_DiskLoad'.
WHDLoad failed returncode 144
```
The PAL version works.

I used a fresh Retropie install and installed Amiberry from Binary (2 days ago). I updated Amiberry from Source and clicked the 'Update XML' button in the GUI. Why does it download the WHDLoad file ? All the whdboot stuff is zipped. Is this supposed to be extracted ?

**Comment by HoraceAndTheSpider** [comment] 2019-03-28 22:16
> I tried loading 'Jaguar XJ220' but got the following error (I added the DATA directory command to the autoboot file) -
> 
> ```
> : Unknown command
>  failed returncode 10
> ```

That looks like you have broken the auto-startup file. ` failed returncode 10` means that Amiga DOS cant find the file it's trying to run as a command. ` : Unknown command` however shows that you dont have a command thats being run, so either there is a typo there, or a bad text editor which has made an error on a line-end. It would normally read `name-of-file : Unknown command`

> I tried 'Ivans Off-Road Racing' NTSC and got -
> 
> ```
> xpkmaster.library version 4 not found
> File "Disk.1" is compressed using XPK but not cached.
> Detected in function 'resload_DiskLoad'.
> WHDLoad failed returncode 144
> ```
> 
> The PAL version works.

Thank you for letting me know about Ivans Off-Road Racing NTSC - this looks like it may be aa similar problem as Dungeon Master (an extra library required) ... i try to avoid having the extra libarires by default, so i've added this game as a fix for the. If i have time to complete a manual update now, i will, otherwise it will be picked up on the next 'major' XML scan (which is every Sunday night IIRC.) , so on Monday try the auto-update of the XML and see if it works.

> 
> I used a fresh Retropie install and installed Amiberry from Binary (2 days ago). I updated Amiberry from Source and clicked the 'Update XML' button in the GUI. 

>> Why does it download the WHDLoad file ? 

Because, to ensure the booter now runs as 'slim' and 'fast' as possible, this is the one and only file needed for the booter. 

You requested that it be made faster, and the dependency on the previous booter, in the below request:  https://github.com/midwan/amiberry/issues/345 - this is part of fulfilling that request.

>>All the whdboot stuff is zipped. Is this supposed to be extracted.

The zipped whdboot is a fall-back only (e.g for the extra libraries as above, or in the event of the local WHDLoad not being available), i have tried to remove the requirements for it where possible, to achieve the above faster booting.

It can be used zipped or unzipped. The boot sequence is able to detect both.

**Comment by SaucySarah** [comment] 2019-03-28 22:36
```
Because, to ensure the booter now runs as 'slim' and 'fast' as possible, this is the one and only file needed for the booter.

You requested that it be made faster, and the dependency on the previous booter, in the below request: #345 - this is part of fulfilling that request.
```

This was nothing related to the request I made a long time ago. I asked because the original WHDLoad file is inside the whdboot.zip so I wondered why it downloaded it again as a separate file. I only listed what I did to update in case it was a Retropie bug again.

**Comment by HoraceAndTheSpider** [comment] 2019-03-28 22:42
>> This was nothing related to the request I made a long time ago.

Yes it is.  The reason it is there (to answer your question), is directly related to the implentation that fulfiled the request.

Carrying out the the impentation that covered a faster booter, meant that i included  the WHDLoad file as a seperate file (i.e. not inside the boot zip) so that it can be accessed without being dependent on the booter zip being there.

**Comment by SaucySarah** [comment] 2019-03-28 23:24
Alright, you don't have to sound so hostile everytime you answer. It was merely an afterthought in case it was Retropie's fault. Could you check Jaguar XJ220 at your end please if it's not too much to ask ?

**Comment by HoraceAndTheSpider** [comment] 2019-03-28 23:46
i'm just stating facts, and making sure you are provided the answer to your question. There is certainly no hostility at this end, i just tend give the details (which some authors on un-named repos often do not!) to explain.


Yes, i can check Jaguar XJ220 certainly - and now confirm it is working here. 

There is a known issue to do with the `data=` parameter as you mentioned, but the error it causes would be different. This is why i suspect an error with the text format line-end, and it might depend on which text editor you used to make the change. 
Another user had a similar problem recently even with a 'unix friendly' Windows text editor, and this was due to the fact the needed to change the settings for that editor. (i believe it was Notepad++ or similar). To be really sure, I would recommend making the change using nano on the host machine to be sure, but with a fresh (amiberry generated) auto-startup. 

To assist, I have also fixed the root bug in the slave, and sent an updated WHDLoad package to whdload.de, so it might be that v1.6 will roll out soon and this will all be rectified automatically in the future.

**Comment by SaucySarah** [comment] 2019-03-29 16:42
Progress update. I got Jaguar XJ220 working with the Nano editor. I updated the XML and tried Off-Road Racing NTSC and now get an error saying -

```
Please insert volume
(null)DH3
in any drive
```

**Comment by HoraceAndTheSpider** [comment] 2019-03-29 20:56
Have you deleted/unzipped the `boot-data.zip` ? This is used to provide the extra library files needed. Persumably you would have the same problem running Dungeon Master.

If it is unzipped and not working, possibly this is required to be zipped for this fix, which i will check, as both should work. You would also need the latest version from the current source.

re: `kick33192.A500`  the following seems to explain: https://www.amigaforever.com/kb/15-120

> some online resources also reference a "kick33192.A500" file, which however was confirmed to be a typo (it should read "kick33180.A500" - as of 2014, no 33.192 Amiga ROM is known to have ever been released)

Amiberry uses symlinks to create the .rom files to match the .rtb files, so there is no need to find the exact equivalent for each. The RTB's are provided as per the original source names (kick33180 is already privded), so i will remove this in the future to avoid any confusion.

**Comment by SaucySarah** [comment] 2019-03-29 21:21
Yes, Dungeon Master gives the same error. My `boot-data` is still zipped the way it came.

**Comment by HoraceAndTheSpider** [comment] 2019-03-29 22:40
Check that it is visible in the whdboot folder and the latest version (updated about a month ago) 

Also you might need to delete the auto-startup and any existing .uae file you may have saved for the game.

**Comment by SaucySarah** [comment] 2019-03-29 22:56
Check what, the `boot-data.zip` ? Can't do it till tomorrow as i'm somewhere else. I did a fresh RetroPie install about 3 days ago, updated Amiberry from Source and clicked the update XML button this morning. It's the first time that i've run Dungeon Master so the autostartup is new, and for Off-Road Racing I deleted the autostartup and ran the game again after the XML update.

**Comment by HoraceAndTheSpider** [comment] 2019-03-31 14:18
I would suggest unpacking `boot-data.zip` is around 706kb (the older version is nearer 665kb) and that in the LIBS/ folder is the sub-folder `compressors`. 

I was able to reproduce your error only by delibrately replacing it with the older version, which is missing these files.

If RetroPie is still installing (or not updating) the older version, that will need to be addressed from their repo.

**Comment by SaucySarah** [comment] 2019-03-31 20:47
I deleted the `boot-data.zip` and updated 'Amiberry from Source'. I updated the XML. The `boot-data` is 690KB Zipped. Now I get -

Dungeon Master error -
```
Please insert volume
(null)DH3
in any drive
```

Ivan Off-Road NTSC error -
```
xpkmaster.library version 4 not found
File "Disk.1" is compressed using XPK but not cached.
Detected in function 'resload_DiskLoad'.
WHDLoad failed returncode 144
```

**Comment by HoraceAndTheSpider** [comment] 2019-03-31 21:31
`/opt/retropie/emulators/amiberry/whdboot-dist` is created by retropie, not us, so you would need to ask them about the difference. 

I would still need to know if the `compressors` folder is in `libs` - as i said above, it could be that RetroPie is installing an out of date version, and not the one from here.

**Comment by SaucySarah** [comment] 2019-03-31 22:17
I'll look tomorrow, but as i've said several times, i've 'updated from Source' which is compiling straight from this github. Unless you're using a different boot-data.zip that you haven't commited to this github ? 
The last time I looked there was a 'compressors' directory. Is there a particular file that you want me to confirm exists ?

**Comment by HoraceAndTheSpider** [comment] 2019-04-01 18:19
It’s possible that “update from source” isn’t correctly updating the file, but only updating the main binary, which is why I am asking for that to be checked, in which case the problem is with the retropie update script. Eg with the “whdboot-dist” folder you mention which is nothing to do with us.

This has to be ruled out becuase I am only able to reproduce this error by using an incorrect/older boot data zip.

Compressors folder should contain a number of xpk libraries.

**Comment by SaucySarah** [comment] 2019-04-01 20:12
Yes, there is a 'Compressors' folder inside the `boot-data.zip` Libs folder, containing -
```
xpkCBR0.library
xpkDLTA.library
xpkDUKE.library
```
etc. (17 libraries all dated 2007)

`xpkmaster.library` is in the Libs folder

**Comment by HoraceAndTheSpider** [comment] 2019-04-01 21:07
Ok thank you for ruling that option out.


 I can only assume there is something awry with how a previous update has changed locations m on your setup, eg. If there was an existing .uae being used for the game, or it has ended up pointing the DH3 to the wrong location. 

If you load the game and then view the Amiberry HD panel you should see the DH3 drive mounted. Perhaps try manually re-mounting the boot-data.zip there to see if a difference occurs. 

It may also be worth switching on logging in the amiberry.conf and adding it to pastebin to be viewed here for checking.

**Comment by SaucySarah** [comment] 2019-04-02 10:54
I deleted all traces of Amiberry from those two locations, uninstalled. I then installed from Source. Those two games still give the same errors. I tried to manually mount the `boot-data.zip` in the GUI in DH3 but I couldn't see it in the requester, only 'game-data' and 'save-data'. I enabled logging in the `conf` file but can't find the log (`/opt/retropie/emulators/amiberry` ? not there). I give up on this one !

**Comment by HoraceAndTheSpider** [comment] 2019-04-02 11:03
>>  I couldn't see it in the requester

Do you mean you couldnt locate the file to pick?  That sounds like the cause of the issue tbh.

Possibly /opt/retropie/emulators/amiberry/ needs to be given `chown pi:pi` permissions in order for the file to be written (why RetroPie wont allow the emulators to write into their own folders i do not know)

**Comment by HoraceAndTheSpider** [comment] 2019-04-02 11:11
Additionally; When you re-isntalled from source did you update the XML? Note that the most up-to-date XML is not hosted here with the source. (@midwan 's choice)

**Comment by SaucySarah** [comment] 2019-04-02 11:55
Yes, I clicked the update XML button. Now Dungeon Master and Off-Road NTSC display -
```
Please insert volume
(null)DH3
in any drive
```
Nearly all other games i've tried work fine (see below) so the `boot-data.zip` is being mounted correctly.

Dynamite Dux just gives a black screen.

**Comment by HoraceAndTheSpider** [comment] 2019-04-02 11:58
Other games no longer require `boot-data.zip` by default. These two do, because of the additional XPK libraries required.

**Comment by SaucySarah** [comment] 2019-04-02 12:14
So the `boot-data.zip` is only needed for 2 games ?? The boot loader is inside this zip. Are there any other games ? If not then maybe the `boot-data.zip` has never worked since. I'm not sure how your's is working. I suspect you're telling porkies !

**Comment by HoraceAndTheSpider** [comment] 2019-04-02 12:46
Bluntly, If i am going to be accused of lieing, i am going to cease trying to help. 

I've shown considerable patience here, even stomaching being called "hostile", despite doing nothing but try to help resolve your issues.

For the sake of clarity, (and purely because i am not in work today) i will explain, and reference. 

Yes - The boot-loader is currently used only for these two 'supported' RetroPlay games (i,e games documented in the XML). It will be used as a 'fall-back' for non-supported LHA games. However, I am not aware of any sources for these other than older versions of existing games. If other (so far untested) games also need the XPK libraries they will be added to the list of two.

As i stated earlier up-thread, here: https://github.com/midwan/amiberry/issues/345 a request was made to remove the use of AMOS for the WHDLoad support by yourself.

This was achieved with the recoding of the whdload boot system, which begain being merged into the main branch in commit: https://github.com/midwan/amiberry/pull/430 and by increasing the level of information in the XML generator. This here: https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder - i am downloading and scanning the RetroPlay LHA packs every 2-3 days to keep the XML as up-to-date as possible and keep compatibility at a maximum,


These changes came in with Version 2.25 and is noted here: https://github.com/midwan/amiberry/wiki/Version-history with the following lines, which were all part of this update.

```
WHDLoad and Autobooter update: Big performance improvements during startup
Rescan Paths button now recreates ROM symlinks also
Added new command-line option that handles .lha and .cue files for Autobooter: -autoload=<path-to-file> 
```


You'll see easy evidence of this on most games where `/tmp/` is now mounted as DH0 **instead** of the `boot-data.zip` - this is because Amberry now writes it's own `startup-sequence` to this location by cross-comparing the file (currently by name only) and the data held in the XML.


implementating this, removed the `boot-data.zip` and the AMOS booter in 99% of use cases. Since the file remains present in the Amiberry repo for extra compatibility, rather than add more dependencies (e.g the libraries on their own), it was also used for the additional libraries requirement here:   https://github.com/midwan/amiberry/pull/431
 
That pull-request was specifically to resolve the issues with Dungeon Master, so i am 100% confident in stating that this works
https://github.com/midwan/amiberry/issues/358

The https://github.com/midwan/amiberry/pull/431  implemenation was a simple matter of automating the manual fix shown here: https://www.youtube.com/watch?v=4bG0SAGDJkk

When you reported the same issue with S.O.R (NTSC) i added it to the list with Dungeon Master here: https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder/commit/4c63726df3c6771851ee85b1cd3714e3f1afee63 and have since tested that it is a working fix.

**Comment by SaucySarah** [comment] 2019-04-02 13:14
Alright, keep your hair on ... As I said before, i'm giving up on this one. It doesn't work for me on a fresh install of RetroPie/Amiberry. I only reported Off-Road Racing NTSC to help with pointing out compatibility issues. I can easily use the PAL version or the prefered ADF version (including Jaguar XJ220) which are both 1 disk anyway.

**Comment by 2xtime** [comment] 2019-04-03 18:23
@SaucySarah Yeh, I would always favour ADF's and only use WHDLoad if there are lots of disk swapping or it takes ages to load. Plus with ADF's you get to see/hear the iconic cracktros which are a big part of the nostalgia, plus they nearly always have a cheeky cheats trainer ! The majority of games seem to work fine with the floppy speed set to 800 as well.

**Comment by Muppetteer** [comment] 2019-05-16 00:28
I have this same issue with Dungeon Master (DungeonMaster_v1.2_0833.lha) on a fresh install of Amiberry and Retro Pie.

`Please insert volume
(null)DH3
in any drive`

I cannot update the database XML via Amiberry because it says it cannot detect an internet connection, despite the fact that I can ping google.com via SSH on the Pie at the same time. Any tips to solve that one? I read someone else had the same problem on another unrelated issue here. Nevertheless I manually replaced whdload_db.xml after downloading it from the XML Builder Github project. Still the same problem.

I can see boot-data.zip is in the correct place and it has the Compressors directory mentioned earlier.

It maybe something to do with symbolic links. Amiberry is looking for DH3 here:
`/opt/retropie/emulators/amiberry/whdboot`

which is actually a symlink to here:
`/opt/retropie/configs/amiga/amiberry/whdboot`

but when I try to manually update the mount point in Amiberry it can't see any of the symlinked folders in 
`/opt/retropie/emulators/amiberry`

There should be conf, savestates, screenshots, kickstarts, controllers, and whdboot. All it can see are the two real directories, whdboot-dist and data.

If I try to update the mount point to boot-data.zip while inside Amiberry I can't because the file selector only shows directories, not files. Is there a way to manually set it?

**Comment by HoraceAndTheSpider** [comment] 2019-05-16 18:03
to be honest - this sounds like an issue with the amiberry distribution, and it may be better to report it with them.

Try setting all available pi user permissions in `/opt/retropie/emulators/amiberry` with `sudo chown -hR pi:pi /opt/retropie/emulators/amiberry` 

I assume the compressors folder has the needed files in it, and that you dont have a clash with another  copy of boot-data.zip (i.e. an out-of date one provided with the RP distro)

I did test from a fresh retropie install previously and managed without issues, but would have updated the above file from the Download button.

**Comment by Muppetteer** [comment] 2019-05-16 23:45
Thanks for trying to help. I re-installed Amiberry from source yesterday which still gives me an out of date whdload_db.xml so I manually copied in a fresh one. I've checked the md5 checksum of boot-data.zip and it is the same as the version in Github here. Applied suggested change to ownership.

I solved the download button not working. I had both wifi and a network cable connected and thus 2 IP addresses. Unplugging the network cable and rebooting so that I only had 1 IP through wifi allowed the update to work. It told me I was up to date. To be sure I deleted whdload_db.xml and ran it again and it grabbed the latest file which was the same anyway. It did not overwrite boot-data.zip with a newer version.

Still no joy. Sorry I thought I was reporting this to the right place - where should I report this to whoever looks after the distribution?

**Comment by HoraceAndTheSpider** [comment] 2019-06-09 11:32
> Still no joy. Sorry I thought I was reporting this to the right place - where should I report this to whoever looks after the distribution?

https://github.com/RetroPie

**Comment by HoraceAndTheSpider** [comment] 2019-06-09 12:17
I've added extra code for the update of the `boot-data.zip` with the XML download - hopefully this may resolve the issue when merged into the master branch.

I will also be adding a 'health check' status button to help resolve these kinds of issues.

**Comment by midwan** [comment] 2019-09-20 23:03
Closing this as there hasn't been any further activity for a while.

**Closed by midwan** 2019-09-20 23:03 UTC
Labels: can't recreate
