### ISSUE TITLE
"Update WHDLoad Database/XML" results in Amiberry Crash since Version 3.1.3.1

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#635] opened 2020-05-01 12:29 UTC
System: Raspberry Pi 4 with RetroPie 4.6 and Amiberry Version 3.1.3.1

"Update WHDLoad Database/XML" results in Amiberry Crash since Version 3.1.3.1

Cheers
Retro1968

**Comment by midwan** [comment] 2020-05-01 12:44
Can you try the following test please:

* Exit EmulationStation
* Login to the console
* Launch Amiberry manually (e.g. sudo /opt/retropie/emulators/amiberry/amiberry)
* Test the button again

**Comment by midwan** [comment] 2020-05-01 12:44
Also, this is really covered in #540 :)

**Comment by Retro1968** [comment] 2020-05-01 13:01
1. "sudo /opt/retropie/emulators/amiberry/amiberry" results in error message "Internal error: file scrc/osdep/gui/main_windows.cpp line 1031".

2.  Internet is OK, since i can surf in IBrowse on AmigaOS 3.1.4.1

**Comment by midwan** [comment] 2020-05-01 13:25
@Retro1968 
That's indicating that it failed to load the GUI font. It's trying to open the file `data/AmigaTopaz.ttf` - does that exist from the location the binary is in?

**Comment by Retro1968** [comment] 2020-05-01 13:42
![data](https://user-images.githubusercontent.com/58906142/80809607-5093c800-8bc2-11ea-8d36-657f22db1166.jpg)

**Comment by stuffu** [comment] 2020-05-01 18:22
I can confirm I have the same issue when updating WHDLoad db.

**Comment by Retro1968** [comment] 2020-05-02 09:16
I deinstalled the Version 3.1.3.1 and installed the pre-compiled Amiberry Version 3.1.3
The error is now also present here. Maybe the problem is with RetroPie 4.6?

**Comment by HoraceAndTheSpider** [comment] 2020-05-02 10:43
There have always been issues with the RetroPie install not giving permissions properly where the file gets saved - has anyone tested if restoring full user rights to `pi` user where it is saved might solve this?

**Comment by Retro1968** [comment] 2020-05-02 16:49
This commands didnt solved the problem:

sudo chown -R pi:pi /home/pi
sudo chown -R pi:pi /opt/retropie/configs

**Comment by midwan** [comment] 2020-05-02 22:05
It certainly works on the standard Raspbian Buster systems I've tested it with, so this sounds like it's RetroPie-specific at this point. More investigation is needed to find out why...

**Comment by Retro1968** [comment] 2020-05-03 07:30
Maybe you should report that to the RetroPie team?

**Comment by Retro1968** [comment] 2020-05-03 08:54
I just tested your new version 3.1.4 beta. Unfortunately, the error remains.

**Comment by midwan** [comment] 2020-05-03 10:19
@Retro1968 there was no change related to this area in the beta, so of course the behavior would be the same :)
If there's any progress made in this, I'll mention it here of course. ;)

**Comment by joolswills** [comment] 2020-05-03 11:33
I will look into this on RetroPie.

**Comment by joolswills** [comment] 2020-05-03 20:19
I can reproduce the crash. Not debugged yet.

```
PING www.google.com (172.217.169.36) 1(29) bytes of data.
9 bytes from lhr48s08-in-f4.1e100.net (172.217.169.36): icmp_seq=1 ttl=55

--- www.google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms

2020-05-03 21:16:25 URL:https://raw.githubusercontent.com/HoraceAndTheSpider/Amiberry-XML-Builder/master/whdload_db.xml [4583717/4583717] -> "/tmp/whdload_db.xml" [1]
/tmp/whdload_db.xml:26772: parser error : PCDATA invalid Char value 2
			$z÷ÄAú¨Nª
```

**Comment by joolswills** [comment] 2020-05-03 20:20
Sorry. Missed some of the log. Updated previous reply.

**Comment by joolswills** [comment] 2020-05-03 20:28
There is a line of garbage at the referenced line in the downloaded file. But I'm not sure that's the cause of the crash.

**Comment by joolswills** [comment] 2020-05-03 20:53
I tested with a fixed XML and it was fine. Also if the file doesn't exist or so it will crash too.

Not sure why this isn't reproducible for you @midwan  - did you test it before the XML got broken maybe. 

Some error handling in this code is needed anyway. But it's not a retropie issue.

**Comment by midwan** [comment] 2020-05-04 07:31
@joolswills 
Thanks for the assistance! Yes, this area definitely needs some error handling.

**Comment by midwan** [comment] 2020-05-04 08:53
@HoraceAndTheSpider 
There seems to be a problem with the current `whdload_db.xml` file in your repo. Specifically, I found this:
`error on line 26813 at column 10: PCDATA invalid Char value 2`

It's in the game `Benefactor_v1.2_CD32`, in the `<custom>` fields (3rd line).
It looks like this causes the parsing of the XML to fail, even if the download is successful.

I'm making several improvements in this area in Amiberry, so it will not crash anymore, but I think you need to update the file also. ;)

**Comment by nemo93** [comment] 2020-05-04 12:35
Hello @midwan it's something I should have fixed in my [xml](https://raw.githubusercontent.com/nemo93/Amiberry-XML-Builder/master/whdload_db.xml). I'm working with @HoraceAndTheSpider to merge it into the official repo but to have confirmation would be great. Thanks.

**Comment by midwan** [comment] 2020-05-04 16:23
@nemo93 yes, that doesn't have the problem. ;)

**Comment by HoraceAndTheSpider** [comment] 2020-05-06 08:35
> @HoraceAndTheSpider
> There seems to be a problem with the current `whdload_db.xml` file in your repo. Specifically, I found this:
> `error on line 26813 at column 10: PCDATA invalid Char value 2`
> 
> It's in the game `Benefactor_v1.2_CD32`, in the `<custom>` fields (3rd line).
> It looks like this causes the parsing of the XML to fail, even if the download is successful.

The garbled characters are actually correct for what is in the file!!
http://whdload.de/games/Benefactor.html

We will add a work-around on the XML builder, but techncially this is one for the WHDLoad devs to fix!
<img width="565" alt="Screenshot 2020-05-06 at 09 34 53" src="https://user-images.githubusercontent.com/567602/81155466-e3df4b80-8f7c-11ea-81dc-e52cc7d3794b.png">

**Comment by Retro1968** [comment] 2020-05-06 09:50
Interesting. Maybe you should inform the developers about your findings?

**Comment by joolswills** [comment] 2020-05-06 09:53
yeah in that case you can work around it by encoding it correctly in the xml.

**Comment by HoraceAndTheSpider** [comment] 2020-05-06 17:50
> Interesting. Maybe you should inform the developers about your findings?

I have reported it on the WHDLoad Mantis BugTracker for the specific game

**Comment by Retro1968** [comment] 2020-05-07 12:45
I just got the message: "Updated XML downloaded". :-)

**Closed** 2020-05-07 17:35 UTC
Labels: bug

**Comment by HoraceAndTheSpider** [comment] 2020-05-10 12:00
This has also been fixed on the Benefactor slave update: http://www.whdload.de/games/Benefactor.html
