### ISSUE TITLE
[RetroPie] Controller input doesn't work until GUI is opened once

### ISSUE THREAD

**Issue by SeraphisCain** [midwan/amiberry#787] opened 2021-04-02 21:54 UTC
Since updating to 4.1 on RPi 4, I'm having an issue with controls. Specifically, in-game controls don't work unless I go into the menu and change my controller's device type under Inputs from "joystick" to "gamepad". GUI controls work fine, and once I've switched the device to gamepad, everything in-game seems to be configured as it should be. It's just a headache to have to manually switch the device type every time I play a game, and it wasn't like this previously. Is there something I could change in amiberry.conf or hostprefs.conf to make the default device type for my controller "gamepad"?

**Comment by midwan** [comment] 2021-04-03 18:20
What controller are you using please?
When you say in-game controls don't work, what exactly do you mean? No input works, only some kind of input?

**Comment by SeraphisCain** [comment] 2021-04-03 21:02
> What controller are you using please?
> When you say in-game controls don't work, what exactly do you mean? No input works, only some kind of input?

Using a 8bitdo SN30 Pro+. No in-game input works at all.

**Comment by midwan** [comment] 2021-04-03 21:11
@SeraphisCain 
And under which distro are you running this?
Do you have a Retroarch mapping for the controller (e.g. under RetroPie)?

**Comment by SeraphisCain** [comment] 2021-04-03 21:27
@midwan 
Latest RetroPie. Yes, I do have a Retroarch mapping for the controller.

**Comment by SeraphisCain** [comment] 2021-04-04 07:57
Upon further testing, manually setting the controller's device type to "Default" also results in working controls.

**Comment by midwan** [comment] 2021-04-04 08:59
@SeraphisCain 
But "Default" is what is should start up with - doesn't it?
In other words, when _doesn't_ it work?

**Comment by SeraphisCain** [comment] 2021-04-04 10:32
@midwan 

It does not start up with "Default", no. It always starts with the controller's device type set to "Joystick". I don't know why it's started doing this, but ever since updating from 3.x to 4.1 it's been a problem. I've even tried completely uninstalling Amiberry and reinstalling fresh. Still happens.

**Comment by SeraphisCain** [comment] 2021-04-04 11:01
Testing out installing from binary (which is v3.3) instead of source. In-game controls work fine. Input settings upon booting a game (Batman, if it matters, but the problem is the same for all games) look like this:

Port 0: RetroArch Keyboard as Joystick #1 (device type "Joystick")
Port 1: 8Bitdo SF30 Pro+ (device type "Joystick")

Uninstalled, reinstalled from source (4.1). In-game inputs don't work. Booted the same game, input settings look like this:

Port 0: System mouse (device type "Default"
Port 1: 8Bitdo SF30 Pro+ (device type "Joystick")

(Also, I'll note that the RetroArch menu hotkey doesn't seem to work in 4.1 either. I do have a keyboard plugged in though, so I can press F12 to get to the menu. The RA exit hotkey, however, does work. Odd.)

**Comment by stuffu** [comment] 2021-04-04 14:01
I have a similar issue, tried WHDLoad version of Arabian nights, keyboard and mouse connected to rpi4 as well as SN30 Pro (switch mode). The gamepad didn’t work until I entered amiberry menu, inputs and then hit resume, gamepad controls worked again in game.

The controller was recognized as switch controller so all fine there. But it didn’t work until I entered input menu and resumed.

I have cleared every config, uae file etc before installing on retropie.

**Comment by midwan** [comment] 2021-04-04 17:51
Does this only occur when using .lha files? Does it work as expected with .adf files?

**Comment by stuffu** [comment] 2021-04-04 19:44
I only have .lha files so I can’t tell I’m afraid.

**Comment by midwan** [comment] 2021-04-04 21:16
@stuffu / @SeraphisCain 
I'd like to see if this problem is isolated to the WHDLoad booter only (if it only occurs when loading .lha files, then that's a strong indication it is), so could you please do the following test and report back:
- Download the latest version of the AmigaTestKit software: https://github.com/keirf/Amiga-Stuff/releases/tag/testkit-v1.16
- Extract the archive and use the ADF contained to boot Amiberry
- Test your controller in the relevant section of AmigaTestKit
If your controller works as expected there, but it doesn't when loading .lha files, then we'll know where to look.

**Comment by SeraphisCain** [comment] 2021-04-04 21:34
@midwan 

Controller works as expected in AmigaTestKit.

(Though I'll note that I had to hunt down the aros-ext.bin and aros-ext.rom files and put them in the RetroPie BIOS folder for the program to work.)

**Comment by midwan** [comment] 2021-04-04 21:38
Thanks, then I think the problem is related only to the whdbooter setting joystick options. I'll investigate further and update this case when I have more information.

**Comment by jimi007** [comment] 2021-04-05 09:22
Hi

I have noticed this issue too. Using Retropie 4.7.11. RPi 4 . Amiberry 4.1.1 , 8bitdo SF30 Pro controller. WHD lha files.

Whenever I start a game it does not recognise the controller input.  I enter amiberry then resume the game , then the controller works fine. Only an issue on first starting a game.

**Comment by midwan** [comment] 2021-04-05 22:00
Can you guys test compiling from the `dev` branch?
I just added a change there to use `Default` for joystick mode, instead of `Joystick`.

Not sure if this solves this problem entirely, or it needs more work though.

**Comment by SeraphisCain** [comment] 2021-04-06 00:05
@midwan No change after building from `dev` branch. Although, I'll note that after stuffu and jimi007's posts, I'm pretty sure I was wrong about the need to change the device type to "Default". As they've both stated, simply entering the menu and then returning to the game seems to fix the problem. It's the same on this `dev` build. Entering the menu, making no changes at all, then returning to the game restores both in-game controls and the RetroArch hotkeys.

**Comment by midwan** [comment] 2021-04-06 06:36
@SeraphisCain 
Alright, thanks. Just needed to isolate that part and make sure it wasn't related.
I'll dig into this today and see if I can find the solution.

**Comment by midwan** [comment] 2021-04-06 08:42
@SeraphisCain 
I believe this is fixed in `dev` now, would you mind giving it another go please?

**Comment by SeraphisCain** [comment] 2021-04-06 10:08
@midwan Can confirm that the issue is fixed in `dev`. Thank you!

**Comment by jimi007** [comment] 2021-04-06 13:44
@midwan Thankyou for resolving the issue

**Comment by stuffu** [comment] 2021-04-06 18:12
Indeed, thanks for your hard work!

**Closed** 2021-04-06 21:06 UTC
Labels: bug, fixed in dev
