### ISSUE TITLE
[Amiberry v2.12] long wait time with lots of uae configs

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#233] opened 2018-02-06 22:51 UTC
Hi

I have currently 7,800 uae configs in my path folder for uae configs.

When you enter the gui it takes about 7 seconds to open the gui. It seems to always be loading the huge amount of configs. This never used to happen in previous versions of Amiberry.

Could this be fixed? In the meantime I have changed paths away from my 7800 configs to eliminate the 7 second wait.

**Comment by CypherXG** [comment] 2018-02-07 05:11
OMG. Do you really need all these configs? I think u use one for each game, or? Are you really playing all these 7800 Games, Programs..?

**Comment by ransom1122** [comment] 2018-02-07 05:22
Yes.

I have been making a 128gb Solo Amiga build for over a year now. The idea is to have every amiga related game in one image. No I dont play them all. But I do have all of the games available for me with a single press of a button.

I dont intend to use my Amiga image externally. When I finish this image I should easily have over 10k amount of games. 👌

**Comment by midwan** [comment] 2018-02-07 08:27
@ransom1122 
Thanks for opening this up as a separate issue.

Could you please attach a zipped archive of those configs, so I can test it here?
Does it also take 7 seconds the first time you run the emulator, before showing the GUI?

**Comment by ransom1122** [comment] 2018-02-07 08:53
It happens anytime/all the time when you open the GUI...

rename the TXT to RAR on the attachment..

[7800 configs.TXT](https://github.com/midwan/amiberry/files/1702319/7800.configs.TXT)

**Comment by midwan** [comment] 2018-02-07 20:37
@ransom1122 
From what I can see, the same behavior was there (scanning for Configs when opening the GUI and when refreshing the Config Panel) since 2016 at least (maybe even older). Which version behaves differently as you mentioned?

**Comment by midwan** [comment] 2018-02-07 21:08
Note: this is caused by the routine that opens each config file found to fetch the Description.
If we have thousands of configs, it takes a long time to go through all of them.

Possible solution: Disable Description fetching as an option (defaulting to OFF, I believe most people don't have thousands of config files there?). That should be saved outside the emulator, perhaps in `adfdir.conf`

**Comment by midwan** [comment] 2018-02-07 21:41
New option added in `adfdir.conf`: `read_config_descriptions`

It accepts a string value of either `yes` or `no` and controls the automatic loading of the config's Description which requires opening the file (and it's an expensive operation).

Example configuration:
`read_config_descriptions=no` - This will **disable** automatic loading of config Descriptions
`read_config_descriptions=yes` - This is the default value, which **enables** automatic loading of Descriptions.

The above line will be added as the last line in the `adfdir.conf` file, after everything else. 
- If it doesn't exist in the file, it will be added as soon as the emulator regenerates it (when closing Amiberry). 
- If it's already there, it will be read on startup and the emulator will adapt the functionality on the fly.

For now, there's no option in the GUI that controls this - if there's a demand, we can add that as a checkbox somewhere as well. Since this seems like an edge case, I think it may not be necessary to add (perhaps just editing the file is enough).

This will be committed in the `dev` branch for now, and will be merged back to `master` along with the rest of the fixes soon.

@ransom1122 
If you'd like to test it, you'll need to compile the `dev` from source after this is committed! :)

**Closed** 2018-02-07 21:44 UTC
Labels: bug

**Comment by ransom1122** [comment] 2018-02-07 22:15
I dont recall the last version. It would have been the latest version prior v2.12.

I have updated my image to v2.12 now, cannot re test it.. i do recall I was able to use gui without wait times.. oftenly saving cpnfigs via the gui to the /amiga folder without this wait time whilst all configs were shown in the gui.
