### ISSUE TITLE
Sorting devices and modes...

### ISSUE THREAD

**Issue by Gerbinist** [midwan/amiberry#775] opened 2021-02-28 12:01 UTC
- Raspberry Pi 400
- Raspberry Pi OS
- Linux PI400 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux
- DispmanX

My WB is configured to use a screenmode of 960x540. As mentioned in the [comment from bug #773](https://github.com/midwan/amiberry/issues/773#issuecomment-786477972) sometimes my WB starts up with a PAL screen. When this happens, I'm seeing the following in the log file:
```
Amiberry BETA (2021-02-27) Logfile

Allocated 16 MB for 24-bit area (0x20000000) and 1152 MB for Z3 and RTG at real address (0x60000000 - 0xa8000020)
Sorting devices and modes...
0: !640x400, 8-bit (50,!60)
1: !640x400, 16-bit (50,!60)
2: !640x400, 32-bit (50,60)
3: 640x480, 8-bit (50,60)
4: !640x480, 16-bit (50i,60)
5: !640x480, 32-bit (!50,60)
6: !720x400, 8-bit (50,60)
7: !720x400, 16-bit (!50i,60)
8: !720x400, 32-bit (50,60)
9: !800x480, 8-bit (!50,60)
10: !800x480, 16-bit (50,60i)
11: !800x480, 32-bit (50,!60)
12: !800x600, 8-bit (!50,60)
13: !800x600, 16-bit (!50i,60)
14: !800x600, 32-bit (50,60)
15: !960x540, 8-bit (50i,60)
16: !960x540, 16-bit (!50i,60)
17: !960x540, 32-bit (50,!60i)
18: 1024x768, 8-bit (50i,60)
19: 1024x768, 16-bit (50,60)
20: 1024x768, 32-bit (50,60)
21: 1280x720, 8-bit (50,60)
22: 1280x720, 16-bit (50,60)
23: 1280x720, 32-bit (50,60)
24: 1280x800, 8-bit (50,60)
25: 1280x800, 16-bit (50,60)
26: 1280x800, 32-bit (50,60)
27: 1280x1024, 8-bit (50,60)
28: 1280x1024, 16-bit (50,60)
29: 1280x1024, 32-bit (50,60)
30: 1360x768, 8-bit (50,60)
31: 1360x768, 16-bit (50,60)
32: 1360x768, 32-bit (50,60)
33: !1366x768, 8-bit (50,60)
34: 1366x768, 16-bit (50,60)
35: 1366x768, 32-bit (50,60)
36: 1680x1050, 8-bit (50,60)
37: 1680x1050, 16-bit (50,60)
38: 1680x1050, 32-bit (50,60)
39: 1920x1080, 8-bit (50,60)
40: 1920x1080, 16-bit (50,60)
41: 1920x1080, 32-bit (50,60)
42 display modes.
```

This results in the following modes a bit further down the road:

```
uaegfx.card magic code: 00F03800-00F03952 BI=4016840C
 1: 50001000  320x 200 UAE: 320x 200
 2: 50011000  320x 240 UAE: 320x 240
 3: 50091000  320x 256 UAE: 320x 256
 4: 50031000  640x 480 UAE: 640x 480
 5: 500A1000  640x 512 UAE: 640x 512
 6: 50051000 1024x 768 UAE:1024x 768
 7: 508E1000 1280x 720 UAE:1280x 720
 8: 50901000 1280x 800 UAE:1280x 800
 9: 50071000 1280x1024 UAE:1280x1024
10: 50A11000 1360x 768 UAE:1360x 768
11: 50931000 1366x 768 UAE:1366x 768
12: 50971000 1680x1050 UAE:1680x1050
13: 50981000 1920x1080 UAE:1920x1080
SetSwitch() - amiga. Monitor=0
```

When I restart and it successfully starts up a 960x540 RTG WB screen, I'm seeing:

```
Amiberry BETA (2021-02-27) Logfile

Allocated 16 MB for 24-bit area (0x20000000) and 1152 MB for Z3 and RTG at real address (0x60000000 - 0xa8000020)
Sorting devices and modes...
0: !640x400, 8-bit (!50,60)
1: !640x400, 16-bit (50i,60)
2: !640x400, 32-bit (50,60)
3: !640x480, 8-bit (!50i,60)
4: !640x480, 16-bit (!50i,60)
5: !640x480, 32-bit (!50,60)
6: !720x400, 8-bit (!50i,60)
7: !720x400, 16-bit (50,60)
8: !720x400, 32-bit (!50,60)
9: !800x480, 8-bit (50i,60)
10: !800x480, 16-bit (50,!60)
11: !800x480, 32-bit (!50,60)
12: 800x600, 8-bit (!50,60)
13: !800x600, 16-bit (50,!60)
14: 800x600, 32-bit (!50,60)
15: 960x540, 8-bit (50,60)
16: 960x540, 16-bit (50,60)
17: 960x540, 32-bit (50,60)
18: 1024x768, 8-bit (50,60)
19: 1024x768, 16-bit (50,60)
20: 1024x768, 32-bit (50,60)
21: 1280x720, 8-bit (50,60)
22: 1280x720, 16-bit (50,60)
23: 1280x720, 32-bit (50,60)
24: 1280x800, 8-bit (50,60)
25: 1280x800, 16-bit (50,60)
26: 1280x800, 32-bit (50,60)
27: 1280x1024, 8-bit (50,60)
28: 1280x1024, 16-bit (50,60)
29: 1280x1024, 32-bit (50,60)
30: 1360x768, 8-bit (50,60)
31: 1360x768, 16-bit (50,60)
32: 1360x768, 32-bit (50,60)
33: 1366x768, 8-bit (50,60)
34: 1366x768, 16-bit (50,60)
35: 1366x768, 32-bit (50,60)
36: 1680x1050, 8-bit (50,60)
37: 1680x1050, 16-bit (50,60)
38: 1680x1050, 32-bit (50,60)
39: 1920x1080, 8-bit (50,60)
40: 1920x1080, 16-bit (50,60)
41: 1920x1080, 32-bit (50,60)
42 display modes.
```

And a bit further:

```
uaegfx.card magic code: 00F03800-00F03952 BI=40169874
 1: 50001000  320x 200 UAE: 320x 200
 2: 50011000  320x 240 UAE: 320x 240
 3: 50091000  320x 256 UAE: 320x 256
 4: 500A1000  640x 512 UAE: 640x 512
 5: 50041000  800x 600 UAE: 800x 600
P96: Non-unique mode 960x540
 6: 50FF1000  960x 540 UAE: 960x 540
 7: 50051000 1024x 768 UAE:1024x 768
 8: 508E1000 1280x 720 UAE:1280x 720
 9: 50901000 1280x 800 UAE:1280x 800
10: 50071000 1280x1024 UAE:1280x1024
11: 50A11000 1360x 768 UAE:1360x 768
12: 50931000 1366x 768 UAE:1366x 768
13: 50971000 1680x1050 UAE:1680x1050
14: 50981000 1920x1080 UAE:1920x1080
SetSwitch() - amiga. Monitor=0
```

This happens in a hit & miss scenario. It 'usually' ends up with the RTG screenmode in mind. 'Sometimes' it doesn't work and my WB boots in a PAL mode.

**Comment by ninjaweb62** [comment] 2021-02-28 13:02
Something similar happens here with latest devs. Every time I reboot the Pi 3, inside emulation I found different uaegfx screen modes available inside ScreenMode. While all PAL screen modes are always there, a few UAE screenmodes ramdomly appear and disappear . A few of higher screenmodes (from 720x400 up to 1920x1080) very often are missing, sometimes I found one or more of them, others times a few of them are not available. At every PI reboot the list changes. So, AMIGA sometimes boot with the selected UAEGFX screenmode, others with the default 4 colors PAL mode because the one selected has diappeared...

**Comment by midwan** [comment] 2021-03-01 16:44
The first list of screenmodes is always the same when using Dispmanx. It's actually checked on the system/monitor you have, only when using the non-Dispmanx versions of Amiberry, so I don't think that part is related.

The second part of the log you provided, seems to be the modes included in the Monitor driver loaded in AmigaOS, if I'm not mistaken. Those are the modes you have available in ScreenMode prefs as well, since it's going to use whatever was configured in the Monitor driver file for that. Those are normally edited with PVS or Picasso96Mode, which saves the changes back to the monitor file.

I'm not sure what is causing this behavior in your system, but I would suggest you check that monitor file first, and possibly your startup-sequence (if it's non-standard), while finally also checking the sd card for any read access issues?

Nobody else has reported such a problem so far...

**Comment by Gerbinist** [comment] 2021-03-01 17:00
> The first list of screenmodes is always the same when using Dispmanx. It's actually checked on the system/monitor you have, only when using the non-Dispmanx versions of Amiberry, so I don't think that part is related.

No, that is incorrect. When you look closely to the logs I provided, the first time there is a "!" in front of 960x540. After restarting Amiberry it doesn't display this "!" in front of the screenmode and then it appears to be working correctly.

> The second part of the log you provided, seems to be the modes included in the Monitor driver loaded in AmigaOS, if I'm not mistaken. Those are the modes you have available in ScreenMode prefs as well, since it's going to use whatever was configured in the Monitor driver file for that. Those are normally edited with PVS or Picasso96Mode, which saves the changes back to the monitor file.

I don't think the OS plays a role here (yet). It looks like the modes that have a ! in front of them during 'Sorting devices and modes...' will not be available to the OS in a later stage.

> Nobody else has reported such a problem so far...

This might be related to the fact I'm not using a 'standard' resolution. I have never seen a ! in front of modes > 1024x768 for instance. However the additional remark from ninjaweb62 seems to point exactly to the same issue.

**Comment by ninjaweb62** [comment] 2021-03-01 20:45
Here are the 3 example logs of what is happening with the latest dev (just to confirm the problem is real).
I use latest RaspiOS lite which boot directly Amiberry.
log1: pi booted for the first time
log2: after closing amiberry and restarting it again (without rebooting)
log3: after a pi reboot
It is obvious that every time the lines regarding the screenmodes somewhat changes !!!
[amiberry1.log](https://github.com/midwan/amiberry/files/6064360/amiberry1.log)
[amiberry2.log](https://github.com/midwan/amiberry/files/6064361/amiberry2.log)
[amiberry3.log](https://github.com/midwan/amiberry/files/6064362/amiberry3.log)

**Comment by midwan** [comment] 2021-03-03 14:15
This seems to be a bug indeed, in the Dispmanx version.
Some DisplayModes fields do not get initialized, so they get random memory values on each run...

Please check with the latest commit above and see if it works better for you?

**Comment by Gerbinist** [comment] 2021-03-03 14:56
Yes! Started it around 10 times. Not once a "!" appeared in front of the screenmodes at the start of the log and all screenmodes were available all the time 👍

**Comment by ninjaweb62** [comment] 2021-03-03 16:33
Confirmed. It works perfectly now!!!  👍
Thanks.

**Comment by midwan** [comment] 2021-03-03 17:33
Thank you for confirming!

**Closed by midwan** 2021-03-03 17:33 UTC
Labels: bug, fixed in dev, question
