### ISSUE TITLE
Amiberry does not recognise retroarch.cfg for IPAC (keyboard encoder)

### ISSUE THREAD

**Issue by tukicat** [midwan/amiberry#207] opened 2018-01-14 11:40 UTC
I have compiled the dev version (SDL1) from the source and have it running on my retropie setup. However, one issue I am having is with the controls. I have placed a retroarch.cfg (attached) in the following directory - /opt/retropie/configs/amiga/amiberry/conf/. However, when I run Amiberry and select "Retroarch Keyboard as Joystick" there is no response from the joystick or buttons. 

Raspberry Pi 3
Retropie 4.3
IPAC keyboard encoder. 

###Expected behavior

Amiberry recognises "retroarch.cfg" and allows custom controller mapping. 

### Actual behavior
Amiberry custom controls tab states "Not a Valid Input Controller for Joystick Emulation" and all the custom keys are greyed out.

### Steps to reproduce the behavior

Place the attached "retroarch.cfg" in the /opt/retropie/configs/amiga/amiberry/conf/ directory and run Amiberry, select control input as "Retroarch Keyboard as Joystick". Check custom controls.

[retroarch.zip](https://github.com/midwan/amiberry/files/1629285/retroarch.zip)

**Comment by blinkydoos** [comment] 2018-01-14 11:55
This may be due to this issue I reported https://github.com/midwan/amiberry/issues/199

**Comment by midwan** [comment] 2018-01-14 11:57
@blinkydoos that issue is about the fire buttons only though, the directional do work...
If I understand this issue correctly, none of the controls work?

**Comment by tukicat** [comment] 2018-01-14 12:37
I have retested and I can confirm the the directional buttons do work, just not the firebutton. However, input_player1_x = "space" appears to be working as fire button one on my setup. 

As I understant a "r" should appear next to the controller description under the custom controls menu, which indicates the retroarch config is being used. This is blank on my setup which I assumes means it is not recognising the retroarch.cfg properly. Before I placed my retroarch.cfg in /opt/retropie/configs/amiga/amiberry/conf/ Amiberry stated "Keyboard as Joystick (Default)" but after I put retroarch.cfg into /opt/retropie/configs/amiga/amiberry/conf/ it recognised it as "Retroarch Keyboard as Joystick"  so it recognising the retroarch.cfg file, but not allowing me to use the custom controls..

**Comment by midwan** [comment] 2018-01-14 12:39
@tukicat thanks for confirming, in that case it seems it's the same bug as mentioned in #199.
This will be fixed shortly I hope. :)

**Comment by tukicat** [comment] 2018-01-14 12:56
No, problem and thanks, that's good to hear.

**Comment by HoraceAndTheSpider** [comment] 2018-01-14 13:53
FYI custom remapping currently does not support keyboard controls as joystick - planned for future release

**Comment by HoraceAndTheSpider** [comment] 2018-01-14 13:54
It will  Not operate as a normal joystick/cd32 controller at the moment

**Comment by m3chstaa** [comment] 2018-02-15 03:40
I hope this helps but I've had problems getting amiberry to read my retroarch controller config and it took me a while to sort this. I found that amiberry looked for my controller config in all/retroarch/autoconfig and for some reason wasn't reading it (I could see it was there and even verified that the filename was the same as the controller name in Amiberry).  on a hunch i loaded up retroarch from retropie menu and went through my controller joystick and buttons again and then chose the option "save autoconfig". Lo and behold I go to Amiberry and I get the magic "R" next to my controller! Just to do a little more digging I went back to autoconfig folder and found a new file there with what looked like an identical filename. This new file, however, has a space at the end of the it! So yeah.. don't normally post in places like this but I hope it helps someone from the headaches I had from getting this to work. Got WHDLoad amiga games working like a dream on a two player arcade system (Dragonrise Generic USB Joystick x 2). Controllers work for both players AND I can quit out by using Select/Start combination. PERFECTION. Thank you Amiberry people, ETA Prime, HoraceAndTheSpider for your fantastic work!

**Comment by Edo75** [comment] 2018-02-17 01:29
I clearly see "Retroarch Keyboard as Joystick" but the firebutton doesn't work what's so ever on my setup (Retropie 4.3, IPAC) even with input_player1_x = "space". I guess I must wait for the planned custom remapping.

**Comment by HoraceAndTheSpider** [comment] 2018-02-17 09:12
Hi @Edo75

The feature you refer to *is* the custom remapping. There is not much planned here other than adding support for players 2-4.

Input_player1_x would in fact be the “yellow” button on CD32 mode and not fire.

Please check that the button you have for Input_player1_b performs the standard Amiga fire control. If that still does not work I will look into it further. 

There is a picture on the Wiki page that shows how the retroarch nameinf (b ,a , x , y etc) lines up with the Amiga controls.

**Comment by HoraceAndTheSpider** [comment] 2018-02-17 09:19
I should add that if you wish to use a layout that has a different positioning , you can create a second retroarch.cfg file inside your Amiberry folder and use say “space” as the “b” button rather than “y” so that the layout is used by Amiberry only.

(You would also need to change the option in the paths panel for the location of this)


Hope that helps

**Comment by cesarpuig** [comment] 2018-02-18 22:32
Hello, and sorry for my English.

I have a similar problem:

I do not work well with the trigger buttons or the cursors.

My configuration is:

Retropie 4.3.11
Amiberry 2.14
Ipac keyboard encoder

Imput: Retroarch keyboard as joystick

**Comment by HoraceAndTheSpider** [comment] 2018-02-18 22:58
Trigger buttons are not supported.


Please post your retroarch.cfg file and explain further the behaviour of what is not working , what you are doing, how it is expected to work etc.


This thread is really about Custom remapping which currently does not exist for these controller types.

**Comment by cesarpuig** [comment] 2018-02-19 21:08
Hello, first of all thank you very much.

I enclose the retroarch configuration and an uae file if necessary.

Basically the problem that I have is that it does not recognize me the right, left and down direction, but it does recognize up

The buttons I'm not sure because I do not know the system very well.

A greeting.

[Retroarch+uae.zip](https://github.com/midwan/amiberry/files/1738131/Retroarch.uae.zip)

**Comment by ZappaUtopia** [comment] 2018-02-22 17:07
What config file is needed to make 'Keyboard as Joystick' work ? I have a keyboard that works as a keyboard in other emulators and Amiberry but when selecting 'Keyboard as Joystick' only Keyboard Up works as Gamepad Up, no other buttons work. The custom section says 'not a valid controller'. The keyboard used to work fine as a controller in previous versions.

**Comment by HoraceAndTheSpider** [comment] 2018-02-22 17:59
it should work with a retroarch.cfg file alone. 

I will investigate more, as it certianly worked in previous revisions. The custom section will always say that for keyboard controllers at the moment though

**Comment by ferra1980** [comment] 2018-03-19 10:41
Hi all, there are some news here?

**Comment by midwan** [comment] 2018-03-28 07:40
@ferra1980 
It's a bit hard for me to test this, as I don't have a relevant controller.
@HoraceAndTheSpider any luck with this? Anything I can do to help?

**Comment by RINNAA** [comment] 2018-03-28 09:36
Hi !
To test a Keyboard as a Joystick it is not necessary to have a JPAC or iPAC interface, just install retrogame that simulates the keyboard using GPIO pin:

https://github.com/adafruit/Adafruit-Retrogame

Alternatively, the keyboard can be used directly. The JPAC / iPAC / GPIO with retrogame do nothing but simulate the pressure of a key.

I use this file configuration for retrogame.

My question is: is possible to make a retrogame.cfg to use in amiberry, that use this keyboard controls ?

LEFT 27 # left - P1
RIGHT 22 # right - P1
UP 4 # up - P1
DOWN 17 # down - P1
LEFTALT 24 # 'A' button 1 - P1
LEFTCTRL 25 # 'B' button 2 - P1
LEFTSHIFT 18 # 'Y' button 3 - P1
SPACE 15 # 'X' button 4 - P1
Z 14 # 'TL' button 5 - P1
X 23 # 'TR' button 6 - P1
1 10 # 'Start' button - P1
5 9 # 'Select' (Coin) button - P1
D 6 # left - P2
G 13 # right - P2
R 11 # up - P2
F 5 # down - P2
S 20 # 'A' button 1 - P2
A 21 # 'B' button 2 - P2
W 12 # 'Y' button 3 - P2
Q 7 # 'X' button 4 - P2
I 8 # 'TL' button 5 - P2
K 16 # 'TR' button 6 - P2
2 19 # 'Start' button - P2
ENTER 26 # 'Select' (Enter) button
ESC 9 10 # Hold Start P1 + Coin to exit ROM

**Comment by HoraceAndTheSpider** [comment] 2018-03-28 12:33
Why would Retro game perform any differently to just using a normal keyboard? 

The RetroPie setup script (from what I have seen recently) seems to possibly duplicate the retroarch.cfg file rather than symlink to the original.

It might be worth checking the retroarch.cfg path in the paths panel and being 100% sure the right file is available and being modified.


Screenshots would help here.

**Comment by RINNAA** [comment] 2018-03-28 12:59
Yes to test the "Keyboard as a Yoistick" normal Keyboard is enough.

Retrogame is usefull to use GPIO pin to external controls.

R.

**Comment by cesarpuig** [comment] 2018-03-28 13:21
Hi. I have tested with an IPAC-2 and a keyboard, and it does not work in either case.
Retropie links the file Retroarch.cfg, I have tried to delete the link and place the file Retroarch.cfg in the same address and it does not work either.

a greeting

**Comment by cesarpuig** [comment] 2018-05-08 20:42
Hello....

In the current version of Amiberry 2.20 and Retropie 4.3.17, the Retroarch controls with IPAC 2 work well for me.

The only problem is the controls that are configured by default.

For example, in all the games by default, the following controls are configured:
![img_20180508_222923](https://user-images.githubusercontent.com/30637939/39781759-69c46fb0-5310-11e8-880a-e6d411215d88.jpg)

When for example I would like them to be like this:
![img_20180508_222942](https://user-images.githubusercontent.com/30637939/39781841-9e876400-5310-11e8-916a-9afdf566053c.jpg)

In the current version could you customize the controls individually for each game? How?

Thank you

**Comment by HoraceAndTheSpider** [comment] 2018-05-08 21:02
Is this using the WHDLoad booter?  

If so, you simply need to change the `hostprefs.conf` file to have `controller_1=joy0`

**Comment by cesarpuig** [comment] 2018-05-09 06:27
Hi.

Yes, I use WHDLoad booter.

I try to modify the hostprefs.conf file, and comment.

Thank you very much.

**Comment by cesarpuig** [comment] 2018-05-09 13:46
Hi.

I have modified the file hostprefs.conf, currently it is like this:

CONTROLLER_1 = joy0
CONTROLLER_2 = joy1
; CONTROLLER_3 = joy2
; CONTROLLER_4 =
CONTROLLER_MOUSE_1 = joy1
; CONTROLLER_MOUSE_2 = joy2
; RETROARCH_QUIT = TRUE
; RETROARCH_MENU = TRUE
; RETROARCH_RESET = TRUE
; KEY_FOR_QUIT = F12
; KEY_FOR_MENU = F11
; DEADZONE =
STEREO_SPLIT = 1
; SOUND_ON = FALSE
; ASPECT_RATIO_FIX = TRUE
; FRAMESKIP = TRUE

With this I have achieved that the default control is Port 1, as shown in the image:

![img_20180509_153315](https://user-images.githubusercontent.com/30637939/39817743-4737fa4a-539f-11e8-9fc1-974466dbe750.jpg)

But to get specify the type of Joystick, I had to modify the file whdload_db.xml, in this case, the original file was this:

<game filename="Benefactor_v1.1_CD32"  sha1="85346619207728e9627d929365bae60a56cef5ab">
		<name>Benefactor [CD32]</name>
		<slave_count>1</slave_count>
		<slave_default>BenefactorCD32.Slave</slave_default>
		<hardware>
PRIMARY_CONTROL=JOYSTICK
PORT0=JOY
PORT1=JOY
JIT=FALSE
SCREEN_HEIGHT=256
SCREEN_Y_OFFSET=3
		</hardware>
		<custom_controls>

		</custom_controls>
	</game>


And the modification the following:

<game filename="Benefactor_v1.1_CD32"  sha1="85346619207728e9627d929365bae60a56cef5ab">
		<name>Benefactor [CD32]</name>
		<slave_count>1</slave_count>
		<slave_default>BenefactorCD32.Slave</slave_default>
		<hardware>
PRIMARY_CONTROL=JOYSTICK
PORT0=JOY
PORT1=CD32
JIT=FALSE
SCREEN_HEIGHT=256
SCREEN_Y_OFFSET=3
		</hardware>
		<custom_controls>

		</custom_controls>
	</game>

The result obtained has been the desired one:

![img_20180509_153328](https://user-images.githubusercontent.com/30637939/39817964-f7c64d58-539f-11e8-83b5-dca2f1437f23.jpg)

Is it the correct way to configure the controls?

**Comment by HoraceAndTheSpider** [comment] 2018-05-09 19:39
Yes, the type of control needs specifying in the XML - a lot are picked up but some are not (yet)

This will be fixed when the Online Database is produced.

**Comment by cesarpuig** [comment] 2018-05-19 14:18
@Edo75 
Only the retroarch controls work for me executing the games in lha format, not if I execute them from an uae file, and I can not reconfigure them from amiberry

**Comment by Edo75** [comment] 2018-05-19 17:19
Excuse me but I'm feeling like a novice. I can't read lha files, must I install WHDLoad booter manually? I can't see it in the Amiberry folders.
 
![screenshot_1](https://user-images.githubusercontent.com/28062697/40271154-86f58fce-5b99-11e8-9686-3a7bdbcc4e74.png)

**Comment by HoraceAndTheSpider** [comment] 2018-05-20 21:04
You need version 2.21 to use a DragonRise controller.

Either by compiling the development branch, or waiting for a release to happen.

The WHDLoad booter is included in the full download package. If you are installing from RetroPie you will need to update scripts and compile from source. This will only bring you up to v2.20 however..

**Comment by Edo75** [comment] 2018-05-25 23:58
I will make some additional tests but, for me personally, the issue didn't move an inch even after the 2.21, the only working input is the up direction. Also, no a trace of the WHDLoad booter, even after update scripts and compile from source. At that point, I will eventually reinstall Retropie totally from scratch to be sure I tried everything (Ipac, Retropie 4.3)

**Comment by HoraceAndTheSpider** [comment] 2018-05-26 06:51
There hasn’t been any work done on the ipac/retroarch solution.

I really need someone to donate/lend on of these things though as I cannot reproduce it properly with a regular keyboard.

Also I could check that RetroPie has made an actual symlink in /configs/ to retroarch.cfg as to me it looked like it had copied in a duplicate file

**Comment by Edo75** [comment] 2018-05-26 10:38
Hi,
I already removed the symlink and replaced it with a new retroarch.cfg but it doesn't fix the issue. If all you want is an Ipac to work on it, just give me your postal address at edouard.aronson@gmail.com. It's the least I can do.

**Comment by midwan** [comment] 2018-05-26 15:58
OK, reopening this one then.

**Comment by Marcoqwerty78** [comment] 2018-05-27 13:33
@Edo75 Can i confirm the issue of "only UP and fire"; my setups is also with IPAC and true keyboard

PS:
I have some issue to exit emulator, can some explain me better how to configure them?

Config + UAE attached (Rick Dangerous Demo)
[Config+Uae.zip](https://github.com/midwan/amiberry/files/2042665/Config.Uae.zip)

**Comment by cesarpuig** [comment] 2018-05-28 13:41
Hello

As of version 2.20, it works well with I-PAC2, using WHDLoad booter, and game data in .lha.

The only problem is that in the Custon Controls window I see not at valid imput for joystick emulation.

I do not know if it will help.

**Comment by Marcoqwerty78** [comment] 2018-05-28 14:03
Thank you @cesarpuig !!
Ho can i downgrade Amiberry to 2.20 ? also...can you help me a bit how to try the WHDLoader booter with .lha (maybe a string to launch it directly from the cmd, after i will try to put all on Attract-Mode)?

**Comment by cesarpuig** [comment] 2018-05-28 20:31
Hi. @Marcoqwerty78 @Edo75 

Update Retropie and amiberry to the latest version, I have tested it with Retropie 4.3.17-Amiberry 2.20 and Retropie 4.4.1-Amiberry 2.21, and with both combinations it works for me, but only by launching the games directly from a * .lha file.

Use the guide on this page:
http://www.ultimateamiga.co.uk/HostedProjects/RetroPieAmiga/guide.html

Then the way to configure the controls individually for each game is in this same thread a little above.

If I can help in something say it.

a greeting

**Comment by Marcoqwerty78** [comment] 2018-05-30 22:53
Sorry @cesarpuig  to bother you again ( i bother a lot of people on these days)

But now im stuck to a black screen after the correct loading of the whdloader, i see the logo, found the slave and creating files...but black screen. ( i test with AnotherWorld_v2.4_It.lha i think is playable!)

before i had some issue to generate the symlinks files, at the end i copied the files from  **Devs:Kickstarts.**  to  **save-data/Kickstarts**, and now looks working ( i get only an erro of SETPATCH NOT FOUND but i have read it is not relevant)

But i'm blocked to this black screen (can you porvide me a name of a working game? to some extra tests)

Thank you again!

**Comment by cesarpuig** [comment] 2018-06-01 13:11
Hello @Marcoqwerty78 


This is my email address: cesarpuig80@gmail.com, write me here because if we do not deviate from the main topic of the thread and I will help you in everything I can

**Comment by midwan** [comment] 2020-06-09 20:29
@HoraceAndTheSpider 
Did we make any progress with this case?

**Closed** 2020-10-07 07:31 UTC
Labels: enhancement
