### ISSUE TITLE
Amiberry 3.0 ps4 Bluetooth 

### ISSUE THREAD

**Issue by Simberg901** [midwan/amiberry#541] opened 2019-11-25 13:21 UTC
**Describe the bug**
Retropie 4.5 latest
Pi3b+
amiberry v 3. 0 latest
Advised on retropie forum to post here. 

When ps4 Bluetooth controller connected amiberry does not open or any games just goes straight back to emulationstation. 

If disconnect ps4 controller and connect xbox 360 wired or wireless amiberry loads. 

I can reproduce this error every time I connect ps4 controller. 

Ps4 controller works on all other emulators. 

And on previous amiberry versions ps4 controller worked fine via Bluetooth. 

I've tried several times restarting system, removing all Bluetooth devices and just adding ps4 controller test on all emulators and works but soon as test amiberry it won't launch. 

Disconnect ps4 controller then start amiberry using other controller and loads fine.

**Comment by midwan** [comment] 2019-11-25 14:52
Thanks for reporting this.
It seems to be a duplicate of #481 actually, so let's keep one of the two issues open.

**Closed by midwan** 2019-11-25 14:52 UTC
Labels: duplicate
