### ISSUE TITLE
UAEQuit fails to quit the emulator

### ISSUE THREAD

**Issue by vanfanel** [midwan/amiberry#165] opened 2017-12-17 14:19 UTC
Hi

UAEquit is a "classic" program used to exit the emulator from within the emulated machine.
It's freely available here:
http://aminet.net/package/misc/emu/UAEquit

It's very useful for non-keyboard setups.
It's supposed to be able to quit the emulator back to the host OS, and so does it with fs-uae, uae, etc...
However, on amiberry it leaves the emulation in an unusable state until you press ENTER, then the emulation is restarted with the latest configuration you loaded.

I have also noticed that trying to exit after passing a config file:
./amiberry myconfig.uae
...results on the emulator to re-enter instead of quitting. May be related.

**Comment by midwan** [comment] 2017-12-17 19:46
This is a duplicate of #159, so I'm copying relevant info from here to that and closing this...

**Closed by midwan** 2017-12-17 19:46 UTC
