### ISSUE TITLE
Default controller blank for every game in retropie

### ISSUE THREAD

**Issue by Shawson** [midwan/amiberry#302] opened 2018-04-12 09:28 UTC
### Expected behavior
Loading a new whdload game would inherit the emulator defaults and stick my petrockblock controlblock controllers in for joystick 1/2

### Actual behavior
Every new game I load, these fields are blank

### Steps to reproduce the behavior
Pick any lha file, and start it up.  I then have to hit f12 and assign the controllers.  This may not be a bug- perhaps user error?  Is there a way to set this globally?  Also not sure if I'm saving these settings- I set the controllers but then how do I actually save the change?  Being lha whd games, theres no uae file for it to save to, and no save settings button that I could find?  (Once the controllers are setup though, games run perfectly!)

**Comment by midwan** [comment] 2018-04-12 15:53
This looks like a dupe of #300

**Closed** 2018-04-12 20:24 UTC
