### ISSUE TITLE
Building from source fails on RetroPie (Raspberry Pi 3)

### ISSUE THREAD

**Issue by 2xtime** [midwan/amiberry#384] opened 2018-12-02 14:07 UTC
Building from source using Retropie fails. Any ideas ? Log attached.
[rps_2018-12-02_140304.log.gz](https://github.com/midwan/amiberry/files/2636988/rps_2018-12-02_140304.log.gz)

Do I have to build from source manually ?

**Comment by midwan** [comment] 2018-12-02 15:40
The logs indicate that a requirement is missing from your installation (the SDL headers in this case).
Attempting to build from source manually should also result in the same error, if the files are missing.

Try removing the package and re-installing it from source, using RetroPie's tooling. It should have installed the required dependencies first anyway, but perhaps doing it this way would fix it?

**Comment by midwan** [comment] 2018-12-02 16:14
Actually, building manually from source seems to work for me.
This seems like a problem in RetroPie's script then - it should be reported there I believe.

**Comment by 2xtime** [comment] 2018-12-02 16:16
I uninstalled Amiberry from the Retropie setup menu and then tried updating from source but got the same error. I updated from binary and it worked fine. I wonder what's preventing it from seeing SDL ?

Earlier today I updated the Raspian firmware etc. Maybe that's created problems !?

**Comment by 2xtime** [comment] 2018-12-02 16:17
I just saw your comment above mine ! I'll have to see what Retropie think.

**Comment by midwan** [comment] 2018-12-02 16:17
I don't think it has anything to do with the firmware, it may be related to the user running the process however. I think you're supposed to run `retropie_setup.sh` as root/sudo, right?

**Comment by midwan** [comment] 2018-12-02 16:18
I've confirmed the same with my RetroPie installation, after upgrading it to the latest RetroPie script.
Earlier versions worked fine, and this process has not changed in Amiberry's Makefile lately, so it's certainly something that has changed on RetroPie's side...

**Comment by midwan** [comment] 2018-12-02 16:19
and to clarify: if you drop to the console and attempt to build Amiberry manually (as the `pi` user), by cloning the repo, then running a `make -j2`, it works fine. No errors are reported about any missing `SDL.h` files.

**Comment by midwan** [comment] 2018-12-02 16:31
Actually, wait.

I found that there is a problem in the latest sources, that shows itself with SDL1. I tested the `dev` branch by mistake in my RetroPie installation earlier. Testing it with the latest from `master` showed the same error.

There is nothing wrong with RetroPie in that case, the issue is here. I'll get it fixed.

**Comment by 2xtime** [comment] 2018-12-02 16:32
Thanks mate !

**Comment by midwan** [comment] 2018-12-02 16:41
Fixed now, please update from source again and it should work for you.

**Closed** 2018-12-02 16:41 UTC
Labels: bug, question

**Comment by 2xtime** [comment] 2018-12-02 17:03
Works now, thanks.

There is a display issue on the 'Display' section. The scanlines options are on top of the Aspect Ratio option !
