### ISSUE TITLE
HDF size limit

### ISSUE THREAD

**Issue by windale** [midwan/amiberry#56] opened 2017-02-24 16:19 UTC
I haven't tested this myself, but a lot of people say that it only supports HDF's up to 1 GB in size. I have always used a 1 GB HDF formatted to PFS3 but it would be good if it supported larger harddrives with RDB as there is also a 5 HDF mount limit.

**Comment by midwan** [comment] 2017-02-24 16:58
Duplicate of #20

**Closed by midwan** 2017-02-24 16:58 UTC

**Comment by windale** [comment] 2017-02-24 17:02
Oops !
