### ISSUE TITLE
Joystick auto-configuration on Stretch OS RetroPie

### ISSUE THREAD

**Issue by dmmarti** [midwan/amiberry#300] opened 2018-04-10 13:02 UTC
### Expected behavior
With the recent pull request merged into Retropie, using the new amiberry (updated from source), launching a game should have the Joystick be auto-configured to whatever gamepad is already configured in RetroPie.

### Actual behavior
This functionality works as expected on Jessie based RetroPie.  However, on Stretch OS based RetroPie, the joystick is not being auto configured.  

Pressing F12 ... Inputs ... gamepads do show up as selectable and do work fine after selecting it.

### Steps to reproduce the behavior
These are the manual steps I took to test the new Amiberry updates on the Stretch OS beta image posted in the RetroPie forums.

1. download Stretch OS RetroPie beta and unzip
2. write image to SD card
3. bootup on Pi 3B+ board, configure gamepad, ssh, etc.
4. update setup script
5. install amiberry from source
6. copy over Amiga kickstarts
7. copy over Amiga LHA game file:      1943_v1.3.lha
8. restart Emulation Station
9. launch game

game loads straight into the game (so whdboot loader is working good) press F12 to get to Amiberry menu scroll down to “Input” ... no default selected for Joystick.

I can navigate to it, press enter, and see my list of choices to pick my F710 gamepad. Once selected, I click on “Resume” and the gamepad then works in the 1943 game.

**Comment by midwan** [comment] 2018-04-10 14:24
@dmmarti 
Thanks for reporting this.
I haven't yet tested RetroPie on Stretch, but on a standard Raspbian Stretch that I'm using daily, the default joystick detection works normally.

We'll have to test on RetroPie specifically, perhaps something there is problematic.

**Comment by ajefr** [comment] 2018-04-10 21:33
I too have this trouble, no joystick selected by default.
I can access config menu, affect one and it works.
But always uppon boot, field is blank

**Comment by Shawson** [comment] 2018-04-12 20:58
Ah yes- this is totally my problem also- I'm also on the stretch test image of retropie on a pi 3b+

**Comment by HoraceAndTheSpider** [comment] 2018-04-12 21:34
>>Just FYI, only autowhdload is impacted by this bug. UAE loading works great.

This is the strange thing , since it uses the same code for both.

**Comment by Shawson** [comment] 2018-04-13 11:48
Is there any logging or anything the app produces which I could submit that might assist?

**Comment by midwan** [comment] 2018-04-15 19:41
Added a fix with 63f1b84bb2ad054e47a67256404086037b14ab89

**Comment by HoraceAndTheSpider** [comment] 2018-04-15 19:48
Still testing some unexpected behaviour with the fix.

**Comment by ajefr** [comment] 2018-04-15 21:50
Just tried but got a black screen after amiberry logo.
While last built before 63f1b84 was loading fine (except controls)

**Comment by ajefr** [comment] 2018-04-16 21:39
Well, after many attempt, no whd games are starting since commit 63f1b84bb2ad054e47a67256404086037b14ab89
I always get a black screen after amiberry logo.
Reverting to commit 68290505187634b31b225bfb36a67bfb386b2fb6 make all games starts (same configuration, only replacing the executable)
Pushing button while starting makes no differences
Any clue ?

**Comment by HoraceAndTheSpider** [comment] 2018-04-16 22:32
You hold the fire button when and during the Amiberry logo? You get the WHDLoad booter appearing?

If not, your install is broken. If using RetroPie try building again from Source. 

Tested with a fresh Rp4.4 here and all working as expected.

**Comment by ajefr** [comment] 2018-04-17 05:16
I will try again but nothing were working.
Could we avoid this in the future ? (pressing button to start game).
I remember that on real hardware (A4000), I don't have to push any button to start a whd game.

**Comment by HoraceAndTheSpider** [comment] 2018-04-17 06:12
Pushing the button allows the auto startup file to be regenerated. This only has to happen once

However you’ve now mentioned that you are using another distro, so you probably want to check you have the booter files setup/configured correctly then.  Possibly your setup isn’t able to write to the save-data folder correctly. 

I suspect your problem comes from updating the binary without checking for the other folders that would be needed. 

On the a4000 you would be using Workbench to load first. If you prefer that method it can still be used.

**Comment by ajefr** [comment] 2018-04-17 16:49
Well, I may have found the (my) problem.
I'm using specific controller, and if in the controllers directory I don't have a file corresponding to this controller, I get black screen.
No matter what's inside the file, if not present, black screen. Even an empty file is enough to make game start.

**Comment by HoraceAndTheSpider** [comment] 2018-04-17 17:38
Can you explain when this is happening? Maybe post a video?

**Comment by jimi007** [comment] 2018-04-19 06:11
Hi 

I think I am having a similar issue. I am using an 8bitdo SF30 controller and am getting the black screen issue after the amiberry logo.
Where is the controllers directory?

**Comment by midwan** [comment] 2018-04-19 12:34
If you're running RetroPie, EmulationStation will ask you to configure your controller when you first start it up (if you haven't done so already). That mapping will be saved to disk, and it's that file that Amiberry will attempt to make use of as well.

If you don't have such a file, or if it doesn't match your current controller, it won't be picked up and the mapping won't work. However, I don't think the game should fail to start, so if that's happening we'll need to investigate (I haven't seen the issue myself, as it works for me).

**Comment by jimi007** [comment] 2018-04-19 23:43
I think I will investigate a bit more.
I have used a brand new Retropie 4.4 image  on Stretch and installed Amiberry from source. 
I have an 8bitdo controller but have only mapped the keyboard.
I cannot even see the autoboot file being created.
So I basically start the game from emulationstation and it goes black.
I might try and redo the image or add the controller mapping file and see what happens.

**Comment by midwan** [comment] 2018-04-20 17:00
Since the original post of this Issue is now resolved, I'm closing this.
We'll track the Black Screen problem in a separate issue here: #305

**Closed by midwan** 2018-04-20 17:00 UTC
Labels: bug
