### ISSUE TITLE
KMSDRM with Auto Height shows black screen

### ISSUE THREAD

**Issue by myzar** [midwan/amiberry#743] opened 2020-12-16 17:40 UTC
If i compile master with  make -j2 PLATFORM=rpi4-sdl2 , the compiled exe gives me a blackscreen with audio working, i can trigger the gui , the gui showsup, returning to the amiga still black screen with audio. I've tried with both kms and fkms vc4 drivers. 
Only the hybrid dispamax target works for me with fkms but i can't use fkms anymore so i need a pure sdl2 build 

RaspiOs Linux 5.4.79-v7l+ armv7l GNU/Linux

**Comment by midwan** [comment] 2020-12-17 00:45
@myzar 
Which back-end are you using?

If you run it under the desktop (X11 backend), does it work for you?

If you are launching it from the console, then you need the KMSDRM back-end. That unfortunately is not enabled in the SDL2 version supplied with RaspiOS - but it is on other distros, such as Manjaro.

**Comment by joolswills** [comment] 2020-12-17 02:38
I believe this user is on RetroPie btw from a thread I saw. I know the pure SDL2 Kms version used to work fine, but haven't tested in a while. I will also give it a try and report back

**Comment by joolswills** [comment] 2020-12-17 03:42
I could reproduce this using the default RetroPie config rp-500.uae which had been saved to within amiberry after tweaking settings. If I remove this and reinstall amiberry so it's a very minimal few settings in it, it works.

I will need to check which setting which was fine on fkms+dispmanx is causing the issue.

**Comment by joolswills** [comment] 2020-12-17 04:10
The issue is the auto height setting. If enabled I just get a black screen. Disabling it makes it work. I've seen this mentioned before and had a search - https://github.com/midwan/amiberry/issues/650

Issue is closed but I think the problem may be present. I can help reproduce if needed.

RetroPie latest with /boot/config.txt switched to use `dtoverlay=vc4-kms-v3d` / reboot

Install amiberry from source via RetroPie-Setup which will then build the pure sdl2 version.

And then launch an adf, and switch auto height on.

Can provide example config if useful.

**Comment by joolswills** [comment] 2020-12-17 04:17
RetroPie forum reference fyi https://retropie.org.uk/forum/topic/28834/amiberry-auto-height-causing-black-screen

**Comment by myzar** [comment] 2020-12-17 16:07
I confirm autoheight being the issue it's on by default in whdload_db.xml , there is also another settings which i changed and i forgot about that was causing the blackscreen always it's use_sdl2_render_thread=on

**Comment by midwan** [comment] 2020-12-17 16:14
@myzar 
the render thread can only work in back-ends that allow it - the X11 one for example.
It does not work in others, like KMSDRM. That's why it's an option :)

I'll check the auto-height in combination with KMSDRM, and get back.

**Comment by midwan** [comment] 2020-12-28 19:49
I can recreate this.

It seems to be related to the KMSDRM back-end, as there is no code difference in Amiberry regarding what back-end you're using (except Dispmanx, which is a special case). The same exact code for refreshing the screen works normally under the X11 back-end, but in KMSDRM it has glitches.

I also tested this with newer versions of SDL2 to see if it made any difference.
Here's what I found:

- RetroPie version: Amiberry starts, but GUI doesn't get drawn until an input event is triggered (e.g. move the mouse, press a key, or button).
- Newer version (Manjaro): Amiberry starts, GUI shows up normally.

This indicates that there is a difference/bug in the older SDL2 version and specifically, the KMSDRM back-end implementation on the RPI at least.

- RetroPie version: Select Quickstart->A1200, go to Display and enable Auto Height, start emulation. Black screen shows instead of the expected kickstart. Enter GUI with F12, and exit GUI again: The kickstart screen shows as expected.
- Newer version (Manjaro): same exact pattern/problem as above.

This indicates that there still is some kind of problem with the latest version of SDL2 and KMSDRM, since both versions behave the same.

I will see if I can find some kind of work around from Amiberry's side, to bypass this, and I will update this issue accordingly.
Thanks for reporting the problem! I don't normally test KMSDRM daily, and this was missed since it requires a combination of Auto Height to be enabled as well.

Keep in mind that you cannot use `use_sdl2_render_thread` with KMSDRM - that will always show you a black screen, because that back-end does not support threaded updates on the texture!

**Comment by midwan** [comment] 2020-12-28 22:27
OK, I found the source of this:

I have the line drawing routines running on a separate thread, to increase performance. When auto-height is turned on, at the end of that routine it will also change the display height. Since the call comes from the separate thread, I'm guessing KMSDRM goes bananas and doesn't update the screen, which remains black. Until a refresh is triggered elsewhere (e.g. by opening the GUI and closing it again), which would start a fresh redraw.

I'll see what I can do about this, without sacrificing performance if possible.

**Comment by midwan** [comment] 2020-12-29 00:43
35ab3921d284cab9138db9d0b9d0c57bf2593312 fixes this, with a workaround:

I've added a new option in `amiberry.conf`, which allows you to disable the drawing thread. You lose a few FPS (3-4 on a Pi3, shouldn't be any noticeable difference on a Pi4) but you can get it to work with KMSDRM this way. The option is enabled by default.

The new option name is `use_drawing_thread` and can be set to either `yes` or `no`. Similar to the SDL2 thread option, which should be set to `no` if using KMSDRM. At least until something changes with that back-end.

**Comment by myzar** [comment] 2020-12-30 00:13
the workaround works fine for me , i'm on rpi4 so i can't notice any notable difference

**Comment by midwan** [comment] 2020-12-30 00:40
@myzar 
Thanks for confirming!

**Closed** 2021-04-01 07:27 UTC
Labels: bug, fixed in dev
