### ISSUE TITLE
bluetooth gamepad not reconnecting

### ISSUE THREAD

**Issue by tednilsen** [midwan/amiberry#82] opened 2017-04-13 15:15 UTC
bluetooth gamepad isn't reconnecting when turned on again, so the user is forced to quit amiberry with keyboard / mouse and restarting amiberry again to use the gamepad.

**Comment by midwan** [comment] 2017-04-13 15:51
This will be a bit hard to troubleshoot as I don't have a bluetooth controller, but we'll see what we can do.

What type of controller are you testing it with? PS3/PS4?

**Comment by tednilsen** [comment] 2017-04-14 03:27
I have a G910, but fails with other gamepads too, I haven't tried xbox controller.
Works with no issues in RetroArch and more.

**Comment by HoraceAndTheSpider** [comment] 2017-04-14 06:57
This is duplicate of issue #52 I think and should be merged.

**Comment by midwan** [comment] 2017-04-14 10:30
@HoraceAndTheSpider indeed it is, thanks

@tednilsen this will be merged with #52

**Closed by midwan** 2017-04-14 10:30 UTC
Labels: bug
