### ISSUE TITLE
WHDLoad Turrican II

### ISSUE THREAD

**Issue by ukshark** [midwan/amiberry#103] opened 2017-05-05 06:06 UTC
Turrican 2 had glitches in the graphics so i changed gfx_framerate=0 and cachesize=0 which fixed the glitch, now it crashes after a few mins of play. 
Same problem every time, go left from start smash the hidden block above head far left.
Head right for 2 seconds and the game returns to menu.

This is on a Raspberry Pi 3, latest Retro Pi, Amiberry built from source Using RetroPi build script.

**Comment by GreenRebel** [comment] 2017-05-05 08:33
Same issue for me on Pi3 recently (2 weeks ago) built with latest retropie image and installed Amiberry from source option. Graphical artefacts were cured for me by unselecting JIT but the game crashes after performing exact same moves mentioned above.

**Comment by midwan** [comment] 2017-05-05 08:50
Thanks guys, I'll take a look and see if I can catch the crash with a debugger to see why it's happening

**Comment by ransom1122** [comment] 2017-05-05 09:28
Is it safe to say this game is not working at the moment?

**Comment by midwan** [comment] 2017-05-05 09:29
@ransom1122 
I didn't have time to test this yet, so I can say for sure. I hope to know more after the weekend, when I can spend some time on it.

**Comment by blinkydoos** [comment] 2017-05-05 11:47
I can also confirm the WHDLoad version crashes. I've noticed this on a few WHDLoad games that just crash the emulator. The ADF version of Turrican II works perfect.

**Comment by ransom1122** [comment] 2017-05-05 11:54
Agree. Adf works. But i will try and make whdload version work tomorrow


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: blinkydoos <notifications@github.com> Date: 5/5/17  9:47 pm  (GMT+10:00) To: midwan/amiberry <amiberry@noreply.github.com> Cc: ransom1122 <lenalouie01@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [midwan/amiberry] WHDLoad Turrican II (#103) 
I can also confirm the WHDLoad version crashes. I've noticed this on a few WHDLoad games that just crash the emulator. The ADF version of Turrican II works perfect.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/midwan/amiberry","title":"midwan/amiberry","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/midwan/amiberry"}},"updates":{"snippets":[{"icon":"PERSON","message":"@blinkydoos in #103: I can also confirm the WHDLoad version crashes. I've noticed this on a few WHDLoad games that just crash the emulator. The ADF version of Turrican II works perfect."}],"action":{"name":"View Issue","url":"https://github.com/midwan/amiberry/issues/103#issuecomment-299444458"}}}

**Comment by ransom1122** [comment] 2017-05-06 04:13
I figured it out gents, after messing with different configs until I found a working one. I have included working configs for both Turiican II & Turrican II Demo WHDLoad as both of these crash. 

On the other hand Turrican II CDTV Version seems to work without any modification of the config file.

[Turrican 2.TXT](https://github.com/midwan/amiberry/files/980672/Turrican.2.TXT)
[Turrican 2 (Demo).TXT](https://github.com/midwan/amiberry/files/980673/Turrican.2.Demo.TXT)

**Comment by blinkydoos** [comment] 2017-05-06 09:15
So what was the actually solution so people can add it to there own config file (and Midwan will know the cause of it) ? The emulator crash happens on some other games as well (one of the Alien Breed games on CD32 and First Samurai/Second Samurai). It also happens on SDL2.

**Comment by ransom1122** [comment] 2017-05-06 09:31
Cant remember Now, I think AGA was selected, and fast copper removed. There was another thing, but you can check the CFG I attached. its all in there. Game defenitly works though.

**Comment by midwan** [comment] 2017-05-06 09:33
Has anyone tried this on Amiberry-SDL2? There's a chance it might work directly there for example.

FYI: Fast Copper is a "dirty hack" and it has been removed in the SDL2 version altogether.

**Comment by blinkydoos** [comment] 2017-05-06 10:09
It happens in SDL2 as well, I did say in my post above :) What's strange is that the ADF version of Turrican 2 work fine on 68000 but if you change it to 68020 then it crashes the emulator in the same way as described.

@ransom1122 It was Alien Breed Tower Assault CD32 that I was thinking of but it doesn't crash, it just doesn't load.

**Comment by ransom1122** [comment] 2017-05-06 10:22
@blinkydoos Leave the cd32 stuff with me, I am in the process of testing every CD32 game .

**Comment by ransom1122** [comment] 2017-05-06 11:09
**Alien Breed - Tower Assault (1994)(Team 17)[!]** [ISO/CUE] - Works fine.  Intro & Ingame. Both Tower Assault & Alien Breed II Work fine.

**Alien Breed Tower Assault [CD32]** [WHDLoad Version] - Works after changing the cfg as mentioned above.

I have attached both working CFG Files

[Alien Breed - Tower Assault (1994)(Team 17)[!].txt](https://github.com/midwan/amiberry/files/980865/Alien.Breed.-.Tower.Assault.1994.Team.17.txt)
[Alien Breed Tower Assault [CD32].txt](https://github.com/midwan/amiberry/files/980867/Alien.Breed.Tower.Assault.CD32.txt)

**Comment by ransom1122** [comment] 2017-05-06 11:31
After a short config battle with WHDLoad versions of First Samurai & Second Samurai ECS & AGA, I can confirm they all work fine, Here are my working configs
[First Samurai.txt](https://github.com/midwan/amiberry/files/980876/First.Samurai.txt)
[Second Samurai.txt](https://github.com/midwan/amiberry/files/980877/Second.Samurai.txt)
[Second Samurai [AGA].txt](https://github.com/midwan/amiberry/files/980878/Second.Samurai.AGA.txt)

**Comment by blinkydoos** [comment] 2017-05-06 12:11
I'll write the actual solution so @midwan can quickly see the problem :) . You need to have '24-bit addressing' ticked and Turrican 2 WHDLoad works fine. If it's unticked then it crashes the emulator if you perform the steps listed in the OP. This also fixes First Samurai. So a problem with no 24-bit addressing ?

**Comment by ransom1122** [comment] 2017-05-07 00:13
It does seem '24-bit addressing' fixes a lot of issues. There are always other options that can change the outcome of a game which makes it trial and error really.

Looks like Flink CD32 may have issues emulating though, from glitchy graphics to stuttering audio. Fast Copper fixes the audio issue though, can't work out how to get a stable picture though?

**Comment by ukshark** [comment] 2017-05-07 11:39
Sorry even with brand new PI and amiberry install it still happens with your config.
This doesnt happen if I just use keyboard as controller, but always crashes the whole system if i use ANY controller (XBOX, USB, PS4, generic USB)

I cant get it to work using 68000 or 68020

**Comment by blinkydoos** [comment] 2017-05-07 12:33
It's best to use your own config as the ones Ransom posted have the games and kickstarts paths in weird places. You need at least 68020 selected for WHDLoad (and 3.1 A1200 kickstart ROM) and just make sure '24-bit addressing' is ticked and the game works fine even if you go left at the beginning of the level.

**Comment by ransom1122** [comment] 2017-05-07 13:09
I use a ps3 controller through bluetooth. As for my configs im not expecting you to carbon copy them as naturally paths will be all over the place. They're there to match and compare to non working configs.

As blinkydoos says though 24 bit addressing seems to fix a lot of issues anyway.

**Comment by ukshark** [comment] 2017-05-07 13:14
Yeah sorry, I changed the paths to match my setup (and controller settings), i took that as presumed which is my fault. I will try a bluetooth controller to rule out USB issue.

**Comment by GreenRebel** [comment] 2017-05-07 14:44
Turrican 2 works for me now by generating a new uae, then only changes are: selecting '24-bit' but de-selecting 'JIT'.

**Comment by ukshark** [comment] 2017-05-07 16:17
Works a treat after doing the above :) thanks all

**Comment by midwan** [comment] 2017-10-07 08:31
I assume this is resolved with the cfg changes mentioned, therefore I'm closing it.
We'll be testing things again with the upcoming version of course, just in case...

**Closed by midwan** 2017-10-07 08:31 UTC
Labels: bug
