### ISSUE TITLE
Ctrl+WinLeft+WinRight don't work to reset the emulation (bug?)

### ISSUE THREAD

**Issue by ariath** [midwan/amiberry#16] opened 2016-09-24 12:33 UTC
Hi all!

I don't know if this is a bug or there is another working key combination, but i tried restarting the emulation with Ctrl+Left windows+Right window (would correspond to Ctrl+Left Amiga+Right Amiga i think) and the key combination doesn't seem to be recognized. Nothing happens.

See ya!

**Comment by midwan** [comment] 2016-09-24 21:22
This combination of keys should have worked, let me try to see what's going on.

**Comment by n0rt0nthec4t** [comment] 2016-10-01 21:35
Interesting thing I've noticed is that what ever custom key is assigned to bring up the emulator menu, pressing left amiga key still also brings up menu. I'll have to check my key mapping file for keyrah to make sure got that key mapped correctly first.  Same thing happens in chips code too

**Comment by midwan** [comment] 2016-12-19 09:33
I noticed that the Right Menu key, when used in combination with the rest (LCtrl + LWin) does cause a reset like it should. Not a complete solution yet, but at least a workaround (both RMenu and RWin should work).

**Comment by midwan** [comment] 2016-12-20 08:45
I found out what is causing this, working on a fix now.

**Comment by midwan** [comment] 2016-12-20 10:39
Hm, this is a bit more tricky than I thought. It seems it might be a bug in the keyboard input from fbcon.
When running the emulator from the console, it uses fbcon to get any input directed to SDL. Under that scenario, the LWin key is detected as LAlt for some reason. The problem is, the RWin key is ALSO detected as LAlt.

When running under X11, that's not an issue as both keys return their correct symcode (LSUPER and RSUPER respectively).

We'll need to investigate if there's a way around this.

**Comment by midwan** [comment] 2017-01-24 08:30
Fixed in the SDL2 branch, not sure if it's worth doing more on the SDL1.x anymore if we get that one fully working. Closing this issue for now, we can re-open it if necessary (e.g. SDL2 branch has unforeseen delays)

**Closed by midwan** 2017-01-24 08:30 UTC
Labels: bug
