### ISSUE TITLE
Amiberry Bezel support

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#400] opened 2019-01-05 10:53 UTC
Hi guys.

Long time no chat. Glad to see there is still activity Including android porting.. 

I have a question not sure if it's been asked. But is it possible to get some kind of bezel support for amiberry. I am creating my own custom psx bezels for retroarch and was hoping I could make them for Amiga!!!
Here is my preview 
[IMG]http://i67.tinypic.com/bj92l3.png[/IMG]

**Comment by Darknior** [comment] 2019-01-05 16:42
Hi :)
Yes i speak about it yesterday with a friend, it is one of the only thing Amiberry miss now we have filters in SDL2 :p 
And AIMGA is 4/3, there are many black zone on the TV :( Border can hide them ;)
The best idea if possible is to have a default.png bezel, and one by game with the same name of the game. Like on Retroarch. It can be cool to adapt it to each games, PAL or NTSC ...
Thanks a lot for all your work :)

**Comment by waal** [comment] 2019-01-05 16:47
Hey, 

Long time either. I'm glad to see there have been some improvements.  Indeed, bezel support could be nice. I have in mind what we have available with FS-UAE.

**Comment by midwan** [comment] 2019-01-05 16:52
Hi guys,
This is a dupe of #364 - let's keep the discussion there please. :)

**Closed by midwan** 2019-01-05 16:52 UTC
Labels: duplicate
