### ISSUE TITLE
Amiberry - Retroarch Quit Not Responding

### ISSUE THREAD

**Issue by GeorgeSpiggott** [midwan/amiberry#394] opened 2018-12-20 23:08 UTC
I cannot quit out of Amiberry with WHDload or .ADF games (any games I try) using the Retroarch Quit buttons. Buttons do not respond. but all other game related controls seem to work including pause on the 'Start' button.. Retroarch Quit works in all my other emulators (N64, SNES, PS1, Neo Geo etc.)

Using a Raspberry Pi3B+ Retroarch version v 4.4.2? (image downloaded from the Retropie site last month, updated last week). Amiberry v 2.21. Joypad is Xbox One 2016 Bluetooth. 

Function key is permanently set to 'none' on this screen (if I change it to 'hotkey' it changes back when I quit out):
https://github.com/midwan/amiberry/wiki/Setting-up-Input-Controllers#verify-retroarch-controller-mapping

Some more relevant information may be gleaned from this thread:
https://retropie.org.uk/forum/topic/20224/amiga-emulation-combining-pad-and-mouse-onto-one-controller/12

Thanks for any help you can provide

**Comment by GeorgeSpiggott** [comment] 2018-12-23 19:05
Some screenshots that may be of use. I have reinstalled from both binary and source.

Paths, input and custom menus in the GUI.
![2018-12-23 11 31 19](https://user-images.githubusercontent.com/45982104/50386778-2b956800-06e5-11e9-9373-ed2f2b9d2352.jpg)
![2018-12-23 11 31 45](https://user-images.githubusercontent.com/45982104/50386779-2b956800-06e5-11e9-96a6-b48506627e2f.jpg)
![2018-12-23 11 31 55](https://user-images.githubusercontent.com/45982104/50386780-2b956800-06e5-11e9-98ee-d2a6944c3c9c.jpg)

My controller setup, filename Xbox Wireless Controller.cfg
![48408696_1420995931365866_2789981309185818624_n](https://user-images.githubusercontent.com/45982104/50386782-45cf4600-06e5-11e9-8624-d46d2b10ef79.jpg)

**Comment by dudleydes** [comment] 2018-12-24 08:43
In the `Custom controls` panel, the Function Key is set to `None`. Change this to `HotKey` and you should be good.

**Comment by GeorgeSpiggott** [comment] 2018-12-25 11:12
I can do that but when I quit or save the option is not selected when I go back in.

**Comment by HoraceAndTheSpider** [comment] 2018-12-29 23:46
I have responded to this on Facebook already.

The “hotkey” button is not an option to be set - it simply changes the panel to allow you to map various other hotkey combinations - this is why it always reverts, because it’s is no different to clicking one of the other menu tabs. 

If it click that button it should show you where your hotkey+quit is mapped. I have yet to see a screenshot of this.

**Comment by GeorgeSpiggott** [comment] 2018-12-30 03:07
![20181230_025746](https://user-images.githubusercontent.com/45982104/50544002-a972db00-0bdf-11e9-9e7c-51e298f4ca42.jpg)

Apologies and thanks. Screenshot as requested.

**Comment by HoraceAndTheSpider** [comment] 2018-12-30 11:31
So your pad buttons are being correct detected for quit by Amiberry.

Is “retroarch quit” checked on the most panel? 
Are you launching your WHDLoad games using the LHA booter?
Is the hostprefs file set to have retroarch quit enabled?

**Comment by midwan** [comment] 2018-12-30 11:43
@HoraceAndTheSpider I think you meant the "Misc" panel, which is where the "Retroarch Quit" checkbox is located. :)

**Comment by HoraceAndTheSpider** [comment] 2018-12-30 12:49
Thanks! Damn phone autocorrect!

**Comment by GeorgeSpiggott** [comment] 2018-12-30 23:16
> Is “retroarch quit” checked on the misc. panel?

Yes. 

> Are you launching your WHDLoad games using the LHA booter?

Not sure. I'm selecting them from the list on the Retroarch Amiga section. They are .LHA files. Games loaded as .AFD files also would not quit. 

> Is the hostprefs file set to have retroarch quit enabled?

Looks like it. Full text copy pasted from /retropie/configs/amiga/amyberry/whdboot/hostprefs.conf

CONTROLLER_1=joy1
CONTROLLER_2=joy2
CONTROLLER_3=joy0
;CONTROLLER_4=
CONTROLLER_MOUSE_1=joy1
CONTROLLER_MOUSE_2=joy2
;RETROARCH_QUIT=TRUE
;RETROARCH_MENU=TRUE
;RETROARCH_RESET=TRUE
;KEY_FOR_QUIT=F12
;KEY_FOR_MENU=F11
;DEADZONE=
STEREO_SPLIT=1
;SOUND_ON=FALSE
;ASPECT_RATIO_FIX=TRUE
;FRAMESKIP=TRUE

**Comment by midwan** [comment] 2018-12-30 23:33
@GeorgeSpiggott 
The `hostprefs.conf` file has some lines commented out (starting with ";" means they are a comment), and the RETROARCH_QUIT is one of them. Try removing the ";" from that line (and any other you want to enable) and test again?

**Comment by GeorgeSpiggott** [comment] 2018-12-30 23:45
Edited thusly. No effect.

CONTROLLER_1=joy1
CONTROLLER_2=joy2
CONTROLLER_3=joy0
;CONTROLLER_4=
CONTROLLER_MOUSE_1=joy1
CONTROLLER_MOUSE_2=joy2
RETROARCH_QUIT=TRUE
RETROARCH_MENU=TRUE
;RETROARCH_RESET=TRUE
;KEY_FOR_QUIT=F12
;KEY_FOR_MENU=F11
;DEADZONE=
STEREO_SPLIT=1
;SOUND_ON=FALSE
;ASPECT_RATIO_FIX=TRUE
;FRAMESKIP=TRUE

**Comment by Mangaclub** [comment] 2019-01-03 14:11
i had the same problem with amiberry before and my arcade cutom joystick. The problem is the config file created by retroarch or Emulation station. Retroarch joypad config files are somehow not read sucesfully there. Look in /opt/retropie/configs/all/retroarch/autoconfig
There a cfg file of your jopad should be. 
back that up and then look in the udev folder for the same file. those are the default config files. copy the default one to /opt/retropie/configs/all/retroarch/autoconfig and add the line input_exit_emulator_btn = "0" (or whatever button yu use to exit) in it. change all other buttons according to your backed up config manually. that solved it for me.

**Comment by GeorgeSpiggott** [comment] 2019-01-06 03:13
While I was attempting this I discovered that there are folders called retorarch and retroarch-joypads. Both have a folder in them called autoconfig along with the joypad config files, if you open autoconfig there is another autoconfig folder along with the joypad config files. And in that folder the same contents (for a great many subfolders in depth) is this normal?

**Comment by GeorgeSpiggott** [comment] 2019-01-13 17:04
I'm still playing with this trying to find a solution. I see that the creator of this video had the same issue an is using the same pad as me.

https://m.youtube.com/watch?v=nruqQ7muVPc

I have noticed that the start button (11) works fine (pauses game, enters letter P) however it continues to do this when the Xbox/Hotkey (16) is held down at the same time. Surely it should quit the game (or do nothing) in this situation. I wonder if the issue lies in detecting that (Xbox 16) is being pressed. Does (Xbox 16) have any other function in the emulator?

**Comment by HoraceAndTheSpider** [comment] 2019-01-19 12:50
If someone will lend me an Xbox pad , I’d be happy to look into it properly.

I’m wondering if there is a 0-15button limit somewhere by accident

**Comment by GeorgeSpiggott** [comment] 2019-01-20 00:18
Thanks. I've done a bit more experimenting with changing the Hotkey for other buttons and I've made another breakthrough.

If I assign the Hoykey to the 'Y button'/Amiberry 'West' (Button 3) I can Hotkey Quit in conjunction with 'Start' (button 11) from Amiberry with my Xbox Pad. I can do the same with the 'Right Analogue' (button 14). There's definitely a button limit at 14 as buttons 15 and 16 ('Select'/'Back' and 'Xbox' respectively) don't respond.

As a temporary fix is there a way to make Amiberry (only) accept button 14 as the Hotkey as part of Hostprefs or some such?

**Comment by midwan** [comment] 2019-11-10 17:53
@GeorgeSpiggott 
Have you tried with the current `dev` version?
Could you please let me know what the situation is with that, since we're preparing this for the next release? From what I can see, the absolute limit is currently 16 buttons (used to be 14), so maybe this is fixed.

**Comment by GeorgeSpiggott** [comment] 2019-11-10 23:55
@midwan 
I haven't used the Xbox pad with my Pi for some time. The Retropie environment (including Amiberry) was a smoother experience on a PS3 Pad so that's the one I use now. Even that is (was) super shaky with the 5.1 build of Retropie so I 'm wary about updating anything on it in case I break the Bluetooth joy pad connection completely again.

I'll have a look at my version of Amiberry (not updated from the vanilla 5.1 Retropie image) and try using a wired Xbox pad ASAP. Looking further ahead I'm going to pick up a Pi4/Lakka build at the end of the month. I'll be sure to test out all the options on that.

**Comment by Brownmonster** [comment] 2019-11-29 11:35
I have done alot of fixes for this today, I'll get them pushed up.

In short it now allows "Retroarch keyboard as joystick" to use the hotkey like joysticks
It also allows ? 1 joystick when using retroarch as keyboard. This is because out of the box 2 arcade sticks plugged into an iPac2 does not work in the current code base.

**Comment by midwan** [comment] 2020-02-18 11:59
I believe this has been fixed now, but let me know if I'm mistaken...

**Closed by midwan** 2020-02-18 11:59 UTC
Labels: question

**Comment by davince72** [comment] 2020-06-01 09:34
Updating amiberry solved the problem at my site...seemed i was a bit behind ;-)
